- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - StarlightBarratry
  - StarlightCog
  - StarlightCork
  - StarlightExo
  - StarlightFland
  - StarlightHotel
  - StarlightLagan
  - StarlightLeth
  - StarlightLobster
  - StarlightManor
  - StarlightMing
  - StarlightOasis
  - StarlightOmega
  - StarlightOrigin
  - StarlightOrwell
  - StarlightReach
  - StarlightSaltern
  - StarlightStarboard
  - StarlightKiloton
  - StarlightElkridge
  - StarlightPrism
  - StarlightSilica
  - StarlightCluster
  - StarlightBox
# - StarlightMarathon
# - StarlightMeta
# - StarlightPacked
