using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._Starlight.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEmoteSelector : DefaultWindow
{
    private const int EmoteButtonSize = 48;
    private const int EmoteIconSize = 36;
    private const int MaxRecentEmotes = 14;

    private List<NanoChatEmoteCache.EmoteData> _displayedEmotes = new();
    private readonly Queue<string> _recentlyUsedEmotes = new();
    private string _currentCategory = "All";
    private SpriteSystem? _spriteSystem;

    public event Action<string>? OnEmoteSelected;

    public NanoChatEmoteSelector()
    {
        RobustXamlLoader.Load(this);

        _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        // Setup event handlers
        FooterCloseButton.OnPressed += _ => Close();
        ClearSearchButton.OnPressed += _ => ClearSearch();
        SearchInput.OnTextChanged += OnSearchChanged;
        OnResized += UpdateGridLayout;

        // Initialize UI
        InitializeCategoryTabs();
        LoadDisplayedEmotes();
        UpdateEmoteGrid();
        UpdateRecentEmotes();
    }

    private void InitializeCategoryTabs()
    {
        CategoryTabs.RemoveAllChildren();

        // "All" tab
        AddCategoryTab("All", "nano-chat-all-categories");

        // "Recent" tab if we have recent emotes
        if (_recentlyUsedEmotes.Count > 0)
        {
            AddCategoryTab("Recent", "nano-chat-recent-emotes");
        }

        // Category tabs from cache
        foreach (var category in NanoChatEmoteCache.Categories)
        {
            AddCategoryTab(category, category);
        }
    }

    private void AddCategoryTab(string category, string labelKey)
    {
        var button = new Button
        {
            Text = Loc.GetString(labelKey),
            StyleClasses = { StyleClass.ButtonOpenBoth },
            ToggleMode = true,
            Pressed = category == _currentCategory,
            Margin = new Thickness(0, 0, 4, 0),
        };

        button.OnPressed += _ =>
        {
            SelectCategory(category);
            UpdateCategoryTabStates();
        };

        CategoryTabs.AddChild(button);
    }

    private void UpdateCategoryTabStates()
    {
        foreach (var child in CategoryTabs.Children.OfType<Button>())
        {
            var buttonText = child.Text;
            var isCurrentCategory =
                (buttonText == Loc.GetString("nano-chat-all-categories") && _currentCategory == "All") ||
                (buttonText == Loc.GetString("nano-chat-recent-emotes") && _currentCategory == "Recent") ||
                (buttonText == _currentCategory);

            child.Pressed = isCurrentCategory;
        }
    }

    private void SelectCategory(string category)
    {
        _currentCategory = category;
        LoadDisplayedEmotes();
        UpdateEmoteGrid();
    }

    private void ClearSearch()
    {
        SearchInput.Text = string.Empty;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        var searchText = args.Text.Trim();

        if (string.IsNullOrWhiteSpace(searchText))
        {
            LoadDisplayedEmotes();
        }
        else
        {
            _displayedEmotes = NanoChatEmoteCache.SearchEmotes(searchText);
        }

        UpdateEmoteGrid();
    }

    private void LoadDisplayedEmotes()
    {
        _displayedEmotes = _currentCategory switch
        {
            "All" => NanoChatEmoteCache.AllEmotes.Values.ToList(),
            "Recent" => GetRecentEmotesData(),
            _ => NanoChatEmoteCache.GetEmotesInCategory(_currentCategory)
        };

        // Update recently used section visibility
        RecentlyUsedSection.Visible = _currentCategory == "All" &&
                                       _recentlyUsedEmotes.Count > 0 &&
                                       string.IsNullOrWhiteSpace(SearchInput.Text);
    }

    private List<NanoChatEmoteCache.EmoteData> GetRecentEmotesData()
    {
        var emotes = new List<NanoChatEmoteCache.EmoteData>();
        foreach (var emoteId in _recentlyUsedEmotes.Reverse())
        {
            if (NanoChatEmoteCache.AllEmotes.TryGetValue(emoteId, out var emote))
            {
                emotes.Add(emote);
            }
        }
        return emotes;
    }

    private void UpdateEmoteGrid()
    {
        EmoteGrid.DisposeAllChildren();
        RecentEmotesGrid.DisposeAllChildren();

        // Show/hide states
        var hasEmotes = _displayedEmotes.Count > 0;
        EmptyLabel.Visible = !hasEmotes;
        EmoteScrollContainer.Visible = hasEmotes;

        if (!hasEmotes)
        {
            EmoteCountLabel.Text = Loc.GetString("nano-chat-no-emotes");
            return;
        }

        // Update emote count
        EmoteCountLabel.Text = Loc.GetString("nano-chat-emote-count", ("count", _displayedEmotes.Count));

        // Populate grid
        var resCache = IoCManager.Resolve<IResourceCache>();

        foreach (var emote in _displayedEmotes)
        {
            var button = CreateEmoteButton(emote, resCache);
            if (button != null)
                EmoteGrid.AddChild(button);
        }

        // Populate recent emotes if visible
        if (RecentlyUsedSection.Visible)
        {
            foreach (var emoteId in _recentlyUsedEmotes.Reverse().Take(MaxRecentEmotes))
            {
                if (NanoChatEmoteCache.AllEmotes.TryGetValue(emoteId, out var emote))
                {
                    var button = CreateEmoteButton(emote, resCache, isCompact: true);
                    if (button != null)
                        RecentEmotesGrid.AddChild(button);
                }
            }
        }

        UpdateGridLayout();
    }

    private Button? CreateEmoteButton(NanoChatEmoteCache.EmoteData emote, IResourceCache resCache, bool isCompact = false)
    {
        Texture? texture = null;

        switch (emote.Sprite)
        {
            case SpriteSpecifier.Texture texSpecifier:
                if (!resCache.TryGetResource<TextureResource>(texSpecifier.TexturePath, out var textureResource))
                    return null;
                texture = textureResource.Texture;
                break;

            case SpriteSpecifier.Rsi rsiSpecifier:
                try
                {
                    var state = _spriteSystem!.GetState(rsiSpecifier);
                    texture = state.Frame0;
                }
                catch
                {
                    return null;
                }
                break;

            default:
                return null;
        }

        var buttonSize = isCompact ? 40 : EmoteButtonSize;
        var iconSize = isCompact ? 30 : EmoteIconSize;

        var button = new Button
        {
            MinSize = new Vector2(buttonSize, buttonSize),
            MaxSize = new Vector2(buttonSize, buttonSize),
            ToolTip = $":{emote.Id}: - {emote.DisplayName}",
            StyleClasses = { StyleClass.ButtonOpenBoth },
        };

        var textureRect = new TextureRect
        {
            Texture = texture,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MinSize = new Vector2(iconSize, iconSize),
            MaxSize = new Vector2(iconSize, iconSize),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        button.AddChild(textureRect);

        button.OnPressed += _ =>
        {
            OnEmoteSelected?.Invoke($":{emote.Id}:");
            TrackRecentEmote(emote.Id);
            Close();
        };

        return button;
    }

    private void TrackRecentEmote(string emoteId)
    {
        // Remove if already exists (to move to front)
        while (_recentlyUsedEmotes.Contains(emoteId))
        {
            var temp = _recentlyUsedEmotes.ToList();
            temp.Remove(emoteId);
            _recentlyUsedEmotes.Clear();
            foreach (var id in temp)
                _recentlyUsedEmotes.Enqueue(id);
        }

        // Add to front
        var tempQueue = new Queue<string>();
        tempQueue.Enqueue(emoteId);
        foreach (var id in _recentlyUsedEmotes)
            tempQueue.Enqueue(id);

        _recentlyUsedEmotes.Clear();
        foreach (var id in tempQueue.Take(MaxRecentEmotes))
            _recentlyUsedEmotes.Enqueue(id);
    }

    private void UpdateGridLayout()
    {
        const int scrollbarWidth = 12;
        var availableWidth = EmoteScrollContainer.PixelSize.X - scrollbarWidth;

        if (availableWidth <= 0)
            return;

        var columns = Math.Max(1, (int)(availableWidth / EmoteButtonSize));
        if (EmoteGrid.Columns != columns)
        {
            EmoteGrid.Columns = columns;
        }
    }

    public List<string> GetRecentEmotes() => _recentlyUsedEmotes.ToList();

    public void LoadRecentEmotes(List<string> recent)
    {
        _recentlyUsedEmotes.Clear();
        foreach (var emoteId in recent.Take(MaxRecentEmotes))
        {
            _recentlyUsedEmotes.Enqueue(emoteId);
        }
        InitializeCategoryTabs();
        UpdateRecentEmotes();
    }

    private void UpdateRecentEmotes()
    {
        RecentlyUsedSection.Visible = _recentlyUsedEmotes.Count > 0 &&
                                       _currentCategory == "All" &&
                                       string.IsNullOrWhiteSpace(SearchInput.Text);
    }
}
