using Content.Shared._Starlight.Medical.Virology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Medical.Virology;

[GenerateTypedNameReferences]
public sealed partial class PathogenAnalyzerWindow : DefaultWindow
{
    public PathogenAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PathogenAnalyzerUiState state)
    {
        TargetNameLabel.Text = state.TargetName;
        TargetKindLabel.Text = Loc.GetString(
            $"pathogen-analyzer-target-{state.TargetKind.ToString().ToLowerInvariant()}");
        Results.RemoveAllChildren();

        if (state.Pathogens.Count == 0)
        {
            Results.AddChild(new Label
            {
                Text = Loc.GetString("pathogen-analyzer-none"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        foreach (var pathogen in state.Pathogens)
        {
            Results.AddChild(new Label
            {
                Text = pathogen.Heading,
                StyleClasses = { "LabelHeading" },
            });
            Results.AddChild(new Label { Text = pathogen.Context });

            if (!pathogen.FullyIdentified)
            {
                Results.AddChild(new Label
                {
                    Text = Loc.GetString("pathogen-analyzer-incomplete"),
                    StyleClasses = { "LabelSubText" },
                });
                continue;
            }

            AddField("pathogen-analyzer-field-classification", pathogen.Classification);
            AddField("pathogen-analyzer-field-tier", pathogen.Tier);
            AddField("pathogen-analyzer-field-origin", pathogen.Origin);
            AddField("pathogen-analyzer-field-symptoms", pathogen.Symptoms);
            AddField("pathogen-analyzer-field-incubation", pathogen.Incubation);
            AddField("pathogen-analyzer-field-duration", pathogen.Duration);
            AddField("pathogen-analyzer-field-transmissibility", pathogen.Transmissibility);
            AddField("pathogen-analyzer-field-bypass", pathogen.ProtectionBypass);
            AddField("pathogen-analyzer-field-prevalence", pathogen.MaxPrevalence);
        }
    }

    private void AddField(string labelKey, string value)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };
        row.AddChild(new Label
        {
            Text = Loc.GetString(labelKey),
            MinWidth = 135,
            StyleClasses = { "LabelSubText" },
        });
        row.AddChild(new RichTextLabel
        {
            Text = value,
            HorizontalExpand = true,
        });
        Results.AddChild(row);
    }
}
