using System.Linq;
using Content.Shared.Chat;
using Content.Shared.CCVar;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;
using Content.Shared.Radio;
using Robust.Shared.Prototypes;
#region Starlight
using Content.Client._Starlight.TextToSpeech;
#endregion

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChannelFilterPopup : Popup
{
    // Starlight begin
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    // Starlight end
    // order in which the available channel filters show up when available
    private static readonly ChatChannel[] ChannelFilterOrder =
    {
        ChatChannel.Local,
        ChatChannel.Whisper,
        ChatChannel.Emotes,
        ChatChannel.Radio,
        ChatChannel.Notifications,
        ChatChannel.LOOC,
        ChatChannel.OOC,
        ChatChannel.Dead,
        ChatChannel.Admin,
        ChatChannel.AdminAlert,
        ChatChannel.AdminChat,
        ChatChannel.Server
    };

    private readonly Dictionary<ChatChannel, ChannelFilterCheckbox> _filterStates = new();

    public event Action<ChatChannel, bool>? OnChannelFilter;
    public event Action<string>? OnNewHighlights;

    // Starlight start
    private readonly Dictionary<ProtoId<RadioChannelPrototype>, CheckBox> _ttsMuteStates = new();
    private TextToSpeechStreamSystem? _ttsStream;
    private TextToSpeechSystem? _tts;
    // Starlight end

    public ChannelFilterPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Starlight

        HighlightButton.OnPressed += HighlightsEntered;
        // Add a placeholder text to the highlights TextEdit.
        HighlightEdit.Placeholder = new Rope.Leaf(Loc.GetString("hud-chatbox-highlights-placeholder"));

        // Load highlights if any were saved.
        string highlights = _cfg.GetCVar(CCVars.ChatHighlights); // Starlight

        if (!string.IsNullOrEmpty(highlights))
        {
            UpdateHighlights(highlights);
        }

        // Starlight start
        InitializeTTSMuteChannels();
        TTSClearQueueButton.OnPressed += _ => ClearQueue();
        TTSToggleAllButton.OnPressed += _ => ToggleAllTTSMuteCheckboxes();
        // Starlight end
    }
    // Starlight start

    private void ClearQueue()
    {
        if (_tts == null)
        {
            _tts = _entityManager.System<TextToSpeechSystem>();
        }
        _tts?.ClearQueue();
    }

    // Creates checkbox toggle mute buttons for each defined Radio channel prototype
    private void InitializeTTSMuteChannels()
    {
        foreach (var channel in _protoManager.EnumeratePrototypes<RadioChannelPrototype>()
                     .OrderBy(channel => Loc.GetString(channel.Name)))
        {
            var checkbox = new CheckBox
            {
                Text = Loc.GetString(channel.Name),
                Pressed = false
            };

            var channelId = channel.ID;
            checkbox.OnToggled += args => SetChannelMuteState(channelId, args.Pressed);

            _ttsMuteStates[channel.ID] = checkbox;
            TTSChannelsVBox.AddChild(checkbox);
        }
    }

    // Toggles all mute buttons on, then off, and so on
    private void ToggleAllTTSMuteCheckboxes()
    {
        bool allChecked = _ttsMuteStates.Values.All(checkbox => checkbox.Pressed);
        bool newState = !allChecked;

        foreach (var (channelId, checkbox) in _ttsMuteStates)
        {
            checkbox.Pressed = newState;
            SetChannelMuteState(channelId, newState);
        }
    }

    // Function to apply the mute state from the UI to the TTS system for a specific channel
    private void SetChannelMuteState(ProtoId<RadioChannelPrototype> channelId, bool muted)
    {
        _ttsStream ??= _entityManager.System<TextToSpeechStreamSystem>();
        _ttsStream.SetChannelMuted(channelId, muted);
    }

    // Starlight end

    public bool IsActive(ChatChannel channel)
    {
        return _filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed;
    }

    public void SetActive(ChatChannel channel, bool isActive)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed != isActive)
        {
            checkbox.Pressed = isActive;
            OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }

    public ChatChannel GetActive()
    {
        ChatChannel active = 0;

        foreach (var (key, value) in _filterStates)
        {
            if (value.IsHidden || !value.Pressed)
            {
                continue;
            }

            active |= key;
        }

        return active;
    }

    public void SetChannels(ChatChannel channels)
    {
        foreach (var channel in ChannelFilterOrder)
        {
            if (!_filterStates.TryGetValue(channel, out var checkbox))
            {
                checkbox = new ChannelFilterCheckbox(channel);
                _filterStates.Add(channel, checkbox);
                checkbox.OnPressed += CheckboxPressed;
                checkbox.Pressed = true;
            }

            if ((channels & channel) == 0)
            {
                if (checkbox.Parent == FilterVBox)
                {
                    FilterVBox.RemoveChild(checkbox);
                }
            }
            else if (checkbox.IsHidden)
            {
                FilterVBox.AddChild(checkbox);
            }
        }
    }

    public void UpdateHighlights(string highlights)
    {
        HighlightEdit.TextRope = new Rope.Leaf(highlights);
    }

    private void CheckboxPressed(ButtonEventArgs args)
    {
        var checkbox = (ChannelFilterCheckbox)args.Button;
        OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
    }

    private void HighlightsEntered(ButtonEventArgs _args)
    {
        OnNewHighlights?.Invoke(Rope.Collapse(HighlightEdit.TextRope));
    }

    public void UpdateUnread(ChatChannel channel, int? unread)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox))
            checkbox.UpdateUnreadCount(unread);
    }
}
