using Content.Client._Starlight.UserInterface; // Starlight
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Shuttles.BUIStates;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // Starlight
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : PopOutFancyWindow, // Starlight: popout support
    IComputerWindow<NavInterfaceState>
{
    protected override Control Control => RadarScreen; // Starlight: popout support

    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavInterfaceState scc, DockingPortStates dockingPortStates)  // Starlight: +dockingPortStates
    {
        RadarScreen.UpdateState(scc, dockingPortStates);  // Starlight: +dockingPortStates
    }
}
