# Wizard Duelists
- type: entity
  parent: MindRoleWizard
  id: MindRoleWizardDuelistBase
  name: Wizard Duelist Role
  components:
  - type: MindRole
    roleType: SoloAntagonist # Starlight, no Free Agents
    antagPrototype: Wizard
    exclusiveAntag: true
    subtype: role-subtype-wizard

- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistRed
  name: Red Wizard Duelist Role
  components:
  - type: WizardDuelistRedRole

- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistBlue
  name: Blue Wizard Duelist Role
  components:
  - type: WizardDuelistBlueRole

- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistViolet
  name: Violet Wizard Duelist Role
  components:
  - type: WizardDuelistVioletRole

# Starlight start
- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistYellow
  name: Yellow Wizard Duelist Role
  components:
  - type: WizardDuelistYellowRole

- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistGreen
  name: Green Wizard Duelist Role
  components:
  - type: WizardDuelistGreenRole

- type: entity
  parent: MindRoleWizardDuelistBase
  id: MindRoleWizardDuelistOrange
  name: Orange Wizard Duelist Role
  components:
  - type: WizardDuelistOrangeRole
# Starlight end
