using Content.Client.Pinpointer.UI;
using Content.Shared._Starlight.Holograms;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._Starlight.Holograms.UI;

[GenerateTypedNameReferences]
public sealed partial class HologramConsoleWindow : BaseWindow
{
    private readonly IEntityManager _entManager;
    private readonly SpriteSystem _spriteSystem;
    
    private NetEntity? _selectedBladeServer;
    private NetEntity? _selectedProjector;
    private bool _isPortableMode;
    private readonly Texture? _blipTexture;
    private HologramConsoleBoundUserInterfaceState? _currentState;

    public event Action<NetEntity, NetEntity>? OnProjectHologram;
    public event Action? OnRecallHologram;
    public event Action<NetEntity>? OnEjectBladeServer;
    public event Action<bool>? OnToggleCarry;

    public HologramConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        
        var dependencies = IoCManager.InitThread();
        _entManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entManager.System<SpriteSystem>();
        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        // Initialize NavMap as hidden until server is connected
        NavMap.Visible = false;
        NoServerOverlay.Visible = true;

        ProjectButton.OnPressed += _ =>
        {
            if (_selectedBladeServer.HasValue)
            {
                // In portable mode, projector selection is not needed use dummy NetEntity
                var projector = _isPortableMode ? NetEntity.Invalid : (_selectedProjector ?? NetEntity.Invalid);
                OnProjectHologram?.Invoke(_selectedBladeServer.Value, projector);
            }
        };

        RecallButton.OnPressed += _ => OnRecallHologram?.Invoke();
        
        AllowCarryCheckbox.OnToggled += args => OnToggleCarry?.Invoke(args.Pressed);
        
        // NavMap click event
        NavMap.TrackedEntitySelectedAction += OnProjectorSelectedFromMap;
    }
    
    private void OnProjectorSelectedFromMap(NetEntity? netEntity)
    {
        if (netEntity.HasValue)
        {
            _selectedProjector = netEntity.Value;
            UpdateSelectionStateAfterChange();
        }
    }
    
    private void SetupNavMap(HologramConsoleBoundUserInterfaceState state)
    {
        // Ensure NavMap is visible before setting up
        NavMap.Visible = true;
        
        // Get the first projector's grid for the NavMap
        if (state.ProjectorCoordinates.Count > 0)
        {
            var firstNetCoords = state.ProjectorCoordinates.Values.First();
            var firstCoords = _entManager.GetCoordinates(firstNetCoords);
            
            if (_entManager.TryGetComponent<TransformComponent>(firstCoords.EntityId, out var xform))
            {
                NavMap.MapUid = xform.GridUid;
            }
        }
        
        // Update projector blips on the map
        UpdateNavMapBlips(state);
        
        // Force map update
        NavMap.ForceNavMapUpdate();
    }
    
    private void UpdateNavMapBlips(HologramConsoleBoundUserInterfaceState state)
    {
        if (_blipTexture == null)
            return;
            
        // Clear existing projector blips
        NavMap.TrackedEntities.Clear();
        
        // Add projector blips
        foreach (var (netEntity, netCoords) in state.ProjectorCoordinates)
        {
            var entityCoords = _entManager.GetCoordinates(netCoords);
            var isSelected = netEntity == _selectedProjector;
            
            // Get color from NavMapControl based on selection
            var color = NavMap.GetProjectorColor(isSelected);
            
            NavMap.TrackedEntities[netEntity] = new NavMapBlip(entityCoords, _blipTexture, color, true, true);
        }
    }
    
    private void UpdateSelectionStateAfterChange()
    {
        if (_currentState != null)
        {
            UpdateSelectionState(_currentState);
            UpdateNavMapBlips(_currentState);
        }
    }

    public void UpdateState(HologramConsoleBoundUserInterfaceState state)
    {
        _currentState = state;
        
        // Configure for portable or stationary mode
        var isPortable = state.IsPortable;
        _isPortableMode = isPortable;
        
        BatteryPanel.Visible = isPortable;
        SettingsPanel.Visible = isPortable;
        ModeLabel.Visible = isPortable;
        
        // Control UI element visibility
        MapPanel.Visible = state.ShowMap;
        LeftPanel.Visible = state.ShowBladeServerPanel;
        ProjectButton.Visible = state.ShowProjectButton;
        RecallButton.Visible = state.ShowRecallButton;
        ControlsPanel.Visible = state.ShowProjectButton || state.ShowRecallButton;
        
        if (isPortable)
        {
            ModeLabel.Text = "PORTABLE MODE";
            
            // Hide NavMap in portable mode
            NavMap.Visible = false;
            NoServerOverlay.Visible = false;
            
            // Update battery
            if (state.BatteryPercent.HasValue)
            {
                var percent = state.BatteryPercent.Value;
                BatteryBar.Value = Math.Clamp(percent / 100f, 0f, 1f);
                BatteryLabel.Text = $"{percent:F0}%";
                
                // Color code battery
                if (percent > 50)
                {
                    BatteryLabel.FontColorOverride = Color.FromHex("#10b981");
                    BatteryBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#10b981") };
                }
                else if (percent > 20)
                {
                    BatteryLabel.FontColorOverride = Color.FromHex("#fbbf24");
                    BatteryBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#fbbf24") };
                }
                else
                {
                    BatteryLabel.FontColorOverride = Color.FromHex("#ef4444");
                    BatteryBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#ef4444") };
                }
            }
            
            AllowCarryCheckbox.Pressed = state.AllowCarry;
            
            PortableInfoLabel.Visible = true;
            PortableInfoLabel.Text = $"Active: {state.ActiveCount} / {state.MaxActive}";
        }
        else
        {
            PortableInfoLabel.Visible = false;
            
            // Check if connected to hologram server machine (NOT blade servers)
            if (!state.HasServer)
            {
                // Debug: Confirm we're in the no-server path
                
                // Show overlay that covers the NavMap
                NoServerOverlay.Visible = true;
                NavMap.Visible = false;
                
                // Clear any existing NavMap data
                NavMap.TrackedEntities.Clear();
                NavMap.MapUid = null;
                
                // Clear UI elements
                StatusLabel.Text = "No server connected";
                StatusLabel.FontColorOverride = Color.FromHex("#ef4444");
                ActiveIndicator.Text = "● OFFLINE";
                ActiveIndicator.FontColorOverride = Color.FromHex("#ef4444");
                
                // Don't set up NavMap - no HologramServer machine
                return;
            }
            
            // Hide overlay and show NavMap when connected to HologramServer machine
            NoServerOverlay.Visible = false;
            NavMap.Visible = true;
            
            // Check if blade servers are available for hologram list
            if (state.BladeServers.Count == 0)
            {
                // Show no blade servers label
                NoBladeServersLabel.Visible = true;
                
                // Clear blade servers list
                BladeServersList.RemoveAllChildren();
                StatusLabel.Text = "No blade servers available";
                StatusLabel.FontColorOverride = Color.FromHex("#ef4444");
                ActiveIndicator.Text = " ● NO DATA ";
                ActiveIndicator.FontColorOverride = Color.FromHex("#6b7280");
                
                ProjectButton.Disabled = true;
                RecallButton.Disabled = true;
            }
            else
            {
                // Hide no blade servers label when blade servers exist
                NoBladeServersLabel.Visible = false;
            }
        }
        
        // Set up NavMap for stationary mode (when connected to HologramServer machine)
        if (!isPortable && state.HasServer)
        {
            SetupNavMap(state);
        }

        // Update status
        if (state.BladeServers.Count == 0)
        {
            StatusLabel.Text = "No blade servers available";
            StatusLabel.FontColorOverride = Color.FromHex("#ef4444");
            ActiveIndicator.Text = " ● NO DATA ";
            ActiveIndicator.FontColorOverride = Color.FromHex("#6b7280");
            
            // Clear blade server list but keep it visible
            BladeServersList.RemoveAllChildren();
            
            ProjectButton.Disabled = true;
            RecallButton.Disabled = true;
        }
        else
        {
            StatusLabel.Text = $"{state.BladeServers.Count} hologram(s) available";
            StatusLabel.FontColorOverride = Color.FromHex("#7dd3fc");
            
            var hasActive = state.ActiveHologram != null || state.ActiveCount > 0;
            ActiveIndicator.Text = hasActive ? "● ACTIVE" : "● READY";
            ActiveIndicator.FontColorOverride = hasActive ? Color.FromHex("#10b981") : Color.FromHex("#fbbf24");
            
            // Update blade server list
            BladeServersList.RemoveAllChildren();
            foreach (var bladeServer in state.BladeServers)
            {
                var bladeServerEntry = new BladeServerListEntry(bladeServer, hasActive && bladeServer.IsActive);
                bladeServerEntry.OnSelected += () =>
                {
                    _selectedBladeServer = bladeServer.Uid;
                    UpdateSelectionState(state);
                };
                bladeServerEntry.OnEject += () => OnEjectBladeServer?.Invoke(bladeServer.Uid);
                BladeServersList.AddChild(bladeServerEntry);
            }
            
            RecallButton.Disabled = !hasActive;
        }

        // Update projector count and map (both modes)
        ProjectorCountLabel.Text = state.Projectors.Count > 0 ? $" {state.Projectors.Count} Projectors " : " No Projectors ";
        
        // Set up NavMap
        SetupNavMap(state);
        
        // In stationary mode, disable project button if no projectors
        if (!isPortable && state.Projectors.Count == 0)
        {
            ProjectButton.Disabled = true;
        }

        UpdateSelectionState(state);
    }

    private void UpdateSelectionState(HologramConsoleBoundUserInterfaceState state)
    {
        // Update blade server selections
        foreach (var child in BladeServersList.Children)
        {
            if (child is BladeServerListEntry entry)
                entry.SetSelected(entry.BladeServerUid == _selectedBladeServer);
        }
        
        // Projector selection is now done via NavMap blips
        // Update map blips to reflect current selection
        if (_currentState != null)
            UpdateNavMapBlips(_currentState);

        // Enable project button based on mode
        if (state.IsPortable)
        {
            // Portable: just need a blade server, projects at briefcase location
            ProjectButton.Disabled = _selectedBladeServer == null || state.ActiveCount >= state.MaxActive;
            ProjectButton.Text = state.ActiveCount > 0 ? "▶ PROJECT ANOTHER" : "▶ PROJECT";
        }
        else
        {
            // Stationary: need blade server and projector, single active hologram
            ProjectButton.Disabled = _selectedBladeServer == null || _selectedProjector == null || state.ActiveHologram != null;
        }
    }
}

public sealed class BladeServerListEntry : PanelContainer
{
    public NetEntity BladeServerUid { get; }
    public event Action? OnSelected;
    public event Action? OnEject;
    
    private readonly PanelContainer _panel;

    public BladeServerListEntry(BladeServerInfo info, bool isActive)
    {
        BladeServerUid = info.Uid;

        _panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat 
            { 
                BackgroundColor = isActive ? Color.FromHex("#0f172a") : Color.FromHex("#1f2937"),
                BorderColor = isActive ? Color.FromHex("#10b981") : Color.FromHex("#374151"),
                BorderThickness = new Thickness(2)
            },
            Margin = new Thickness(2)
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
            SeparationOverride = 8
        };

        // Hologram info
        var infoContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2
        };

        var nameLabel = new Label
        {
            Text = info.HologramName,
            FontColorOverride = Color.FromHex("#e5e7eb")
        };
        infoContainer.AddChild(nameLabel);

        if (isActive)
        {
            var statusLabel = new RichTextLabel
            {
                SetHeight = 16
            };
            statusLabel.SetMessage(FormattedMessage.FromMarkupOrThrow("[color=#10b981]ACTIVE PROJECTION[/color]"));
            infoContainer.AddChild(statusLabel);
        }

        container.AddChild(infoContainer);

        // Eject button (before select)
        var ejectButton = new Button
        {
            Text = "⏏ EJECT",
            MinWidth = 70,
            MinHeight = 30,
            Disabled = isActive
        };
        ejectButton.OnPressed += _ => OnEject?.Invoke();
        container.AddChild(ejectButton);

        // Select button
        var selectButton = new Button
        {
            Text = "SELECT",
            MinWidth = 70,
            MinHeight = 30,
            Disabled = isActive
        };
        selectButton.OnPressed += _ => OnSelected?.Invoke();
        container.AddChild(selectButton);

        _panel.AddChild(container);
        AddChild(_panel);
    }

    public void SetSelected(bool selected)
    {
        if (selected)
        {
            _panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1e3a8a"),
                BorderColor = Color.FromHex("#3b82f6"),
                BorderThickness = new Thickness(2)
            };
        }
        else
        {
            _panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1f2937"),
                BorderColor = Color.FromHex("#374151"),
                BorderThickness = new Thickness(2)
            };
        }
    }
}
