using Content.Client.Message;
using Content.Shared._Functional.TutorialServer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Text;

namespace Content.Client._Functional.TutorialServer.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialPromptWindow : DefaultWindow
{
    public Action? OnNextPressed;
    public Action? OnHintPressed;

    public TutorialPromptWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("tutorial-server-prompt-title");

        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        HintButton.OnPressed += _ => OnHintPressed?.Invoke();
    }

    public void Populate(TutorialPromptBuiState state)
    {
        // Preserve scroll so Continue does not yank the checklist to the top.
        var previousScroll = ContentScroll.VScroll;

        if (!state.HasTutorial)
        {
            SetLabel(GoalLabel, Loc.GetString("tutorial-server-prompt-no-tutorial"));
            ChecklistLabel.Visible = false;
            SetLabel(StepLabel, string.Empty);
            SetLabel(StatusLabel, string.Empty);
            NextButton.Disabled = true;
            HintButton.Disabled = true;
            HintButton.Visible = false;
            RestoreScroll(previousScroll);
            return;
        }

        if (state.GoalCount > 0)
        {
            SetLabel(GoalLabel, Loc.GetString("tutorial-server-goal-hud",
                ("current", state.ViewGoalIndex + 1),
                ("total", Math.Max(state.GoalCount, 1)),
                ("title", state.GoalTitle)));

            var sb = new StringBuilder();
            for (var i = 0; i < state.SubGoalStates.Count; i++)
            {
                var entry = state.SubGoalStates[i];
                // Avoid [] marks — SetMarkupPermissive treats them as rich-text tags and can blank the label.
                var mark = entry.Completed
                    ? "x"
                    : i == state.ViewIndex
                        ? ">"
                        : i == state.ProgressIndex
                            ? "*"
                            : "-";
                sb.AppendLine($"{mark} {FormattedMessage.EscapeText(entry.Text)}");
            }

            SetLabel(ChecklistLabel, sb.ToString().TrimEnd());
            ChecklistLabel.Visible = state.SubGoalStates.Count > 0;
            SetLabel(StepLabel, Loc.GetString("tutorial-server-subgoal-hud",
                ("current", state.ViewIndex + 1),
                ("total", Math.Max(state.StepCount, 1)),
                ("text", state.StepText)));
        }
        else
        {
            SetLabel(GoalLabel, string.Empty);
            ChecklistLabel.Visible = false;
            SetLabel(StepLabel, Loc.GetString("tutorial-server-step-hud",
                ("current", state.ViewIndex + 1),
                ("total", Math.Max(state.StepCount, 1)),
                ("text", state.StepText)));
        }

        if (state.WaitingOnSensor)
        {
            SetLabel(StatusLabel, !string.IsNullOrEmpty(state.HintText)
                ? state.HintText
                : Loc.GetString("tutorial-server-prompt-waiting"));
        }
        else
        {
            SetLabel(StatusLabel, string.Empty);
        }

        NextButton.Disabled = !state.CanGoNext;
        NextButton.Text = state.ViewComplete == TutorialStepComplete.Acknowledge
            ? Loc.GetString("tutorial-server-acknowledge")
            : Loc.GetString("tutorial-server-prompt-next");

        var hasStuckHint = !string.IsNullOrEmpty(state.StuckHintText);
        HintButton.Visible = hasStuckHint;
        HintButton.Disabled = !hasStuckHint;

        RestoreScroll(previousScroll);
    }

    private void RestoreScroll(float previousScroll)
    {
        // Defer until layout has sizes so restoring VScrollTarget sticks.
        ContentScroll.VScrollTarget = previousScroll;
        Timer.Spawn(0, () =>
        {
            if (Disposed)
                return;

            ContentScroll.VScrollTarget = previousScroll;
        });
    }

    private static void SetLabel(RichTextLabel label, string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            label.SetMessage(new FormattedMessage());
            return;
        }

        // Permissive markup so [keybind] tags resolve via KeyBindTag. SetMarkupPermissive would
        // fall through to RichTextEntry.DefaultTags, which does not include keybind and would
        // render the key as an empty gap — pass tagsAllowed: null to permit every registered tag.
        label.SetMessage(FormattedMessage.FromMarkupPermissive(text), tagsAllowed: null);
    }
}
