using Content.Client.UserInterface.Screens;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Functional.TutorialServer.UI;

/// <summary>
/// Control hints.
/// </summary>
/// <remarks>
/// Uses <see cref="Robust.Client.UserInterface.Controls.RichTextLabel"/> so
/// <c>[keybind="MoveUp"]</c> markup resolves through the guidebook's KeyBindTag against the player's own bindings.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class TutorialControlHint : Control
{
    private const float MinChatGap = 10f;

    private const float FallbackInset = 12f;

    private const float FallbackTop = 44f;

    public TutorialControlHint()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Shows the hint, or hides the banner when the markup is empty.
    /// </summary>
    public void SetHint(string markup)
    {
        if (string.IsNullOrWhiteSpace(markup))
        {
            Visible = false;
            return;
        }

        // tagsAllowed: null allows all markup.
        HintLabel.SetMessage(FormattedMessage.FromMarkupPermissive(markup), tagsAllowed: null);
        Visible = true;
    }

    /// <summary>
    /// Parks the hint immediately left of the chat box, tracking its top edge.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible)
            return;

        var right = FallbackInset;
        var top = FallbackTop;

        if (UserInterfaceManager.ActiveScreen is InGameScreen screen)
        {
            var chat = screen.ChatBox;
            if (chat is { Visible: true } && chat.Size.X > 0)
            {
                top = Math.Max(0f, chat.GlobalPosition.Y - GlobalPosition.Y);

                // Mirror the vertical inset horizontally, so the hint sits in a balanced corner
                // instead of flush against the chat box.
                var gap = Math.Max(MinChatGap, top);
                var chatLeft = chat.GlobalPosition.X - GlobalPosition.X;
                right = Math.Max(gap, Width - chatLeft + gap);
            }
        }

        var margin = new Thickness(0, top, right, 0);
        if (!HintPanel.Margin.Equals(margin))
            HintPanel.Margin = margin;
    }
}
