using System.Linq;
using System.Numerics;
using Content.Client._Starlight.Arcade.Crt;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Arcade.Lancer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Arcade.Lancer;

[GenerateTypedNameReferences]
public sealed partial class LancerArcadeWindow : FancyWindow
{
    private LancerGameStateSnapshot? _snapshot;
    private bool _isPlayer = true;
    private readonly List<string> _logLines = new();

    private float _reactionLocalTimer;
    private bool _reactionCounting;
    private int _reactionPendingDamage;

    public event Action<LancerPlayerAction, LancerGridCoord?, int, int, LancerStabilizeOption, string>? OnAction;

    private readonly Dictionary<string, Button> _missionButtons = new();
    private readonly Dictionary<Button, LancerPlayerAction> _actionButtonMap = new();
    private bool _resetConfirmPending;

    public LancerArcadeWindow()
    {
        RobustXamlLoader.Load(this);
        ArcadeCrtOverlayControl.Attach(ContentsContainer);
        BuildActionButtons();
        WireButtons();
        BoardControl.OnCellClicked += HandleCellClick;
        BoardControl.OnHexHovered += HandleHexHovered;
        DiceOverlay.BindBoard(BoardControl);
        DiceOverlay.BindColumn(BoardColumn);
    }

    private void HandleHexHovered(LancerGridCoord? coord)
    {
        if (_snapshot == null || coord == null)
        {
            HexHoverLabel.SetMarkup(LancerHexTooltip.BuildIdle());
            return;
        }

        HexHoverLabel.SetMarkup(LancerHexTooltip.Build(_snapshot, coord));
    }

    public void SetUsability(bool isPlayer)
    {
        _isPlayer = isPlayer;
        UpdateInteractivity();
    }

    public void AppendLog(string line)
    {
        _logLines.Add(line);
        if (_logLines.Count > 200)
            _logLines.RemoveAt(0);

        LogLabel.SetMarkupPermissive(string.Join("\n", _logLines));
        LogScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    public void UpdateSnapshot(LancerGameStateSnapshot snapshot)
    {
        _snapshot = snapshot;
        UpdateScreens();
        BoardControl.UpdateSnapshot(snapshot);
        if (BoardControl.HoveredCoord is { } hover)
            HandleHexHovered(hover);
        UpdateSidebar();
        UpdateWeaponPick();
        UpdateInteractivity();
    }

    public void ShowReaction(LancerReactionType reaction, float timeout, int pendingDamage = 0)
    {
        ReactionPanel.Visible = true;
        _reactionLocalTimer = timeout;
        _reactionCounting = true;
        _reactionPendingDamage = pendingDamage;
        UpdateReactionLabel(reaction);
        UpdateInteractivity();
    }

    public void EnqueueDiceRoll(LancerArcadeMessages.LancerDiceRollMessage msg)
    {
        UpdateDiceFallbackArea();
        DiceOverlay.Enqueue(msg);
    }

    public void PlayAttackEffect(LancerArcadeMessages.LancerAttackEffectMessage msg)
    {
        BoardControl.PlayEffect(msg.Cell, msg.Kind, msg.FromCell);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!_reactionCounting || _snapshot == null)
            return;

        _reactionLocalTimer -= args.DeltaSeconds;
        if (_reactionLocalTimer < 0)
            _reactionLocalTimer = 0;

        UpdateReactionLabel(_snapshot.Prompt.Reaction);
        if (_reactionLocalTimer <= 0)
            _reactionCounting = false;
    }

    private void UpdateReactionLabel(LancerReactionType reaction)
    {
        var damage = _snapshot?.Prompt.PendingDamage ?? _reactionPendingDamage;
        ReactionLabel.SetMarkup(Loc.GetString(reaction == LancerReactionType.Overwatch
            ? "lancer-arcade-overwatch-prompt"
            : "lancer-arcade-brace-prompt",
            ("damage", damage),
            ("seconds", (int) MathF.Ceiling(_reactionLocalTimer))));
    }

    private void BuildActionButtons()
    {
        AddActionButton("lancer-arcade-action-move", LancerPlayerAction.SelectMove);
        AddActionButton("lancer-arcade-action-boost", LancerPlayerAction.SelectBoost);
        AddActionButton("lancer-arcade-action-skirmish", LancerPlayerAction.Skirmish);
        AddActionButton("lancer-arcade-action-barrage", LancerPlayerAction.Barrage);
        AddActionButton("lancer-arcade-action-lock-on", LancerPlayerAction.LockOn);
        AddActionButton("lancer-arcade-action-hex", LancerPlayerAction.UseSystem, weaponIndex: 0);
        AddActionButton("lancer-arcade-action-stabilize", LancerPlayerAction.Stabilize);
        AddActionButton("lancer-arcade-action-disengage", LancerPlayerAction.Disengage);
        AddActionButton("lancer-arcade-action-overcharge", LancerPlayerAction.Overcharge);
        AddActionButton("lancer-arcade-action-core", LancerPlayerAction.ActivateCore);
        AddActionButton("lancer-arcade-action-cancel", LancerPlayerAction.Cancel);
    }

    private void AddActionButton(string locId, LancerPlayerAction action, int weaponIndex = -1)
    {
        var button = new Button { Text = Loc.GetString(locId) };
        button.OnPressed += _ => OnAction?.Invoke(action, null, weaponIndex, -1, LancerStabilizeOption.ClearHeat, "");
        _actionButtonMap[button] = action;
        ActionGrid.AddChild(button);
    }

    private void WireButtons()
    {
        IntroStartButton.OnPressed += _ => Send(LancerPlayerAction.StartGame);
        RestartButton.OnPressed += _ => Send(LancerPlayerAction.NewGame);
        MissionCompleteContinueButton.OnPressed += _ => Send(LancerPlayerAction.ContinueIntermission);
        RollSpotButton.OnPressed += _ => Send(LancerPlayerAction.RollSpot);
        BeginCombatButton.OnPressed += _ => Send(LancerPlayerAction.BeginCombat);
        PreFightDeployButton.OnPressed += _ => Send(LancerPlayerAction.BeginCombat);
        NarrativeCheck0Button.OnPressed += _ => Send(LancerPlayerAction.SelectNarrativeCheck, weaponIndex: 0);
        NarrativeCheck1Button.OnPressed += _ => Send(LancerPlayerAction.SelectNarrativeCheck, weaponIndex: 1);
        IntermissionStructureButton.OnPressed += _ => Send(LancerPlayerAction.IntermissionRepairStructure);
        IntermissionReactorButton.OnPressed += _ => Send(LancerPlayerAction.IntermissionRepairReactor);
        IntermissionContinueButton.OnPressed += _ => Send(LancerPlayerAction.ContinueIntermission);
        EndTurnButton.OnPressed += _ => Send(LancerPlayerAction.EndTurn);
        ReactionAcceptButton.OnPressed += _ => Send(LancerPlayerAction.ReactionAccept);
        ReactionDeclineButton.OnPressed += _ => Send(LancerPlayerAction.ReactionDecline);

        CampaignResetButton.OnPressed += _ =>
        {
            _resetConfirmPending = true;
            UpdateResetButtons();
        };
        CampaignResetConfirmButton.OnPressed += _ =>
        {
            _resetConfirmPending = false;
            Send(LancerPlayerAction.CampaignReset);
            UpdateResetButtons();
        };
        CampaignResetCancelButton.OnPressed += _ =>
        {
            _resetConfirmPending = false;
            UpdateResetButtons();
        };

        ReturnToMenuButton.OnPressed += _ => Send(LancerPlayerAction.ReturnToMenu);

        LoadoutOption0Button.OnPressed += _ => Send(LancerPlayerAction.SelectLoadout, weaponIndex: 0);
        LoadoutOption1Button.OnPressed += _ => Send(LancerPlayerAction.SelectLoadout, weaponIndex: 1);
        LoadoutConfirmButton.OnPressed += _ => Send(LancerPlayerAction.ConfirmLoadout);

        SkillOption0Button.OnPressed += _ => Send(LancerPlayerAction.SelectUpgrade, weaponIndex: 0);
        SkillOption1Button.OnPressed += _ => Send(LancerPlayerAction.SelectUpgrade, weaponIndex: 1);
        SkillOption2Button.OnPressed += _ => Send(LancerPlayerAction.SelectUpgrade, weaponIndex: 2);
        SkillPickConfirmButton.OnPressed += _ => Send(LancerPlayerAction.ConfirmUpgrade);

        StabilizeHeatButton.OnPressed += _ =>
            Send(LancerPlayerAction.Stabilize, stabilizeOption: LancerStabilizeOption.ClearHeat);
        StabilizeRepairButton.OnPressed += _ =>
            Send(LancerPlayerAction.Stabilize, stabilizeOption: LancerStabilizeOption.Repair);
        StabilizeReloadButton.OnPressed += _ =>
            Send(LancerPlayerAction.Stabilize, stabilizeOption: LancerStabilizeOption.Reload);

        PickWeapon0Button.OnPressed += _ => Send(LancerPlayerAction.SelectWeapon, weaponIndex: 0);
        PickWeapon1Button.OnPressed += _ => Send(LancerPlayerAction.SelectWeapon, weaponIndex: 1);
        PickWeapon2Button.OnPressed += _ => Send(LancerPlayerAction.SelectWeapon, weaponIndex: 2);
    }

    private void Send(
        LancerPlayerAction action,
        LancerGridCoord? cell = null,
        int weaponIndex = -1,
        int targetUnitId = -1,
        LancerStabilizeOption stabilizeOption = LancerStabilizeOption.ClearHeat,
        string contextId = "")
    {
        OnAction?.Invoke(action, cell, weaponIndex, targetUnitId, stabilizeOption, contextId);
    }

    private void HandleCellClick(LancerGridCoord coord)
    {
        if (!_isPlayer || _snapshot == null)
            return;

        if (_snapshot.SelectionMode is LancerSelectionMode.Move or LancerSelectionMode.Boost or LancerSelectionMode.HexTarget)
        {
            OnAction?.Invoke(LancerPlayerAction.ConfirmCell, coord, -1, -1, LancerStabilizeOption.ClearHeat, "");
            return;
        }

        if (_snapshot.SelectionMode is LancerSelectionMode.Target or LancerSelectionMode.LockOnTarget)
        {
            var unit = _snapshot.Units.FirstOrDefault(u => u.Position.X == coord.X && u.Position.Y == coord.Y);
            if (unit != null)
                OnAction?.Invoke(LancerPlayerAction.ConfirmTarget, coord, _snapshot.SelectedWeaponIndex, unit.Id, LancerStabilizeOption.ClearHeat, "");
        }
    }

    private void UpdateScreens()
    {
        if (_snapshot == null)
            return;

        var phase = _snapshot.Phase;
        IntroPanel.Visible = phase == LancerGamePhase.Briefing;
        MissionSelectPanel.Visible = phase == LancerGamePhase.MissionSelect;
        LoadoutSelectPanel.Visible = phase == LancerGamePhase.LoadoutSelect;
        PreFightPanel.Visible = phase == LancerGamePhase.PreFight;
        Scene1Panel.Visible = false;
        IntermissionPanel.Visible = phase == LancerGamePhase.Intermission;
        SkillPickPanel.Visible = phase == LancerGamePhase.SkillPick;
        CombatPanel.Visible = phase == LancerGamePhase.Combat;
        EndPanel.Visible = phase is LancerGamePhase.MissionComplete or LancerGamePhase.CampaignComplete or LancerGamePhase.Victory or LancerGamePhase.Defeat;
        ReactionPanel.Visible = _snapshot.Prompt.Active;
        StabilizeBox.Visible = _snapshot.SelectionMode == LancerSelectionMode.Stabilize;
        WeaponPickBox.Visible = _snapshot.SelectionMode == LancerSelectionMode.WeaponPick;

        ActionsColumn.Visible = phase == LancerGamePhase.Combat;
        StatusColumn.Visible = phase == LancerGamePhase.Combat;

        if (!_snapshot.Prompt.Active)
            _reactionCounting = false;

        PhaseLabel.Text = Loc.GetString($"lancer-arcade-phase-{_snapshot.Phase.ToString().ToLower()}");

        var canReturnToMenu = phase is not (LancerGamePhase.Briefing or LancerGamePhase.MissionSelect);
        ReturnToMenuButton.Visible = canReturnToMenu;
        ReturnToMenuButton.Disabled = !_isPlayer;

        if (phase == LancerGamePhase.Briefing)
            IntroStartButton.Disabled = !_isPlayer;

        UpdateMissionSelect();
        UpdateLoadoutSelect();
        UpdatePreFight();
        UpdateIntermission();
        UpdateSkillPick();

        if (phase == LancerGamePhase.MissionComplete)
        {
            EndLabel.Text = Loc.GetString("lancer-arcade-mission-complete-title");
            if (!string.IsNullOrEmpty(_snapshot.MissionCompleteText))
                EndLabel.Text += $"\n{_snapshot.MissionCompleteText}";
            MissionCompleteContinueButton.Visible = true;
            RestartButton.Visible = false;
        }
        else if (phase == LancerGamePhase.CampaignComplete)
        {
            EndLabel.Text = Loc.GetString("lancer-arcade-campaign-complete-title");
            if (!string.IsNullOrEmpty(_snapshot.MissionCompleteText))
                EndLabel.Text += $"\n{_snapshot.MissionCompleteText}";
            MissionCompleteContinueButton.Visible = true;
            RestartButton.Visible = false;
        }
        else if (phase == LancerGamePhase.Victory)
        {
            EndLabel.Text = Loc.GetString("lancer-arcade-victory");
            MissionCompleteContinueButton.Visible = false;
            RestartButton.Visible = true;
        }
        else if (phase == LancerGamePhase.Defeat)
        {
            EndLabel.Text = Loc.GetString("lancer-arcade-defeat");
            MissionCompleteContinueButton.Visible = false;
            RestartButton.Visible = true;
        }

        UpdateDiceFallbackArea();

        if (phase is LancerGamePhase.Briefing or LancerGamePhase.MissionSelect)
            DiceOverlay.Clear();
    }

    private void UpdateDiceFallbackArea()
    {
        if (_snapshot == null)
        {
            DiceOverlay.SetRollContext(null, null, preferBoard: false);
            return;
        }

        var phase = _snapshot.Phase;

        Control? dedicated = phase switch
        {
            LancerGamePhase.Briefing => IntroDiceArea,
            LancerGamePhase.PreFight => PreFightDiceArea,
            LancerGamePhase.Scene1 => Scene1DiceArea,
            LancerGamePhase.Intermission => IntermissionDiceArea,
            LancerGamePhase.LoadoutSelect => LoadoutSelectDiceArea,
            LancerGamePhase.SkillPick => SkillPickDiceArea,
            LancerGamePhase.MissionComplete or LancerGamePhase.CampaignComplete or LancerGamePhase.Victory or LancerGamePhase.Defeat => EndDiceArea,
            _ => null
        };

        Control? phasePanel = phase switch
        {
            LancerGamePhase.Briefing => IntroPanel,
            LancerGamePhase.PreFight => PreFightPanel,
            LancerGamePhase.Scene1 => Scene1Panel,
            LancerGamePhase.Intermission => IntermissionPanel,
            LancerGamePhase.LoadoutSelect => LoadoutSelectPanel,
            LancerGamePhase.SkillPick => SkillPickPanel,
            LancerGamePhase.Combat => CombatPanel,
            LancerGamePhase.MissionComplete or LancerGamePhase.CampaignComplete or LancerGamePhase.Victory or LancerGamePhase.Defeat => EndPanel,
            _ => null
        };

        DiceOverlay.SetRollContext(dedicated, phasePanel, phase == LancerGamePhase.Combat);
    }

    private void UpdateMissionSelect()
    {
        if (_snapshot?.Phase != LancerGamePhase.MissionSelect || _snapshot.MissionSelect == null)
            return;

        var state = _snapshot.MissionSelect;
        MissionSelectSummaryLabel.Text = state.ChassisSummary;
        MissionSelectLoadoutLabel.Text = state.LoadoutSummary;
        UpdateResetButtons(state.CanResetCampaign);

        var missions = state.Missions;
        var existingIds = _missionButtons.Keys.ToHashSet();
        var currentIds = missions.Select(m => m.Id).ToHashSet();

        foreach (var id in existingIds.Except(currentIds).ToList())
        {
            if (_missionButtons.Remove(id, out var btn))
                MissionListBox.RemoveChild(btn);
        }

        // Rebuild in server order (unlock sequence) so buttons stay mission 1 → 2 → 3.
        foreach (var (_, btn) in _missionButtons)
            MissionListBox.RemoveChild(btn);

        foreach (var mission in missions)
        {
            if (!_missionButtons.TryGetValue(mission.Id, out var button))
            {
                button = new Button { HorizontalExpand = true };
                button.OnPressed += _ => Send(LancerPlayerAction.SelectMission, contextId: mission.Id);
                _missionButtons[mission.Id] = button;
            }

            MissionListBox.AddChild(button);

            var text = mission.Locked
                ? Loc.GetString("lancer-arcade-mission-locked", ("name", mission.Name))
                : mission.Cleared
                    ? Loc.GetString("lancer-arcade-mission-cleared", ("name", mission.Name))
                    : Loc.GetString("lancer-arcade-mission-available", ("name", mission.Name));

            button.Text = text;
            button.Disabled = mission.Locked || !_isPlayer;
            button.ToolTip = mission.Description;
        }
    }

    private void UpdateResetButtons(bool canReset = true)
    {
        if (_snapshot?.Phase != LancerGamePhase.MissionSelect)
            return;

        var showConfirm = _resetConfirmPending && canReset;
        CampaignResetButton.Visible = canReset && !showConfirm;
        CampaignResetConfirmButton.Visible = showConfirm;
        CampaignResetCancelButton.Visible = showConfirm;
        CampaignResetButton.Disabled = !_isPlayer;
        CampaignResetConfirmButton.Disabled = !_isPlayer;
        CampaignResetCancelButton.Disabled = !_isPlayer;
    }

    private void UpdateLoadoutSelect()
    {
        if (_snapshot?.Phase != LancerGamePhase.LoadoutSelect || _snapshot.LoadoutSelect == null)
            return;

        var state = _snapshot.LoadoutSelect;
        LoadoutSelectTitleLabel.Text = state.Title;
        LoadoutSelectMissionLabel.Text = state.MissionName;
        UpdateChoiceButton(LoadoutOption0Button, state.Options.ElementAtOrDefault(0));
        UpdateChoiceButton(LoadoutOption1Button, state.Options.ElementAtOrDefault(1));
        LoadoutConfirmButton.Disabled = !state.CanConfirm || !_isPlayer;
    }

    private void UpdateSkillPick()
    {
        if (_snapshot?.Phase != LancerGamePhase.SkillPick || _snapshot.SkillPick == null)
            return;

        var state = _snapshot.SkillPick;
        SkillPickTitleLabel.Text = state.Title;
        SkillPickStatsLabel.Text = Loc.GetString("lancer-arcade-skills-summary",
            ("hull", state.Hull),
            ("agility", state.Agility),
            ("engineering", state.Engineering));
        UpdateChoiceButton(SkillOption0Button, state.Options.ElementAtOrDefault(0));
        UpdateChoiceButton(SkillOption1Button, state.Options.ElementAtOrDefault(1));
        UpdateChoiceButton(SkillOption2Button, state.Options.ElementAtOrDefault(2));
        SkillPickConfirmButton.Disabled = !state.CanConfirm || !_isPlayer;
    }

    private void UpdateChoiceButton(Button button, LancerUpgradeOptionState? option)
    {
        if (option == null)
        {
            button.Visible = false;
            return;
        }

        button.Visible = true;
        button.Text = option.Selected ? $"[ {option.Label} ]" : option.Label;
        button.ToolTip = option.Description;
        button.Disabled = option.Selected || !option.Pickable || !_isPlayer;
    }

    private void UpdatePreFight()
    {
        if (_snapshot?.Phase != LancerGamePhase.PreFight || _snapshot.PreFight == null)
            return;

        var pre = _snapshot.PreFight;
        PreFightFightLabel.Text = Loc.GetString("lancer-arcade-prefight-fight",
            ("current", pre.FightNumber), ("total", pre.FightCount));
        PreFightMissionLabel.Text = pre.MissionName;
        PreFightDescLabel.SetMessage(pre.FightDescription);
        PreFightObjectiveLabel.SetMessage(pre.ObjectiveText);

        UpdateNarrativeButton(NarrativeCheck0Button, pre.NarrativeChecks.ElementAtOrDefault(0), 0);
        UpdateNarrativeButton(NarrativeCheck1Button, pre.NarrativeChecks.ElementAtOrDefault(1), 1);

        PreFightDeployButton.Disabled = !pre.CanDeploy || !_isPlayer;
    }

    private void UpdateNarrativeButton(Button button, LancerNarrativeCheckState? check, int index)
    {
        if (check == null)
        {
            button.Visible = false;
            return;
        }

        button.Visible = true;
        button.Text = check.Selected
            ? $"[ {check.Label} ]"
            : check.Label;
        button.ToolTip = check.Description;
        button.Disabled = check.Selected || !check.Pickable || !_isPlayer;
    }

    private void UpdateIntermission()
    {
        if (_snapshot?.Phase != LancerGamePhase.Intermission || _snapshot.Intermission == null)
            return;

        var state = _snapshot.Intermission;
        IntermissionFightLabel.Text = Loc.GetString("lancer-arcade-prefight-fight",
            ("current", state.FightNumber), ("total", state.FightCount));
        IntermissionRepairsLabel.Text = Loc.GetString("lancer-arcade-repairs",
            ("current", state.Repairs), ("max", state.RepairCap));
        IntermissionStructureLabel.Text = Loc.GetString("lancer-arcade-structure",
            ("current", state.Structure), ("max", state.MaxStructure));
        IntermissionHpLabel.Text = Loc.GetString("lancer-arcade-hp",
            ("current", state.Hp), ("max", state.MaxHp));
        IntermissionStructureButton.Disabled = !state.CanRepairStructure || !_isPlayer;
        IntermissionReactorButton.Disabled = !state.CanRepairReactor || !_isPlayer;
        IntermissionContinueButton.Disabled = !_isPlayer;
    }

    private void UpdateWeaponPick()
    {
        if (_snapshot == null || _snapshot.SelectionMode != LancerSelectionMode.WeaponPick)
            return;

        var mech = _snapshot.MechPanel;
        WeaponPickLabel.Text = _snapshot.AttackIntent switch
        {
            LancerAttackIntent.Barrage when _snapshot.BarragePickedWeapons.Length >= 1 =>
                Loc.GetString("lancer-arcade-mode-weapon-pick-barrage-second"),
            LancerAttackIntent.Barrage =>
                Loc.GetString("lancer-arcade-mode-weapon-pick-barrage"),
            _ => Loc.GetString("lancer-arcade-mode-weapon-pick-skirmish")
        };

        UpdatePickButton(PickWeapon0Button, mech.Weapons.ElementAtOrDefault(0), 0);
        UpdatePickButton(PickWeapon1Button, mech.Weapons.ElementAtOrDefault(1), 1);
        UpdatePickButton(PickWeapon2Button, mech.Weapons.ElementAtOrDefault(2), 2);
    }

    private void UpdatePickButton(Button button, LancerWeaponState? weapon, int index)
    {
        if (weapon == null || string.IsNullOrEmpty(weapon.Name))
        {
            button.Visible = false;
            return;
        }

        button.Visible = true;
        var picked = _snapshot!.BarragePickedWeapons.Contains(index);
        button.Text = picked
            ? Loc.GetString("lancer-arcade-weapon-picked", ("name", weapon.Name))
            : FormatWeaponPickLabel(weapon);

        var available = weapon.Pickable;
        button.Disabled = !_isPlayer || !available || picked;
    }

    private static string FormatWeaponPickLabel(LancerWeaponState weapon)
    {
        var text = FormatWeapon(weapon);
        if (!weapon.Pickable && weapon.BlockReason != LancerWeaponBlockReason.None)
        {
            text += $" — {Loc.GetString(GetBlockReasonLoc(weapon.BlockReason))}";
        }

        return text;
    }

    private static string GetBlockReasonLoc(LancerWeaponBlockReason reason) => reason switch
    {
        LancerWeaponBlockReason.Empty => "lancer-arcade-weapon-block-empty",
        LancerWeaponBlockReason.Moved => "lancer-arcade-weapon-block-moved",
        LancerWeaponBlockReason.Boosted => "lancer-arcade-weapon-block-boosted",
        LancerWeaponBlockReason.Engaged => "lancer-arcade-weapon-block-engaged",
        _ => string.Empty
    };

    private void UpdateSidebar()
    {
        if (_snapshot == null)
            return;

        var mech = _snapshot.MechPanel;
        HpLabel.Text = Loc.GetString("lancer-arcade-hp", ("current", mech.Hp), ("max", mech.MaxHp));
        HeatLabel.Text = Loc.GetString("lancer-arcade-heat", ("current", mech.Heat), ("max", mech.HeatCap));
        StructureLabel.Text = Loc.GetString("lancer-arcade-structure", ("current", mech.Structure), ("max", mech.MaxStructure));
        StressLabel.Text = Loc.GetString("lancer-arcade-stress", ("current", mech.Stress), ("max", mech.MaxStress));
        RepairsLabel.Text = Loc.GetString("lancer-arcade-repairs", ("current", mech.Repairs), ("max", mech.RepairCap));
        HexLabel.Text = Loc.GetString("lancer-arcade-hex", ("count", mech.HexCharges));
        CoreLabel.Text = mech.CoreActive
            ? Loc.GetString("lancer-arcade-core-active")
            : Loc.GetString("lancer-arcade-core-power", ("count", mech.CorePower));
        if (mech.Grit > 0)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-grit", ("grit", mech.Grit));
        if (mech.Impaired)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-impaired");
        if (mech.Exposed)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-exposed");
        if (mech.DangerZone)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-danger-zone");
        else if (mech.NuclearCavalier)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-nuclear-cavalier");
        if (mech.ExternalBatteries)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-external-batteries");
        if (mech.DeepWellActive)
            CoreLabel.Text += "  " + Loc.GetString("lancer-arcade-status-deep-well");

        var relay = _snapshot.Units.FirstOrDefault(u => u.Kind == LancerUnitKind.Relay);
        RelayLabel.Text = relay != null
            ? Loc.GetString("lancer-arcade-relay-hp", ("current", relay.Hp), ("max", relay.MaxHp))
            : string.Empty;

        var eco = _snapshot.ActionEconomy;
        var ecoParts = new List<string>
        {
            Loc.GetString("lancer-arcade-economy-move", ("current", eco.MoveRemaining), ("max", eco.MoveMax)),
            Loc.GetString("lancer-arcade-economy-quick-count",
                ("used", eco.QuickActionsUsed), ("max", eco.QuickActionsMax)),
            eco.FullUsed ? $"[{Loc.GetString("lancer-arcade-economy-full")}]" : Loc.GetString("lancer-arcade-economy-full")
        };
        if (eco.OverchargeUsed)
            ecoParts.Add($"[{Loc.GetString("lancer-arcade-economy-overcharge")}]");
        if (eco.FreeBoostAvailable)
            ecoParts.Add(Loc.GetString("lancer-arcade-economy-free-boost"));
        if (!eco.ReactionAvailable)
            ecoParts.Add($"[{Loc.GetString("lancer-arcade-economy-reaction-used")}]");
        EconomyLabel.Text = string.Join("  ", ecoParts);

        ModeLabel.Text = Loc.GetString(_snapshot.SelectionMode switch
        {
            LancerSelectionMode.Move => "lancer-arcade-mode-move",
            LancerSelectionMode.Boost => "lancer-arcade-mode-boost",
            LancerSelectionMode.WeaponPick => _snapshot.AttackIntent == LancerAttackIntent.Barrage
                ? "lancer-arcade-mode-weapon-pick-barrage"
                : "lancer-arcade-mode-weapon-pick-skirmish",
            LancerSelectionMode.Target => _snapshot.BarrageWeaponQueueCount > 0
                ? "lancer-arcade-mode-target-barrage-next"
                : "lancer-arcade-mode-target",
            LancerSelectionMode.LockOnTarget => "lancer-arcade-mode-lock-on",
            LancerSelectionMode.HexTarget => "lancer-arcade-mode-hex",
            LancerSelectionMode.Stabilize => "lancer-arcade-mode-stabilize",
            _ => "lancer-arcade-mode-none"
        });

        Weapon0Label.Text = mech.Weapons.Length > 0 ? FormatWeaponSidebar(mech.Weapons[0]) : string.Empty;
        Weapon1Label.Text = mech.Weapons.Length > 1 ? FormatWeaponSidebar(mech.Weapons[1]) : string.Empty;
        Weapon2Label.Text = mech.Weapons.Length > 2 ? FormatWeaponSidebar(mech.Weapons[2]) : string.Empty;
    }

    private static string FormatWeaponSidebar(LancerWeaponState weapon)
    {
        if (string.IsNullOrEmpty(weapon.Name))
            return string.Empty;

        var text = FormatWeapon(weapon);
        if (!weapon.Pickable && weapon.BlockReason != LancerWeaponBlockReason.None)
            text += $" — {Loc.GetString(GetBlockReasonLoc(weapon.BlockReason))}";

        return text;
    }

    private static string FormatWeapon(LancerWeaponState weapon)
    {
        var status = weapon.Loaded
            ? Loc.GetString("lancer-arcade-weapon-ready")
            : Loc.GetString("lancer-arcade-weapon-empty");
        return $"{weapon.Name} ({status}) R{weapon.Range}";
    }

    private void UpdateInteractivity()
    {
        UpdateTutorialHint();

        if (_snapshot != null)
        {
            var canReturnToMenu = _snapshot.Phase is not (LancerGamePhase.Briefing or LancerGamePhase.MissionSelect);
            ReturnToMenuButton.Visible = canReturnToMenu;
            ReturnToMenuButton.Disabled = !_isPlayer;
        }

        var tutorial = _snapshot?.Tutorial;
        var tutorialActive = tutorial is { Active: true };
        var tutorialAllows = tutorialActive
            ? tutorial!.AllowedActions.ToHashSet()
            : null;

        var combatReady = _isPlayer
                          && _snapshot is { Phase: LancerGamePhase.Combat, PlayerTurn: true, Prompt.Active: false };
        var endTurnOk = combatReady
                        && (!tutorialActive || tutorial!.CanEndTurn);
        EndTurnButton.Disabled = !endTurnOk;

        var eco = _snapshot?.ActionEconomy;
        var mech = _snapshot?.MechPanel;
        var mode = _snapshot?.SelectionMode ?? LancerSelectionMode.None;

        foreach (var child in ActionGrid.Children)
        {
            if (child is not Button button)
                continue;

            if (!combatReady)
            {
                button.Disabled = true;
                continue;
            }

            if (!_actionButtonMap.TryGetValue(button, out var mappedAction))
            {
                button.Disabled = true;
                continue;
            }

            if (mappedAction == LancerPlayerAction.Cancel)
            {
                button.Disabled = mode == LancerSelectionMode.None;
                continue;
            }

            if (tutorialAllows != null && !tutorialAllows.Contains(mappedAction))
            {
                button.Disabled = true;
                continue;
            }

            if (eco == null || mech == null)
            {
                button.Disabled = true;
                continue;
            }

            button.Disabled = mappedAction switch
            {
                LancerPlayerAction.SelectMove => eco.MoveRemaining <= 0,
                LancerPlayerAction.SelectBoost =>
                    eco.BoostUsed && !eco.FreeBoostAvailable || !eco.CanSpendQuick && !eco.FreeBoostAvailable,
                LancerPlayerAction.Skirmish => eco.SkirmishUsed || !eco.CanSpendQuick,
                LancerPlayerAction.Barrage => !eco.CanSpendFull,
                LancerPlayerAction.LockOn => eco.LockOnUsed || !eco.CanSpendQuick,
                LancerPlayerAction.UseSystem =>
                    mech.HexCharges <= 0 || eco.HexUsed || !eco.CanSpendQuick,
                LancerPlayerAction.Stabilize => !eco.CanSpendFull,
                LancerPlayerAction.Disengage => !eco.CanSpendFull,
                LancerPlayerAction.Overcharge => eco.OverchargeUsed,
                LancerPlayerAction.ActivateCore => mech.CoreActive || mech.CorePower <= 0,
                _ => false
            };
        }

        var stabilizeEnabled = combatReady && mode == LancerSelectionMode.Stabilize;
        var tutorialStabilize = tutorialActive && tutorialAllows != null
                                && tutorialAllows.Contains(LancerPlayerAction.Stabilize);
        StabilizeHeatButton.Disabled = !stabilizeEnabled || (tutorialActive && !tutorialStabilize);
        StabilizeRepairButton.Disabled = !stabilizeEnabled || tutorialActive || (mech?.Repairs ?? 0) <= 0;
        // Reload is for LOADING weapons (Catalytic Hammer, AMR, etc.).
        var needsReload = mech?.Weapons.Any(w =>
            !string.IsNullOrEmpty(w.Name) && !w.Loaded) == true;
        StabilizeReloadButton.Disabled = !stabilizeEnabled || tutorialActive || !needsReload;

        if (_snapshot?.Prompt.Active == true)
        {
            var reactionOk = _isPlayer;
            if (tutorialActive && tutorialAllows != null)
            {
                ReactionAcceptButton.Disabled = !reactionOk || !tutorialAllows.Contains(LancerPlayerAction.ReactionAccept);
                ReactionDeclineButton.Disabled = !reactionOk || !tutorialAllows.Contains(LancerPlayerAction.ReactionDecline);
            }
            else
            {
                ReactionAcceptButton.Disabled = !reactionOk;
                ReactionDeclineButton.Disabled = !reactionOk;
            }
        }

        if (_snapshot?.SelectionMode == LancerSelectionMode.WeaponPick)
            UpdateWeaponPick();
    }

    private void UpdateTutorialHint()
    {
        var tutorial = _snapshot?.Tutorial;
        if (tutorial is { Active: true })
        {
            TutorialHintLabel.Visible = true;
            TutorialHintLabel.SetMarkup(
                $"[color=#E8C96A]{tutorial.Title}[/color]\n{tutorial.Hint}");
        }
        else
        {
            TutorialHintLabel.Visible = false;
            TutorialHintLabel.SetMarkup(string.Empty);
        }
    }
}
