- type: entity
  id: ClothingBackpackSyndicateGMNDamageControl
  parent: ClothingBackpackSyndicate
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: SheetSteel
        - id: SheetPlasteel
        - id: SheetRPGlass

- type: entity
  id: ClothingBackpackSyndicateGMNGunner
  parent: ClothingBackpackSyndicate
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: SheetSteel10
