using Robust.Client.AutoGenerated;
using Content.Client.Gameplay;
using Content.Client.ContextMenu.UI;
using Content.Client.Verbs;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Content.Client.Actions;
using Content.Client.UserInterface.Systems.Actions.Controls;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Inventory.Controls;
using Content.Client.UserInterface.Systems.Hands.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Client.Viewport;
using Content.Client.UserInterface.Systems.Viewport;
using Content.Client._Starlight.UserInterface;
using Content.Shared.ActionBlocker;
using Robust.Client.State;
using Content.Client.Examine;
using Content.Shared.Interaction;
using Content.Client._Starlight.RCD;
using Content.Shared.Atmos.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Movement.Pulling.Components;
using Content.Shared.UserInterface;
using Content.Shared._Starlight.Computers.RemoteControl;
using Robust.Client.Timing;
using Robust.Shared.GameObjects;
using Robust.Shared.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Input.Binding;
using Content.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Client.Player;
using Robust.Client.Placement;
using Robust.Client.UserInterface.Controls;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Content.Client._Starlight.Computers.RemoteControl;

[GenerateTypedNameReferences]
public sealed partial class RemoteControlConsoleWindow : PopOutFancyWindow
{
    [Dependency] private IEyeManager _eyeManager = default!;
    [Dependency] private IStateManager _stateManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly ISawmill _sawmill = IoCManager.Resolve<ILogManager>().GetSawmill("remote-control");
    private readonly EntityMenuUIController _entityMenu;
    private readonly RemoteControlInterface _remoteControl;
    private readonly SharedMapSystem _mapManager;
    private readonly ExamineSystem _examineSystem;
    private readonly ActionsSystem _actionsSystem;
    private readonly VerbSystem _verbSystem;
    private readonly ActionBlockerSystem _actionBlocker;
    private readonly IPlayerManager _playerManager;
    [Dependency] private IInputManager _inputManager = default!;
    [Dependency] private IPlacementManager _placementManager = default!;
    private readonly ItemStatusPanel _activeDeviceStatusPanel;
    private readonly TextureButton _inventoryToggleButton;
    private readonly Robust.Shared.Graphics.Eye _remoteEye = new();
    private IEye? _sourceEye;
    private EntityUid? _remoteEntity;
    private bool _commandBindsRegistered;
    private bool _inventoryOpen;
    private SimpleRadialMenu? _remoteRadialMenu;
    private Vector2 _remoteMouseViewportPosition;
    public event Action? ToggleControl;
    public event Action<NetCoordinates, EntityUid?, bool, bool, RemoteControlInteractionAction, AtmosPipeLayer?>? RemoteInteractionPressed;
    public event Action<EntityUid>? RemoteActionPressed;
    public event Action<string, RemoteControlHandAction>? RemoteHandPressed;
    public event Action<string, RemoteControlInventoryAction>? RemoteInventoryPressed;

    protected override Control Control => RootContainer;

    public IEye RemoteEye => _remoteEye;
    public IViewportControl RemoteViewport => RemoteView;

    public override void Close()
    {
        _remoteRadialMenu?.Close();
        UnregisterCommandBinds();
        base.Close();
    }

    public RemoteControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _activeDeviceStatusPanel = FindControl<ItemStatusPanel>("ActiveDeviceStatusPanel");
        _activeDeviceStatusPanel.SetSide(HandLocation.Right);
        _inventoryToggleButton = FindControl<TextureButton>("InventoryToggleButton");
        _inventoryToggleButton.TextureNormal = Theme.ResolveTextureOrNull("Slots/back")?.Texture;
        _inventoryToggleButton.OnPressed += _ => ToggleInventory();
        _actionsSystem = _entityManager.System<ActionsSystem>();
        _actionBlocker = _entityManager.System<ActionBlockerSystem>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        InitializeRemoteStatus();
        _mapManager = _entityManager.System<SharedMapSystem>();
        _remoteControl = _entityManager.System<RemoteControlInterface>();
        _entityMenu = IoCManager.Resolve<IUserInterfaceManager>().GetUIController<EntityMenuUIController>();
        _examineSystem = _entityManager.System<ExamineSystem>();
        _verbSystem = _entityManager.System<VerbSystem>();
        OnPopout += RegisterCommandBinds;
    }

    protected override void Opened()
    {
        base.Opened();

        RegisterCommandBinds();
    }

    private bool HandleRemoteExamine(in PointerInputCmdHandler.PointerInputCmdArgs args)
    {
        if (!RemoteView.GlobalRect.Contains(args.ScreenCoordinates.Position))
            return false;

        var mapPosition = RemoteView.PixelToMap(args.ScreenCoordinates.Position);
        var target = GetRemoteTarget(mapPosition);

        if (target is not { } targetEntity)
            return false;

        if (_remoteControl.ControlledEntity is not { } remoteEntity)
            return false;

        _examineSystem.DoExamine(targetEntity, userOverride: remoteEntity, uiRoot: RemoteView.Root);
        return true;
    }

    private bool HandleRemoteUse(in PointerInputCmdHandler.PointerInputCmdArgs args)
        => HandleRemoteInteraction(args, false);

    private bool HandleRemoteActivateInWorld(in PointerInputCmdHandler.PointerInputCmdArgs args)
        => HandleRemoteInteraction(args, false, activateInWorld: true);

    private bool HandleRemoteAltUse(in PointerInputCmdHandler.PointerInputCmdArgs args)
        => HandleRemoteInteraction(args, true);

    private bool HandleRemotePull(in PointerInputCmdHandler.PointerInputCmdArgs args)
        => HandleRemoteInteraction(args, false, action: RemoteControlInteractionAction.TryPull);

    private bool HandleRemoteMovePulled(in PointerInputCmdHandler.PointerInputCmdArgs args)
    {
        if (!_inputManager.IsKeyDown(Keyboard.Key.Control)
            || _remoteControl.ControlledEntity is not { } remoteEntity
            || !_entityManager.TryGetComponent<PullerComponent>(remoteEntity, out var puller)
            || puller.Pulling is null)
            return false;

        return HandleRemoteInteraction(args, false, action: RemoteControlInteractionAction.MovePulledObject);
    }

    private bool HandleRemoteContextMenu(in PointerInputCmdHandler.PointerInputCmdArgs args)
    {
        if (args.State != BoundKeyState.Down || !RemoteView.GlobalRect.Contains(args.ScreenCoordinates.Position))
            return false;

        if (_entityManager.System<RemoteConstructionPlacementSystem>().IsActive)
        {
            _entityManager.System<RemoteConstructionPlacementSystem>().Clear();
            return true;
        }

        if (_inputManager.IsKeyDown(Keyboard.Key.Control) && HandleRemoteMovePulled(args))
            return true;

        if (_remoteControl.ControlledEntity is not { } remoteEntity)
            return false;

        var mapPosition = RemoteView.PixelToMap(args.ScreenCoordinates.Position);
        if (!_verbSystem.TryGetEntityMenuEntities(mapPosition, remoteEntity, _remoteEye.DrawFov, out var entities))
            return false;

        _entityMenu.OpenRootMenu(entities, RemoteView.Root);
        return true;
    }

    private bool HandleRemoteInteraction(in PointerInputCmdHandler.PointerInputCmdArgs args, bool altInteract,
        RemoteControlInteractionAction action = RemoteControlInteractionAction.Interact,
        bool activateInWorld = false)
    {
        if (!IoCManager.Resolve<IGameTiming>().IsFirstTimePredicted
            || args.State != BoundKeyState.Down
            || !RemoteView.GlobalRect.Contains(args.ScreenCoordinates.Position))
            return false;

        var mapPosition = RemoteView.PixelToMap(args.ScreenCoordinates.Position);
        var mapEntity = _mapManager.GetMapOrInvalid(mapPosition.MapId);
        if (!mapEntity.IsValid())
            return false;

        var target = GetRemoteTarget(mapPosition);
        var pipeLayer = _placementLayer;

        var coordinates = _mapManager.MapExists(mapPosition.MapId)
            && _mapManager.TryFindGridAt(mapPosition, out var grid, out _)
            ? _mapManager.MapToGrid(grid, mapPosition)
            : new EntityCoordinates((EntityUid) mapEntity, mapPosition.Position);
        RemoteInteractionPressed?.Invoke(
            _entityManager.GetNetCoordinates(coordinates),
            target,
            altInteract,
            activateInWorld,
            action,
            pipeLayer);
        return true;
    }

    private AtmosPipeLayer? _placementLayer
        => _placementManager.CurrentMode is AlignRPDAtmosPipeLayers mode
            ? mode.CurrentLayer
            : null;

    private EntityUid? GetRemoteTarget(MapCoordinates coordinates)
        => _stateManager.CurrentState is GameplayStateBase screen
            ? screen.GetClickedEntity(coordinates, _remoteEye)
            : null;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateRemoteEye();
    }

    public void UpdateRemoteEye()
    {
        if (_sourceEye == null)
            return;

        _remoteEye.Position = _sourceEye.Position;
        _remoteEye.Offset = _sourceEye.Offset;
        _remoteEye.Zoom = _sourceEye.Zoom;
        _remoteEye.DrawFov = _sourceEye.DrawFov;
        _remoteEye.DrawLight = _sourceEye.DrawLight;
        _remoteEye.Rotation = _sourceEye.Rotation;
    }

    public void InitializeViewport()
    {
        RemoteView.ViewportSize = ViewportUIController.ViewportSize;
        RemoteView.StretchMode = ScalingViewportStretchMode.Bilinear;
        RemoteView.RenderScaleMode = ScalingViewportRenderScaleMode.Fixed;
        RemoteView.FixedRenderScale = 1;
        RemoteView.OnResized += OnViewportResized;
        RemoteView.OnViewportMouseMove += OnRemoteViewportMouseMove;
        OnViewportResized();
    }

    private void OnRemoteViewportMouseMove(Vector2 position)
    {
        if (_remoteControl.ControlledEntity is not { })
            return;

        _remoteMouseViewportPosition = position;
        _remoteControl.SetRemoteMousePosition(RemoteView.PixelToMap(position));
    }

    public bool OpenRemoteRadialMenu(SimpleRadialMenu menu)
    {
        if (_remoteControl.ControlledEntity is null || !RemoteView.Visible)
            return false;

        _remoteRadialMenu?.Close();
        _remoteRadialMenu = menu;
        menu.OnClose += OnRemoteRadialMenuClosed;
        menu.OpenEmbedded(RootContainer, RemoteView.Position + RemoteView.Size / 2);
        return true;
    }

    private void OnRemoteRadialMenuClosed()
    {
        if (_remoteRadialMenu is { } menu)
            menu.OnClose -= OnRemoteRadialMenuClosed;

        _remoteRadialMenu = null;
    }

    public void SetConnected(bool connected)
    {
        StatusLabel.Visible = !connected;
        UpdateRemoteViewVisibility(connected);
        ControlButton.Visible = connected;
        ActionButtons.Visible = connected;
        HandButtons.Visible = connected;
        _inventoryToggleButton.Visible = connected;
        InventoryButtons.Visible = connected && _inventoryOpen;
        RemoteAlerts.Visible = connected;

        if (!connected)
        {
            _inventoryOpen = false;
            ClearRemoteStatus();
        }
    }

    public void SetControlState(bool controlling, bool occupied)
    {
        ControlButton.Pressed = controlling;
        ControlButton.Disabled = occupied && !controlling;
        UpdateRemoteViewVisibility(_remoteEntity != null);
        _inventoryToggleButton.MouseFilter = controlling ? MouseFilterMode.Pass : MouseFilterMode.Ignore;
        InventoryButtons.Visible = controlling && _inventoryOpen;
        ActionButtons.MouseFilter = controlling ? MouseFilterMode.Pass : MouseFilterMode.Ignore;
        HandButtons.MouseFilter = controlling ? MouseFilterMode.Pass : MouseFilterMode.Ignore;
        InventoryButtons.MouseFilter = controlling ? MouseFilterMode.Pass : MouseFilterMode.Ignore;
    }

    private void UpdateRemoteViewVisibility(bool connected)
        => RemoteView.Visible = connected
            && _playerManager.LocalEntity is { } player
            && _actionBlocker.CanConsciouslyPerformAction(player);

    public void SetRemoteEye(IEye? eye)
    {
        _sourceEye = eye;
        RemoteView.Eye = eye == null ? null : _remoteEye;
    }

    public void SetRemoteEntity(EntityUid? entity)
    {
        if (_remoteEntity == entity)
            return;

        _remoteEntity = entity;
        if (entity is { } remoteEntity)
            UpdateRemoteStatus(remoteEntity);
        else
            ClearRemoteStatus();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => RemoteView.GlobalRect.Contains(relativeMousePos + GlobalPosition)
            ? DragMode.None
            : base.GetDragModeFor(relativeMousePos); // Starlight

    public void SetActions(IEnumerable<EntityUid> actions, EntityUid? selectedAction = null)
    {
        ActionButtons.RemoveAllChildren();

        foreach (var action in actions)
        {
            var button = new ActionButton(IoCManager.Resolve<IEntityManager>())
            {
                MinSize = new Vector2(64, 64),
            };
            button.UpdateData(action, _actionsSystem);
            button.SetRemoteSelected(button.Action?.Owner == selectedAction);
            button.ActionUnpressed += OnRemoteActionUnpressed;
            ActionButtons.AddChild(button);
        }
    }

    private void ToggleInventory()
    {
        if (_remoteEntity == null)
            return;

        _inventoryOpen = !_inventoryOpen;
        InventoryButtons.Visible = _inventoryOpen;
    }

    private void OnRemoteActionUnpressed(GUIBoundKeyEventArgs args, ActionButton button)
    {
        if (args.Function == EngineKeyFunctions.UIClick && button.Action is { } action)
            RemoteActionPressed?.Invoke(action.Owner);
    }

    public void SetHands(IEnumerable<RemoteControlHandState> hands)
    {
        HandButtons.RemoveAllChildren();
        var activeHand = hands.FirstOrDefault(hand => hand.Active);
        var activeEntity = activeHand?.HeldItem is { } activeItem
            && _entityManager.TryGetEntity(activeItem, out var resolvedEntity)
            ? resolvedEntity
            : (EntityUid?) null;
        _activeDeviceStatusPanel.Update(activeEntity, hand: null);

        foreach (var hand in hands)
        {
            var handButton = new HandButton(hand.Name, hand.Location);
            EntityUid? heldEntity = null;
            if (hand.HeldItem is { } held)
                _entityManager.TryGetEntity(held, out heldEntity);

            if (heldEntity is { } entity)
                handButton.SetEntity(entity);
            else if (hand.EmptyRepresentative is { } representative)
                handButton.SetPrototype(representative, true);
            else
                handButton.SetEntity(null);

            handButton.Highlight = hand.Active;
            handButton.Pressed += (args, _) => OnRemoteHandButtonPressed(args, hand);
            HandButtons.AddChild(handButton);
        }
    }

    private void OnRemoteHandButtonPressed(GUIBoundKeyEventArgs args, RemoteControlHandState hand)
    {
        RemoteControlHandAction? action = null;
        if (args.Function.FunctionName == EngineKeyFunctions.UIClick.FunctionName)
            action = GetHandClickAction(hand);
        else if (args.Function.FunctionName == ContentKeyFunctions.MoveStoredItem.FunctionName)
            action = GetHandClickAction(hand);
        else if (args.Function.FunctionName == ContentKeyFunctions.ActivateItemInWorld.FunctionName)
            action = RemoteControlHandAction.Activate;
        else if (args.Function.FunctionName == ContentKeyFunctions.AltActivateItemInWorld.FunctionName)
            action = RemoteControlHandAction.AltUse;
        else if (args.Function.FunctionName == ContentKeyFunctions.ExamineEntity.FunctionName)
        {
            if (hand.HeldItem is { } held
                && _entityManager.TryGetEntity(held, out var heldEntity)
                && heldEntity is { } heldUid
                && _remoteEntity is { } remoteEntity)
            {
                _examineSystem.DoExamine(heldUid, userOverride: remoteEntity, uiRoot: RemoteView.Root);
            }

            args.Handle();
            return;
        }

        if (action is { } handAction)
        {
            RemoteHandPressed?.Invoke(hand.Name, handAction);
            args.Handle();
        }
    }

    private static RemoteControlHandAction GetHandClickAction(RemoteControlHandState hand)
    {
        if (hand.Active)
            return hand.HeldItem != null
                ? RemoteControlHandAction.Use
                : RemoteControlHandAction.SetActive;

        return RemoteControlHandAction.SetActive;
    }

    public void SetInventory(IEnumerable<RemoteControlInventorySlotState> inventory)
    {
        InventoryButtons.RemoveAllChildren();
        var index = 0;
        foreach (var slot in inventory)
        {
            EntityUid? slotEntity = null;
            if (slot.Item is { } item)
                _entityManager.TryGetEntity(item, out slotEntity);

            var slotButton = new SlotButton
            {
                ButtonTexturePath = slot.TextureName,
                FullButtonTexturePath = slot.FullTextureName,
                StorageTexturePath = "Slots/back",
                SlotName = slot.Name,
            };
            slotButton.SetEntity(slotEntity);
            slotButton.Pressed += (_, _) => RemoteInventoryPressed?.Invoke(slot.Name, RemoteControlInventoryAction.UseSlot);
            InventoryButtons.AddChild(slotButton);
            LayoutContainer.SetPosition(slotButton, new Vector2(index * (SlotControl.DefaultButtonSize + 5), 0));
            index++;

            if (slot.HasStorage)
            {
                slotButton.StorageButton.Visible = true;
                slotButton.StoragePressed += (_, _) => RemoteInventoryPressed?.Invoke(slot.Name, RemoteControlInventoryAction.OpenStorage);
            }
        }
    }

    private void OnViewportResized()
    {
        var width = Math.Max(RemoteView.PixelWidth, (int) Math.Floor(RemoteView.MinWidth));
        var height = Math.Max(RemoteView.PixelHeight, (int) Math.Floor(RemoteView.MinHeight));
        var viewSize = (Vector2) RemoteView.ViewportSize;
        var scale = Math.Min(width / viewSize.X, height / viewSize.Y);
        RemoteView.FixedStretchSize = (Vector2i) (viewSize * scale);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            UnregisterCommandBinds();

        base.Dispose(disposing);
    }
    private void RegisterCommandBinds()
    {
        if (_commandBindsRegistered)
            return;

        ControlButton.OnPressed += OnControlButtonPressed;

        CommandBinds.Builder
            .Bind(EngineKeyFunctions.Use,
                new PointerInputCmdHandler(HandleRemoteUse, outsidePrediction: true))
            .BindBefore(ContentKeyFunctions.ActivateItemInWorld,
                new PointerInputCmdHandler(HandleRemoteActivateInWorld, outsidePrediction: true),
                typeof(SharedInteractionSystem))
            .BindBefore(ContentKeyFunctions.AltActivateItemInWorld,
                new PointerInputCmdHandler(HandleRemoteAltUse, outsidePrediction: true),
                typeof(SharedInteractionSystem))
            .BindBefore(ContentKeyFunctions.TryPullObject,
                new PointerInputCmdHandler(HandleRemotePull, outsidePrediction: true),
                typeof(SharedInteractionSystem))
            .Bind(ContentKeyFunctions.MovePulledObject,
                new PointerInputCmdHandler(HandleRemoteMovePulled, outsidePrediction: true))
            .BindBefore(EngineKeyFunctions.UseSecondary,
                new PointerInputCmdHandler(HandleRemoteContextMenu, outsidePrediction: true),
                typeof(EntityMenuUIController))
            .BindBefore(ContentKeyFunctions.ExamineEntity,
                new PointerInputCmdHandler(HandleRemoteExamine, outsidePrediction: true),
                typeof(ExamineSystem))
            .Register<RemoteControlConsoleWindow>();
        _commandBindsRegistered = true;
    }
    private void UnregisterCommandBinds()
    {
        if (!_commandBindsRegistered)
            return;

        ControlButton.OnPressed -= OnControlButtonPressed;
        CommandBinds.Unregister<RemoteControlConsoleWindow>();
        _commandBindsRegistered = false;
    }

    private void OnControlButtonPressed(BaseButton.ButtonEventArgs _)
        => ToggleControl?.Invoke();
}
