using Content.Client.Medical.CrewMonitoring;
using Content.Client.Pinpointer.UI;
using Content.Shared._PV.Terraforming;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client._PV.Terraforming.UI;

[GenerateTypedNameReferences]
public sealed partial class TerraformerConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private Texture? _blipTexture;

    public event Action? OnRefreshPressed;

    public TerraformerConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        RefreshButton.OnPressed += _ => OnRefreshPressed?.Invoke();

        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(
            new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
    }

    public void UpdateState(TerraformerConsoleBoundInterfaceState state)
    {
        SummaryLabel.Text =
            $"TOTAL CONVERTED TILES: {state.TotalTilesTerraformed}    |    " +
            $"TERRAFORMERS DETECTED: {state.TerraformerCount}";

        AtmosphereLabel.Text =
            $"Sampled tiles: {state.Atmosphere.TileCount}\n\n" +
            $"Average pressure: {state.Atmosphere.AveragePressure:0.0} kPa\n" +
            $"Average temperature: {state.Atmosphere.AverageTemperature:0.0} K\n\n" +
            $"Gas composition:\n" +
            $"  Oxygen: {state.Atmosphere.OxygenPercent:0.0}%\n" +
            $"  Nitrogen: {state.Atmosphere.NitrogenPercent:0.0}%\n" +
            $"  CO2: {state.Atmosphere.CarbonDioxidePercent:0.0}%\n" +
            $"  Plasma: {state.Atmosphere.PlasmaPercent:0.0}%\n" +
            $"  Tritium: {state.Atmosphere.TritiumPercent:0.0}%\n" +
            $"  Nitrous oxide: {state.Atmosphere.NitrousOxidePercent:0.0}%\n" +
            $"  Other: {state.Atmosphere.OtherPercent:0.0}%";

        UpdateNavMap(state);
        UpdateTerraformerList(state);
    }

    private void UpdateNavMap(TerraformerConsoleBoundInterfaceState state)
    {
        NavMap.TrackedEntities.Clear();
        NavMap.TrackedCoordinates.Clear();
        NavMap.LocalizedNames.Clear();

        if (state.GridEntity == null)
        {
            NavMap.Visible = false;
            return;
        }

        NavMap.Visible = true;
        NavMap.MapUid = _entManager.GetEntity(state.GridEntity.Value);

        if (_blipTexture == null)
            return;

        foreach (var entry in state.Terraformers)
        {
            var coordinates = _entManager.GetCoordinates(entry.Coordinates);
            var color = StatusColor(entry.Status);

            NavMap.LocalizedNames[entry.Entity] =
                $"{entry.Name} ({StatusText(entry.Status)})";

            NavMap.TrackedEntities[entry.Entity] = new NavMapBlip(
                coordinates,
                _blipTexture,
                color,
                true,
                false);
        }

        NavMap.ForceNavMapUpdate();
    }

    private void UpdateTerraformerList(TerraformerConsoleBoundInterfaceState state)
    {
        TerraformerList.RemoveAllChildren();

        if (state.Terraformers.Count == 0)
        {
            TerraformerList.AddChild(new Label
            {
                Text = "No terraformers detected on this grid.",
            });

            return;
        }

        foreach (var entry in state.Terraformers)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
            };

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 3,
                Margin = new Thickness(6),
            };

            panel.AddChild(box);

            box.AddChild(new Label
            {
                Text = $"{entry.Name} — {StatusText(entry.Status)}",
                StyleClasses = { "LabelHeading" },
            });

            box.AddChild(new Label
            {
                Text =
                    $"Fuel: {entry.Fuel:0}/{entry.MaxFuel:0}\n" +
                    $"Tiles converted: {entry.TilesTerraformed}\n" +
                    $"Terraform radius: {entry.Radius:0.#}\n" +
                    $"Barrier radius: {entry.BarrierRadius:0.#}\n" +
                    $"Grid position: {entry.GridX}, {entry.GridY}",
            });

            TerraformerList.AddChild(panel);
        }
    }

    private Color StatusColor(TerraformerConsoleStatus status)
    {
        return status switch
        {
            TerraformerConsoleStatus.Inactive => Color.Red,
            TerraformerConsoleStatus.Empty => Color.Yellow,
            TerraformerConsoleStatus.Working => Color.LimeGreen,
            _ => Color.Gray,
        };
    }

    private string StatusText(TerraformerConsoleStatus status)
    {
        return status switch
        {
            TerraformerConsoleStatus.Inactive => "Inactive",
            TerraformerConsoleStatus.Empty => "Empty",
            TerraformerConsoleStatus.Working => "Working",
            _ => "Unknown",
        };
    }
}