using System.Threading.Tasks;
using Content.Client.Sprite;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared._Sol.Language;
using Content.Shared._Starlight.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;

namespace Content.Client._Starlight.Lobby.UI.ProfileEditorControls;

/// <summary>
/// This class provides a control that gives you a sprite view of an entity with an applied
/// <see cref="HumanoidCharacterProfile"/>, and some buttons to rotate the view. It's a relatively lightweight wrapper
/// around <see cref="ProfilePreviewSpriteView"/> specifically for the right side panel of the
/// <see cref="HumanoidProfileEditor"/> window.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ProfilePreview : BoxContainer
{
    /// <summary>
    ///     Index of the traits tab in <see cref="HumanoidProfileEditor"/>'s TabContainer.
    /// </summary>
    public const int TraitsTabIndex = 3;

    private static readonly Color TableHeaderBg = Color.FromHex("#464966");
    private static readonly Color TableRowBg = Color.FromHex("#2E2F38");
    private static readonly Color TableAltRowBg = Color.FromHex("#25262E");
    private static readonly Color TableText = Color.FromHex("#EEEEEE");
    private static readonly Color TableMutedText = Color.FromHex("#A8ADB5");

    private IEntityManager _entityManager = default!;
    private IPrototypeManager _prototypeManager = default!;
    private IComponentFactory _componentFactory = default!;

    private HumanoidProfileEditor? _editor;
    private bool _showKnownLanguages;

    private Direction _previewRotation = Direction.North;

    public ProfilePreview()
    {
        RobustXamlLoader.Load(this);
        SpriteRotateLeft.OnPressed += OnRotateLeft;
        SpriteRotateRight.OnPressed += OnRotateRight;
    }

    /// <summary>
    /// This MUST be called before loading a profile to initialize the managers.
    /// Instead of resolving these dependencies, we pass the references through.
    /// </summary>
    /// <param name="profileEditor">Passed in dependency</param>
    /// <param name="entMan">Passed in dependency</param>
    /// <param name="prefMan">Passed in dependency</param>
    /// <param name="protoMan">Passed in dependency</param>
    /// <param name="playerMan">Passed in dependency</param>
    public void Initialize(HumanoidProfileEditor profileEditor, IEntityManager entMan, IClientPreferencesManager prefMan, IPrototypeManager protoMan, ISharedPlayerManager playerMan)
    {
        _editor = profileEditor;
        _entityManager = entMan;
        _prototypeManager = protoMan;
        _componentFactory = IoCManager.Resolve<IComponentFactory>();
        SpriteView.Initialize(prefMan, protoMan, playerMan);
        UpdateKnownLanguages();
    }

    /// <summary>
    ///     Shows or hides the known-languages panel (intended for the traits tab).
    /// </summary>
    public void SetKnownLanguagesVisible(bool visible)
    {
        _showKnownLanguages = visible;
        KnownLanguagesPanel.Visible = visible;
        if (visible)
            UpdateKnownLanguages();
    }

    /// <summary>
    ///     Rebuilds the known-languages table from the current profile's species and traits.
    /// </summary>
    public void UpdateKnownLanguages()
    {
        KnownLanguagesList.RemoveAllChildren();

        if (!_showKnownLanguages || _editor?.Profile is not { } profile)
            return;

        if (_prototypeManager is null || _componentFactory is null)
            return;

        var knowledge = CharacterProfileLanguageHelper.GetLanguages(profile, _prototypeManager, _componentFactory);
        var spoken = new HashSet<ProtoId<LanguagePrototype>>(knowledge.Speaks);

        AddLanguageTableHeader();

        var rowIndex = 0;
        foreach (var language in knowledge.Speaks)
        {
            if (!_prototypeManager.TryIndex(language, out LanguagePrototype? proto))
                continue;

            AddLanguageTableRow(proto.Name, Loc.GetString("humanoid-profile-editor-known-languages-speak"), rowIndex++, false);
        }

        foreach (var language in knowledge.Understands)
        {
            if (spoken.Contains(language))
                continue;

            if (!_prototypeManager.TryIndex(language, out LanguagePrototype? proto))
                continue;

            AddLanguageTableRow(proto.Name, Loc.GetString("humanoid-profile-editor-known-languages-understand"), rowIndex++, true);
        }

        if (rowIndex == 0)
            AddLanguageTableRow(Loc.GetString("humanoid-profile-editor-known-languages-empty"), string.Empty, rowIndex, true);
    }

    private void AddLanguageTableHeader()
    {
        KnownLanguagesList.AddChild(MakeLanguageTableRow(
            Loc.GetString("humanoid-profile-editor-known-languages-column-language"),
            Loc.GetString("humanoid-profile-editor-known-languages-column-access"),
            TableHeaderBg,
            TableText,
            heading: true));
    }

    private void AddLanguageTableRow(string language, string access, int rowIndex, bool muted)
    {
        var bg = rowIndex % 2 == 0 ? TableRowBg : TableAltRowBg;
        var color = muted ? TableMutedText : TableText;
        KnownLanguagesList.AddChild(MakeLanguageTableRow(language, access, bg, color, heading: false));
    }

    private static PanelContainer MakeLanguageTableRow(string language, string access, Color background, Color textColor, bool heading)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 3),
        };

        row.AddChild(new Label
        {
            Text = language,
            HorizontalExpand = true,
            FontColorOverride = textColor,
            StyleClasses = { heading ? "LabelKeyText" : "LabelSubText" },
        });

        row.AddChild(new Label
        {
            Text = access,
            MinWidth = 90,
            Align = Label.AlignMode.Right,
            HorizontalAlignment = HAlignment.Right,
            FontColorOverride = textColor,
            StyleClasses = { heading ? "LabelKeyText" : "LabelSubText" },
        });

        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = background },
            Children = { row },
        };
    }

    private void OnRotateLeft(BaseButton.ButtonEventArgs obj)
    {
        _previewRotation = _previewRotation.TurnCw();
        SetPreviewRotation(_previewRotation);
    }

    private void OnRotateRight(BaseButton.ButtonEventArgs obj)
    {
        _previewRotation = _previewRotation.TurnCcw();
        SetPreviewRotation(_previewRotation);
    }

    private void SetPreviewRotation(Direction direction)
    {
        if (direction == Direction.Invalid)
            throw new Exception("Invalid direction");
        // I didn't write this code but it's pretty wacky...
        // It looks like OnRotateLeft/Right will increment or decrement the direction of _previewRotation, which includes
        // all 8 directions, but then this function basically truncates that to four directions, and multiplies by two
        // in order to get the sprite to rotate in 90 degree increments instead of 45 degree increments.
        // It's pretty wacky like I said but I'm not inclined to change code that works right now.
        SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
    }

    /// <summary>
    /// Reloads the entire dummy entity for preview.
    /// This will reload the job profiles and delete and reconstruct the entity from scratch.
    /// </summary>
    /// <remarks>
    /// This is expensive so not recommended to run if you have a slider.
    /// </remarks>
    public void ReloadPreview()
    {
        if (_editor?.Profile == null)
            return;

        SpriteView.LoadPreview(_editor.Profile, _editor?.JobOverride, _editor?.ShouldShowClothes ?? true, _editor?.AntagOverride); // Starlight edit: Antag Loadouts
        UpdateKnownLanguages();
    }

    /// <summary>
    /// A slim reload that only updates the entity itself and not any of the job entities, etc.
    /// This just updates the elements of the entity that can be found in <see cref="HumanoidAppearanceComponent"/>.
    /// Use this for skin color, markings updates, etc.
    /// </summary>
    public void ReloadProfilePreview()
    {
        if (_editor?.Profile == null)
            return;

        SpriteView.ReloadProfilePreview(_editor.Profile);
    }

    /// <summary>
    /// This is task that will initiate an image export of the current entity. Optionally disable a UI button for a half
    /// second for feedback.
    /// </summary>
    /// <param name="buttonToDisable">If specified, this button will be disabled for at least a half second.</param>
    public async void ExportImage(BaseButton? buttonToDisable = null)
    {
        var dir = SpriteView.OverrideDirection ?? Direction.South;

        var tasks = new List<Task>();

        // If we're given a button to momentarily disable for feedback, disable the button and add a delay task to
        // the list
        if(buttonToDisable is not null)
        {
            tasks.Add(Task.Delay(TimeSpan.FromSeconds(0.5f)));
            buttonToDisable.Disabled = true;
        }

        // Add the export task to the list
        tasks.Add(_entityManager.System<ContentSpriteSystem>().Export(SpriteView.PreviewDummy, dir, includeId: false));

        // Wait for the export task and the optional delay task
        await Task.WhenAll(tasks);

        // Now re-enable the button
        if(buttonToDisable is not null)
            buttonToDisable.Disabled = false;
    }
}
