- type: startingGear
  id: RedHeavyGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCasualRed
    gloves: ClothingHandsKnuckleBoneCrushers
    outerClothing: ClothingOuterVestWeb
    shoes: ClothingShoesBootsCombat
    pocket1: FoodBurgerMcrib
    belt: ClothingBeltBandolier
    inhand: WeaponMinigun