using Content.Client._Starlight.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogsWindow : PopOutWindow // Starlight: popout support
{
    protected override Control Control => Logs; // Starlight: popout support

    public AdminLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
