using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.MenuBar.Widgets
{
    [GenerateTypedNameReferences]
    public sealed partial class GameTopMenuBar : UIWidget
    {
        public GameTopMenuBar()
        {
            RobustXamlLoader.Load(this);

            // Starlight-start
            foreach (var button in Bar.Children.OfType<MenuButton>())
            {
                button.IconScale = new Vector2(0.45f, 0.45f);
                button.ShowKey = false;
            }

            Bar.Setup(CharacterButton, EmotesButton, CraftingButton, SandboxButton, ReportBugButton, AchievementButton);
            // Starlight-end
        }
    }
}
