using Content.Shared._Starlight.MHelp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.MHelp.UI;

[GenerateTypedNameReferences]
public sealed partial class MhelpPanel : BoxContainer
{
    public int Unread { get; private set; } = 0;
    public DateTime LastMessage { get; private set; } = DateTime.MinValue;
    private List<string> _peopleTyping { get; set; } = [];
    public bool ShowTpto = false;
    public event Action<string> OnInputTextChanged = delegate { };
    public event Action<string> OnMessageSend = delegate { };
    public event Action OnTicketClosed = delegate { };
    public event Action OnTptoPressed = delegate { };

    public MhelpPanel()
    {
        RobustXamlLoader.Load(this);

        OnVisibilityChanged += c =>
        {
            if (c.Visible)
                Unread = 0;
        };
        Conversation.OnMessageSubmitted += text => OnMessageSend.Invoke(text);
        Conversation.OnInputChanged += text => OnInputTextChanged.Invoke(text);
        CloseTicket.OnPressed += _ => OnTicketClosed.Invoke();
        TptoTicket.OnPressed += _ => OnTptoPressed.Invoke();
        UpdateTypingIndicator();
    }

    public void ReceiveLine(SharedMentorSystem.MHelpTextMessage message)
    {
        if (!Visible)
            Unread++;
        CloseTicket.Visible = message.Ticket is not null && !message.TicketClosed;
        TptoTicket.Visible = CloseTicket.Visible && ShowTpto;
        if (!string.IsNullOrEmpty(message.Title))
            TitleLabel.Text = message.Title;
        var formatted = new FormattedMessage(1);
        formatted.AddMarkupOrThrow(message.Text);
        LastMessage = message.CreateAt;
        Conversation.AddMessage(formatted);
    }

    private void UpdateTypingIndicator()
    {
        var text = _peopleTyping.Count == 0
            ? string.Empty
            : Loc.GetString("bwoink-system-typing-indicator",
                ("players", string.Join(", ", _peopleTyping)),
                ("count", _peopleTyping.Count));

        Conversation.SetTyping(text);
    }

    public void UpdatePlayerTyping(string name, bool typing)
    {
        if (typing)
        {
            if (_peopleTyping.Contains(name))
                return;

            _peopleTyping.Add(name);
            Timer.Spawn(TimeSpan.FromSeconds(10), () =>
            {
                if (Disposed)
                    return;

                _peopleTyping.Remove(name);
                UpdateTypingIndicator();
            });
        }
        else
        {
            _peopleTyping.Remove(name);
        }

        UpdateTypingIndicator();
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
        => base.Dispose(disposing);

    internal void SetInputVisibility(bool v) => Conversation.InputVisible = v;
}
