using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.MHelp.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketEntry : BoxContainer
{
    public TicketEntry() => RobustXamlLoader.Load(this);

    public event Action<Ticket>? OnPinStatusChanged;

    public void Setup(Ticket ticket)
    {
        Update(ticket);
        PlayerEntryPinButton.OnPressed += HandlePinButtonPressed(ticket);
    }

    private Action<BaseButton.ButtonEventArgs> HandlePinButtonPressed(Ticket ticket)
        => args =>
        {
            ticket.IsPinned = !ticket.IsPinned;
            UpdatePinButtonTexture(ticket.IsPinned);
            OnPinStatusChanged?.Invoke(ticket);
        };

    private void Update(Ticket ticket)
    {
        Label.Text = (ticket.IsClosed ? "(X) " : "") + ticket.Title.ToString();

        UpdatePinButtonTexture(ticket.IsPinned);
    }

    private void UpdatePinButtonTexture(bool isPinned)
    {
        if (isPinned)
        {
            PlayerEntryPinButton?.RemoveStyleClass(StyleStarlight.StyleClassPinButtonUnpinned);
            PlayerEntryPinButton?.AddStyleClass(StyleStarlight.StyleClassPinButtonPinned);
        }
        else
        {
            PlayerEntryPinButton?.RemoveStyleClass(StyleStarlight.StyleClassPinButtonPinned);
            PlayerEntryPinButton?.AddStyleClass(StyleStarlight.StyleClassPinButtonUnpinned);
        }
    }
}
