# TODO replace with partials

# Add these as parents to prototypes that can be receive social interactions.
- type: entity
  abstract: true
  id: SocialInteractionReceiver
  components:
  - type: SocialInteractionReceiver
    interactionPrototypes:
    - Pet
    - Boop

# Add as a parent to prototypes that should be able to do simple social interactions (ones that typically don't need hands or arms).
- type: entity
  abstract: true
  id: SocialInteractionGiverSimple
  components:
  - type: SocialInteractionGiver
    interactionPrototypes:
    - Look

# Add as a parent to prototypes that should be able to do complex social interactions that require having arms/hands.
- type: entity
  abstract: true
  id: SocialInteractionGiverComplex
  components:
    interactionPrototypes:
    - Wave
    - Look
