using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Silicons.IPC;
using Content.Shared._FarHorizons.Silicons.IPC.Components;
using Content.Shared.CCVar;
using Content.Shared.Damage;
using Content.Shared.Damage.Components;
using Content.Shared.Eye.Blinding.Components;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.NameIdentifier;
using Content.Shared.NameModifier.EntitySystems;
using Content.Shared.Power.Components;
using Content.Shared.Power.EntitySystems;
using Content.Shared.PowerCell;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Silicons.IPC;

[GenerateTypedNameReferences]
public sealed partial class IPCMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;
    [Dependency] private readonly IEntityManager _entitymanager = default!;
    [Dependency] private readonly IResourceCache _cache = default!;

    public VectorFont ConsoleFont;
    private readonly NameModifierSystem _nameModifier;
    private readonly PowerCellSystem _powerCell;
    private readonly SharedBatterySystem _batterySystem;

    public Action? BrainButtonPressed;
    //public Action? EjectBatteryButtonPressed; The eject battery button is currently bugged and freezes the individual who uses it. Uncomment this when a fix is applied!
    public Action<string>? NameChanged;

    private float _accumulatedTime;
    private string _lastValidName;

    private string _fullText = "";
    private float _charsPerSecond = 150;

    private int _shownCharacters = 0;

    // CCVar.
    private readonly int _maxNameLength;

    private EntityUid _entity;

    private float _bloodLevel;

    public IPCMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConsoleFont = new(_cache.GetResource<FontResource>("/Fonts/_FarHorizons/VT323/vt323-latin-400-normal.ttf"), 14);
        StatusLabel.FontOverride = ConsoleFont;

        _nameModifier = _entitymanager.System<NameModifierSystem>();
        _powerCell = _entitymanager.System<PowerCellSystem>();
        _batterySystem = _entitymanager.System<SharedBatterySystem>();

        _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);

        _lastValidName = NameLineEdit.Text;

        //The eject battery button is currently bugged and freezes the individual who uses it. Uncomment this when a fix is applied!
        //EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
        BrainButton.OnPressed += _ => BrainButtonPressed?.Invoke();

        NameLineEdit.OnTextChanged += OnNameChanged;
        NameLineEdit.OnTextEntered += OnNameEntered;
        NameLineEdit.OnFocusExit += OnNameFocusExit;
    }

    public void SetHealth(IPCHealthMessage healthMessage) =>
        _bloodLevel = (float)healthMessage.BloodLevel;

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        IPCSprite.SetEntity(entity);

        if (_entitymanager.TryGetComponent<NameIdentifierComponent>(_entity, out var nameIdentifierComponent))
        {
            NameIdentifierLabel.Visible = true;
            NameIdentifierLabel.Text = nameIdentifierComponent.FullIdentifier;

            NameLineEdit.Text = _nameModifier.GetBaseName(entity);
        }
        else
        {
            NameIdentifierLabel.Visible = false;
            NameLineEdit.Text = _entitymanager.GetComponent<MetaDataComponent>(_entity).EntityName;
        }

        UpdateWindow();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _accumulatedTime += args.DeltaSeconds;
        IPCSprite.OverrideDirection = (Direction)((int)_accumulatedTime % 4 * 2);

        _shownCharacters = Math.Min((int)Math.Ceiling(_charsPerSecond * _accumulatedTime), _fullText.Length);
        StatusLabel.Text = _fullText[.._shownCharacters];

        UpdateWindow();
    }

    private void UpdateWindow()
    {
        var eyeDamage = 0;
        if (_entitymanager.TryGetComponent<BlindableComponent>(_entity, out var blind))
            eyeDamage = blind.EyeDamage;

        var damage = new DamageSpecifier();
        if (_entitymanager.TryGetComponent<DamageableComponent>(_entity, out var damagecomp))
            damage = damagecomp.Damage;

        var temp = 0f;
        LocId fanMode = "";
        var fansEfficiency = "";
        if (_entitymanager.TryGetComponent<IPCThermalRegulationComponent>(_entity, out var thermals))
        {
            temp = thermals.CurrentTemp;
            fanMode = thermals.FansCurrentlyOff || thermals.CurrentMode == null ?
                        thermals.FansOffDiagnosticsText :
                        thermals.CurrentMode.DiagnosticsText;
            fansEfficiency = thermals.FansCurrentlyOff || thermals.CurrentMode == null ?
                                Loc.GetString("ipc-ui-console-fans-efficiency-none") :
                                (thermals.CurrentEfficiency * 100).ToString("F2") + "%";
        }

        var batteryInserted = false;
        float batteryCharge = 0;
        if (_powerCell.TryGetBatteryFromSlot(_entity, out var batteryEnt) && batteryEnt is Entity<BatteryComponent> checkedBattery)
        {
            batteryInserted = true;
            batteryCharge = _batterySystem.GetChargeLevel((checkedBattery.Owner, checkedBattery.Comp));
        }

        var mobstate = MobState.Invalid;
        if (_entitymanager.TryGetComponent<MobStateComponent>(_entity, out var mobStatecomp))
            mobstate = mobStatecomp.CurrentState;

        IPCBrainHolderComponent? brain = null;
        if (_entitymanager.TryGetComponent<IPCBrainHolderComponent>(_entity, out var brainComp))
            brain = brainComp;

        _fullText = PrintConsole(mobstate.ToString(), batteryInserted, batteryCharge, eyeDamage, _bloodLevel, temp, fanMode, fansEfficiency, brain, damage);
        UpdateBrainButton(brain);
        //The eject battery button is currently bugged and freezes the individual who uses it. Uncomment this when a fix is applied!
        //EjectBatteryButton.Disabled = !batteryInserted;
        ChargeBar.Value = batteryCharge;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int)MathF.Round(batteryCharge * 100)));
    }

    private static string PrintConsole(string currentState, bool hasBattery, float batteryCharge, int eyeDamage, float bloodLevel, float currentTemp, string fansMode, string fansEfficiency, IPCBrainHolderComponent? brain, DamageSpecifier damageSpec)
    {
        var separator = Loc.GetString("ipc-ui-console-separator") + '\n';

        var header = separator;
        var i = 1;
        while (i < 7)
        {
            var index = $"ipc-ui-console-header-{i}";
            var line = Loc.GetString(index);
            if (line == index)
                break;

            header += line + '\n';
            i++;
        }
        header += separator;
        header += Loc.GetString("ipc-ui-console-diagnostics-section") + '\n';

        var itemInstalled = Loc.GetString("ipc-ui-console-part-installed");
        var itemMissing = Loc.GetString("ipc-ui-console-part-missing");

        var eyeDamageNone = Loc.GetString("ipc-ui-console-eye-damage-none");
        var eyeDamageSome = Loc.GetString("ipc-ui-console-eye-damage-some");
        var eyeDamageLots = Loc.GetString("ipc-ui-console-eye-damage-lots");

        List<(string name, string value)> status = [];
        status.Add((Loc.GetString("ipc-ui-console-status"), currentState));
        status.Add((Loc.GetString("ipc-ui-console-brain"), brain != null ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery"), hasBattery ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery-charge"), (batteryCharge * 100).ToString("F2") + "%"));
        status.Add((Loc.GetString("ipc-ui-console-eye-damage"), eyeDamage == 0 ? eyeDamageNone : eyeDamage < 3 ? eyeDamageSome : eyeDamageLots));
        status.Add((Loc.GetString("ipc-ui-console-blood-level"), (bloodLevel * 100).ToString("F2") + "%"));
        status.Add((Loc.GetString("ipc-ui-console-temperature"), $"{TemperatureHelpers.KelvinToCelsius(currentTemp):F2}C"));
        status.Add((Loc.GetString("ipc-ui-console-fans"), Loc.GetString(fansMode)));
        status.Add((Loc.GetString("ipc-ui-console-fans-efficiency"), fansEfficiency));

        var body = AestheticJoin(status);

        body += separator;

        var damageText = "";
        List<(string name, string value)> damage = [];
        if (damageSpec.GetTotal() > 0)
        {
            damageText += Loc.GetString("ipc-ui-console-damage-section") + '\n';
            foreach (var (name, value) in damageSpec.DamageDict.OrderByDescending(p => p.Value))
                if (value != 0)
                    damage.Add((name, value.ToString()));
        }
        else
            damageText += Loc.GetString("ipc-ui-console-damage-none") + '\n';

        damageText += AestheticJoin(damage);

        return header + body + damageText;
    }

    private static string AestheticJoin(List<(string name, string value)> items, char padWith = '.', string joinWith = ".....")
    {
        var result = "";

        var longestName = items.Select(p => p.name.Length).OrderDescending().FirstOrDefault(0);
        if (longestName < 1)
            return result;

        foreach (var (name, value) in items)
        {
            var lenDiff = longestName - name.Length;
            result += name + new string(padWith, lenDiff) + joinWith + value + '\n';
        }

        return result;
    }

    private static T? TryGetAssignComp<T>(IEntityManager entSys, EntityUid ent, ref T? assign) where T : Component
    {
        if (!entSys.TryGetComponent<T>(ent, out var comp))
            return null;

        assign = comp;
        return comp;
    }

    private void UpdateBrainButton(IPCBrainHolderComponent? brainComp)
    {
        if (brainComp != null &&
            brainComp.BrainEntity is EntityUid brain)
        {
            BrainButton.Text = _entitymanager.GetComponent<MetaDataComponent>(brain).EntityName;
            BrainView.Visible = true;
            BrainView.SetEntity(brain);
            BrainButton.Disabled = false;
            BrainButton.AddStyleClass(StyleClass.ButtonOpenLeft);
        }
        else
        {
            BrainButton.Text = Loc.GetString("borg-ui-no-brain");
            BrainButton.Disabled = true;
            BrainView.Visible = false;
            BrainButton.RemoveStyleClass(StyleClass.ButtonOpenLeft);
        }
    }

    private void OnNameChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
            return;

        if (obj.Text.Length > _maxNameLength)
            obj.Control.Text = obj.Text[.._maxNameLength];

        _lastValidName = obj.Control.Text;
        obj.Control.Text = _lastValidName;
    }

    private void OnNameEntered(LineEdit.LineEditEventArgs _) =>
        NameChanged?.Invoke(_lastValidName);

    private void OnNameFocusExit(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length > _maxNameLength ||
            obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            obj.Control.Text = _lastValidName.Trim();
        }

        NameChanged?.Invoke(_lastValidName);
    }
}