using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Silicons.IPC;
using Content.Shared._FarHorizons.Silicons.IPC.Components;
using Content.Shared.CCVar;
using Content.Shared.Damage;
using Content.Shared.Damage.Components;
using Content.Shared.Eye.Blinding.Components;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.NameIdentifier;
using Content.Shared.NameModifier.EntitySystems;
using Content.Shared.Power.Components;
using Content.Shared.Power.EntitySystems;
using Content.Shared.PowerCell;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Silicons.IPC;

[GenerateTypedNameReferences]
public sealed partial class IPCMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IResourceCache _cache = default!;

    public VectorFont ConsoleFont;
    private readonly NameModifierSystem _nameModifier;
    private readonly PowerCellSystem _powerCell;
    private readonly SharedBatterySystem _batterySystem;

    public Action? BrainButtonPressed;
    public Action? EjectBatteryButtonPressed;
    public Action<string>? NameChanged;

    public float AccumulatedTime;
    private string _lastValidName;

    public string FullText = "";
    public float CharsPerSecond = 150;

    private int _shownCharacters = 0;

    // CCVar.
    private readonly int _maxNameLength;

    public EntityUid Entity;

    private float _bloodLevel;

    private DamageableComponent? _damage = null;
    public DamageableComponent? Damage
    {
        get => _damage ?? TryGetAssignComp(_entity, Entity, ref _damage);
        set => _damage = value;
    }

    private BlindableComponent? _blind = null;
    public BlindableComponent? Blind
    {
        get => _blind ?? TryGetAssignComp(_entity, Entity, ref _blind);
        set => _blind = value;
    }

    private MobStateComponent? _state = null;
    public MobStateComponent? State
    {
        get => _state ?? TryGetAssignComp(_entity, Entity, ref _state);
        set => _state = value;
    }

    private IPCBrainHolderComponent? _brain = null;
    public IPCBrainHolderComponent? Brain
    {
        get => _brain ?? TryGetAssignComp(_entity, Entity, ref _brain);
        set => _brain = value;
    }
    
    private IPCThermalRegulationComponent? _thermals = null;
    public IPCThermalRegulationComponent? Thermals
    {
        get => _thermals ?? TryGetAssignComp(_entity, Entity, ref _thermals);
        set => _thermals = value;
    }

    private IPCBatteryComponent? _battery = null;
    public IPCBatteryComponent? Battery
    {
        get => _battery ?? TryGetAssignComp(_entity, Entity, ref _battery);
        set => _battery = value;
    }

    public bool LastKnownBattery = false;
    public float LastKnownCharge = 0;

    public MobState LastKnownState = MobState.Dead;

    public IPCMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConsoleFont = new(_cache.GetResource<FontResource>("/Fonts/_FarHorizons/VT323/vt323-latin-400-normal.ttf"), 14);
        StatusLabel.FontOverride = ConsoleFont;

        _nameModifier = _entity.System<NameModifierSystem>();
        _powerCell = _entity.System<PowerCellSystem>();
        _batterySystem = _entity.System<SharedBatterySystem>();

        _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);

        _lastValidName = NameLineEdit.Text;

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
        BrainButton.OnPressed += _ => BrainButtonPressed?.Invoke();

        NameLineEdit.OnTextChanged += OnNameChanged;
        NameLineEdit.OnTextEntered += OnNameEntered;
        NameLineEdit.OnFocusExit += OnNameFocusExit;
    }

    public void SetHealth(IPCHealthMessage healthMessage) =>
        _bloodLevel = (float)healthMessage.BloodLevel;

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        IPCSprite.SetEntity(entity);

        if (_entity.TryGetComponent<NameIdentifierComponent>(Entity, out var nameIdentifierComponent))
        {
            NameIdentifierLabel.Visible = true;
            NameIdentifierLabel.Text = nameIdentifierComponent.FullIdentifier;

            NameLineEdit.Text = _nameModifier.GetBaseName(entity);
        }
        else
        {
            NameIdentifierLabel.Visible = false;
            NameLineEdit.Text = _entity.GetComponent<MetaDataComponent>(Entity).EntityName;
        }

        UpdateWindow();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        AccumulatedTime += args.DeltaSeconds;
        IPCSprite.OverrideDirection = (Direction) ((int) AccumulatedTime % 4 * 2);

        _shownCharacters = Math.Min((int)Math.Ceiling(CharsPerSecond * AccumulatedTime), FullText.Length);
        StatusLabel.Text = FullText[.._shownCharacters];

        UpdateWindow();
    }

    private void UpdateWindow()
    {
        var eyeDamage = 0;
        if (Blind != null)
            eyeDamage = Blind.EyeDamage;

        var damage = new DamageSpecifier();
        if (Damage != null)
            damage = Damage.Damage;

        var temp = 0f;
        LocId fanMode = "";
        var fansEfficiency = "";
        if (Thermals != null)
        {
            temp = Thermals.CurrentTemp;
            fanMode = Thermals.FansCurrentlyOff || Thermals.CurrentMode == null ? 
                        Thermals.FansOffDiagnosticsText : 
                        Thermals.CurrentMode.DiagnosticsText;
            fansEfficiency = Thermals.FansCurrentlyOff || Thermals.CurrentMode == null ?
                                Loc.GetString("ipc-ui-console-fans-efficiency-none") :
                                (Thermals.CurrentEfficiency * 100).ToString("F2") + "%";
        }

        var batteryInserted = false;
        float batteryCharge = 0;
        if (_powerCell.TryGetBatteryFromSlot(Entity, out var batteryEnt) && batteryEnt is Entity<BatteryComponent> checkedBattery)
        {
            batteryInserted = true;
            batteryCharge = _batterySystem.GetChargeLevel((checkedBattery.Owner, checkedBattery.Comp));
        }

        if (_entity.TryGetComponent<MobStateComponent>(Entity, out var mobState))
            LastKnownState = mobState.CurrentState;

        FullText = PrintConsole(LastKnownState.ToString(), batteryInserted, batteryCharge, eyeDamage, _bloodLevel, temp, fanMode, fansEfficiency, Brain, damage);
        UpdateBrainButton(Brain);
        EjectBatteryButton.Disabled = !batteryInserted;
        ChargeBar.Value = batteryCharge;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int) MathF.Round(batteryCharge * 100)));
    }

    private static string PrintConsole(string currentState, bool hasBattery, float batteryCharge, int eyeDamage, float bloodLevel, float currentTemp, string fansMode, string fansEfficiency, IPCBrainHolderComponent? brain, DamageSpecifier damageSpec)
    {
        var separator = Loc.GetString("ipc-ui-console-separator") + '\n';

        var header = separator;
        var i = 1;
        while (true)
        {
            var index = $"ipc-ui-console-header-{i}";
            var line = Loc.GetString(index);
            if(line == index)
                break;

            header += line + '\n';
            i++;
        }
        header += separator;
        header += Loc.GetString("ipc-ui-console-diagnostics-section") + '\n';

        var itemInstalled = Loc.GetString("ipc-ui-console-part-installed");
        var itemMissing = Loc.GetString("ipc-ui-console-part-missing");

        var eyeDamageNone = Loc.GetString("ipc-ui-console-eye-damage-none");
        var eyeDamageSome = Loc.GetString("ipc-ui-console-eye-damage-some");
        var eyeDamageLots = Loc.GetString("ipc-ui-console-eye-damage-lots");

        List<(string name, string value)> status = [];
        status.Add((Loc.GetString("ipc-ui-console-status"), currentState));
        status.Add((Loc.GetString("ipc-ui-console-brain"), brain != null ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery"), hasBattery ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery-charge"), (batteryCharge * 100).ToString("F2") + "%"));
        status.Add((Loc.GetString("ipc-ui-console-eye-damage"), eyeDamage == 0 ? eyeDamageNone : eyeDamage < 3 ? eyeDamageSome : eyeDamageLots));
        status.Add((Loc.GetString("ipc-ui-console-blood-level"), (bloodLevel * 100).ToString("F2") + "%"));
        status.Add((Loc.GetString("ipc-ui-console-temperature"), $"{TemperatureHelpers.KelvinToCelsius(currentTemp):F2}C"));
        status.Add((Loc.GetString("ipc-ui-console-fans"), Loc.GetString(fansMode)));
        status.Add((Loc.GetString("ipc-ui-console-fans-efficiency"), fansEfficiency));

        var body = AestheticJoin(status);

        body += separator;

        var damageText = "";
        List<(string name, string value)> damage = [];
        if (damageSpec.GetTotal() > 0)
        {
            damageText += Loc.GetString("ipc-ui-console-damage-section") + '\n';
            foreach (var (name, value) in damageSpec.DamageDict.OrderByDescending(p => p.Value))
                if (value != 0)
                    damage.Add((name, value.ToString()));
        } else
            damageText += Loc.GetString("ipc-ui-console-damage-none") + '\n';

        damageText += AestheticJoin(damage);

        return header + body + damageText;
    }

    private static string AestheticJoin(List<(string name, string value)> items, char padWith = '.', string joinWith = ".....")
    {
        var result = "";

        var longestName = items.Select(p => p.name.Length).OrderDescending().FirstOrDefault(0);
        if (longestName < 1)
            return result;
        
        foreach (var (name, value) in items)
        {
            var lenDiff = longestName - name.Length;
            result += name + new string(padWith, lenDiff) + joinWith + value + '\n';
        }

        return result;
    }

    private static T? TryGetAssignComp<T>(IEntityManager entSys, EntityUid ent, ref T? assign) where T : Component
    {
        if(!entSys.TryGetComponent<T>(ent, out var comp))
            return null;

        assign = comp;
        return comp;
    }

    private void UpdateBrainButton(IPCBrainHolderComponent? brainComp)
    {
        if (brainComp != null && 
            brainComp.BrainEntity is EntityUid brain)
        {
            BrainButton.Text = _entity.GetComponent<MetaDataComponent>(brain).EntityName;
            BrainView.Visible = true;
            BrainView.SetEntity(brain);
            BrainButton.Disabled = false;
            BrainButton.AddStyleClass(StyleClass.ButtonOpenLeft);
        }
        else
        {
            BrainButton.Text = Loc.GetString("borg-ui-no-brain");
            BrainButton.Disabled = true;
            BrainView.Visible = false;
            BrainButton.RemoveStyleClass(StyleClass.ButtonOpenLeft);
        }
    }

    private void OnNameChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
            return;

        if (obj.Text.Length > _maxNameLength)
            obj.Control.Text = obj.Text[.._maxNameLength];

        _lastValidName = obj.Control.Text;
        obj.Control.Text = _lastValidName;
    }

    private void OnNameEntered(LineEdit.LineEditEventArgs _) => 
        NameChanged?.Invoke(_lastValidName);

    private void OnNameFocusExit(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length > _maxNameLength ||
            obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            obj.Control.Text = _lastValidName.Trim();
        }

        NameChanged?.Invoke(_lastValidName);
    }
}