using System.Linq;
using Content.Shared._Moffstation.Roles;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Antags.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagCategory : BoxContainer
{
    public event Action<ProtoId<AntagPrototype>, bool>? OnAntagToggled;
    public event Action<ProtoId<AntagPrototype>>? OnLoadoutPressed;

    private readonly List<AntagPrototype> _antags;
    private readonly Dictionary<ProtoId<AntagPrototype>, AntagEntry> _antagEntries = new();

    private bool _isExpanded;

    public bool IsExpanded => _isExpanded;
    public int SelectedCount;

    public AntagCategory(AntagCategoryPrototype category, List<AntagPrototype> antags, IReadOnlySet<ProtoId<AntagPrototype>>? selectedAntags = null, bool? expandedOverride = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _isExpanded = expandedOverride ?? category.DefaultExpanded;
        _antags = antags.OrderBy(a => a.Name).ToList();

        CategoryNameLabel.Text = Loc.GetString(category.Name);
        CategoryDescriptionLabel.Text = Loc.GetString(category.Description);
        SetAccentColor(category.AccentColor);

        HeaderButton.OnPressed += _ => ToggleExpanded();

        PopulateAntags(selectedAntags);
        UpdateExpandedState();
        UpdateStats();
    }

    private void SetAccentColor(Color color)
    {
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = color }; // dumb stylesheet modulation workaround
    }

    private void PopulateAntags(IReadOnlySet<ProtoId<AntagPrototype>>? selectedAntags)
    {
        AntagsContainer.RemoveAllChildren();
        _antagEntries.Clear();

        foreach (var antag in _antags)
        {
            var isSelected = selectedAntags?.Contains(antag.ID) ?? false;
            var entry = new AntagEntry(antag, isSelected);
            entry.OnToggled += selected => OnTraitEntryToggled(antag.ID, selected);
            entry.OnLoadoutPressed += () => OnLoadoutPressed?.Invoke(antag.ID);
            _antagEntries[antag.ID] = entry;
            AntagsContainer.AddChild(entry);
        }
    }

    private void OnTraitEntryToggled(ProtoId<AntagPrototype> traitId, bool selected)
    {
        UpdateStats();
        OnAntagToggled?.Invoke(traitId, selected);
    }

    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }

    public void UpdateStats()
    {
        SelectedCount = _antagEntries.Values.Count(e => e.IsSelected);

        CategoryStatsLabel.Text = Loc.GetString("antag-category-enabled",
            ("selected", SelectedCount),
            ("total", _antagEntries.Count));

        CategoryPointsLabel.Visible = false;
    }

    /// <summary>
    /// Gets the IDs of all currently selected antags in this category.
    /// </summary>
    public IEnumerable<ProtoId<AntagPrototype>> GetSelectedAntagIds()
    {
        return _antagEntries
            .Where(kvp => kvp.Value.IsSelected)
            .Select(kvp => kvp.Key);
    }

    /// <summary>
    /// Filters traits based on search text only
    /// </summary>
    public void FilterAntags(string searchText)
    {
        var hasVisibleAntags = false;

        foreach (var (traitId, entry) in _antagEntries)
        {
            var antag = _antags.First(a => a.ID == traitId);
            var name = Loc.GetString(antag.Name);
            // var description = Loc.GetString(trait.Description);

            var matchesSearch = string.IsNullOrEmpty(searchText) ||
                                name.Contains(searchText, StringComparison.OrdinalIgnoreCase);
                                // description.Contains(searchText, StringComparison.OrdinalIgnoreCase);

            entry.Visible = matchesSearch;

            if (entry.Visible)
                hasVisibleAntags = true;
        }

        // Hide entire category if no traits match search
        Visible = hasVisibleAntags;
    }
}
