using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Genetics.Ui;

public sealed class GeneticsConsoleBoundUserInterface : BoundUserInterface
{
    [ViewVariables]
    public GeneticsConsoleWindow _window = default!;

    public GeneticsConsoleBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey)
    {
    }

    protected override void Open()
    {
        base.Open();

        _window = this.CreateWindow<GeneticsConsoleWindow>();
    }
}

