using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sol.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SolContextualSurgeryWindow : DefaultWindow
{
    public SolContextualSurgeryWindow() => RobustXamlLoader.Load(this);
}
