using Content.Client._Starlight;
using Content.Client.Lathe.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Functional.TutorialServer.StarlightSurgery;

[GenerateTypedNameReferences]
public sealed partial class TutorialStarlightSurgeryStepButton : ChoiceControl
{
    public string StepId { get; set; } = string.Empty;

    public Func<string> TooltipTextSupplier { get; set; } = static () => string.Empty;

    public TutorialStarlightSurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
        Button.TooltipSupplier = SupplyTooltip;
    }

    private Control? SupplyTooltip(Control sender) => new RecipeTooltip(TooltipTextSupplier());
}
