using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Functional.TutorialServer.StarlightSurgery;

[GenerateTypedNameReferences]
public sealed partial class TutorialStarlightSurgeryWindow : DefaultWindow
{
    public TutorialStarlightSurgeryWindow() => RobustXamlLoader.Load(this);
}
