// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.ContentWarning;

[GenerateTypedNameReferences]
public sealed partial class ContentWarningPopup : FancyWindow
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    public event Action? OnContentWarningAccept;
    public event Action? OnContentWarningReject;

    public ContentWarningPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        InitWindow();
    }

    private void InitWindow()
    {
        ContentWarningBodyIntro.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("content-warning-introduction")));
		
		ContentWarningBodyInfo.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("content-warning-information")));

        ContentWarningReject.OnPressed += _ =>
        {
            OnContentWarningReject?.Invoke();
        };

        ContentWarningAccept.OnPressed += obj =>
        {
            OnContentWarningAccept?.Invoke();
        };
    }
}
