- type: antag
  id: Pirate
  name: ghost-role-information-pirate-name
  antagonist: true
  setPreference: false
  objective: roles-antag-pirate-objective
  playTimeTracker: AntagPirate

- type: antag
  id: PirateCaptain
  name: ghost-role-information-pirate-name
  antagonist: true
  setPreference: false
  objective: roles-antag-pirate-objective
  playTimeTracker: AntagPirateCaptain
