#!/usr/bin/env python3
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

FULL_DIRS = [
    "Content.Server/_Starlight",
    "Content.Shared/_Starlight",
    "Resources/Prototypes/_Starlight",
    "Content.Client/_Starlight",
]

USINGS_DIRS = [
    "Content.Server",
    "Content.Shared",
    "Content.Client",
]

FULL_WORDS = [
    "Starlight",
    "NullLink",
]

SKIP_DOC_COMMENTS = True

USINGS_IGNORE = [
    re.compile(r"SPDX-(License-Identifier|FileCopyrightText)", re.IGNORECASE),
    re.compile(r"<auto-generated", re.IGNORECASE),
]

SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__", "dist", "build", "obj", "bin"}
WORD = re.compile(r"\b(?:" + "|".join(re.escape(w) for w in FULL_WORDS) + r")\b", re.IGNORECASE)
NAMESPACE = re.compile(r"^\s*namespace\b")
REGION = re.compile(r"^\s*#\s*(region|endregion)\b")
HAS_CONTENT = re.compile(r"[A-Za-z0-9]")
WORKERS = min(32, (os.cpu_count() or 4) * 4)

COMMENT_SYNTAX = {
    ".py": (["#"], [('"""', '"""'), ("'''", "'''")]),
    ".yml": (["#"], []),
    ".yaml": (["#"], []),
    ".cs": (["//"], [("/*", "*/")]),
    ".xml": ([], [("<!--", "-->")]),
}

MESSAGES = {
    ("full", "comment"): "Forbidden word in a comment inside a _Starlight folder: {text}",
    ("full", "region"): "Forbidden word in a region inside a _Starlight folder: {text}",
    ("usings", "comment"): "Comments are not allowed in the usings block: {text}",
    ("usings", "region"): "Regions are not allowed in the usings block: {text}",
}


def posix(path):
    return path.replace(os.sep, "/").replace("\\", "/")


STRING_LITERAL = re.compile(r'"(?:\\.|[^"\\])*"' + r"|'(?:\\.|[^'\\])*'")


def mask_strings(line):
    return STRING_LITERAL.sub(lambda m: '"' + " " * (len(m.group()) - 2) + '"', line)


def comment_lines(lines, line_markers, block_pairs):
    open_marker = None
    for num, line in enumerate(lines, 1):
        if open_marker:
            yield num, line
            if open_marker[1] in line:
                open_marker = None
            continue

        masked = mask_strings(line)

        starts = [i for i in (masked.find(m) for m in line_markers) if i != -1]
        line_idx = min(starts) if starts else -1

        block_idx, pair = -1, None
        for start, end in block_pairs:
            i = masked.find(start)
            if i != -1 and (block_idx == -1 or i < block_idx):
                block_idx, pair = i, (start, end)

        if line_idx != -1 and (block_idx == -1 or line_idx < block_idx):
            yield num, line[line_idx:]
            continue

        if block_idx != -1:
            start, end = pair
            yield num, line[block_idx:]
            if masked.find(end, block_idx + len(start)) == -1:
                open_marker = pair


def is_reported(text, mode):
    if mode == "full":
        if SKIP_DOC_COMMENTS and text.lstrip().startswith("///"):
            return False
        return bool(WORD.search(text))

    if not HAS_CONTENT.search(text):
        return False
    return not any(p.search(text) for p in USINGS_IGNORE)


def check_file(entry):
    path, mode = entry
    ext = os.path.splitext(path)[1].lower()
    syntax = COMMENT_SYNTAX.get(ext)
    if not syntax:
        return []

    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except (UnicodeDecodeError, OSError):
        return []

    lines = content.splitlines()

    if mode == "usings":
        for i, line in enumerate(lines):
            if NAMESPACE.match(line):
                lines = lines[:i]
                break
        else:
            return []
    elif not WORD.search(content):
        return []

    hits = {}

    for num, text in comment_lines(lines, *syntax):
        if is_reported(text, mode):
            hits[num] = (text.strip(), "comment")

    if ext == ".cs":
        for num, line in enumerate(lines, 1):
            if not REGION.match(line):
                continue
            if mode == "usings" or WORD.search(line):
                hits[num] = (line.strip(), "region")

    return [(path, num, text, mode, kind) for num, (text, kind) in hits.items()]


def collect_paths():
    exts = tuple(COMMENT_SYNTAX)
    seen = set()

    for mode, dirs, only_cs in (("full", FULL_DIRS, False), ("usings", USINGS_DIRS, True)):
        for root_dir in dirs:
            root_dir = posix(root_dir)
            if not os.path.isdir(root_dir):
                print(f"warning: directory can't be found: {root_dir}", file=sys.stderr)
                continue
            for root, subdirs, files in os.walk(root_dir):
                subdirs[:] = [d for d in subdirs if d not in SKIP_DIRS]
                if mode == "usings":
                    subdirs[:] = [d for d in subdirs if d != "_Starlight"]
                for name in files:
                    lowered = name.lower()
                    if only_cs:
                        if not lowered.endswith(".cs"):
                            continue
                    elif not lowered.endswith(exts):
                        continue
                    path = posix(os.path.join(root, name))
                    if path in seen:
                        continue
                    seen.add(path)
                    yield path, mode


def write_summary(errors, scanned):
    target = os.environ.get("GITHUB_STEP_SUMMARY")
    if not target:
        return
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    sha = os.environ.get("GITHUB_SHA", "")

    rows = []
    for path, num, text, mode, kind in errors:
        location = f"{path}:{num}"
        if repo and sha:
            location = f"[{location}]({server}/{repo}/blob/{sha}/{path}#L{num})"
        snippet = text.replace("|", "\\|")
        rows.append(f"| {location} | `{snippet}` | {mode} / {kind} |")

    try:
        with open(target, "a", encoding="utf-8") as f:
            f.write(f"### Starlight check: {len(errors)} found in {scanned} files\n\n")
            f.write("| Location | Match | Rule |\n|---|---|---|\n")
            f.write("\n".join(rows) + "\n")
    except OSError:
        pass


def main():
    entries = list(collect_paths())

    errors = []
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        for result in pool.map(check_file, entries, chunksize=32):
            errors.extend(result)

    errors.sort()
    for path, num, text, mode, kind in errors:
        reason = MESSAGES[(mode, kind)].format(text=text)
        print(f"::error file={path},line={num}::{path}:{num} - {reason}")

    if errors:
        print("", file=sys.stderr)
        print(f"Found entries: {len(errors)} (scanned {len(entries)} files)", file=sys.stderr)
        for path, num, text, mode, kind in errors:
            print(f"  {path}:{num}: {text}", file=sys.stderr)
        write_summary(errors, len(entries))
        return 1

    print(f"OK: nothing found. Scanned {len(entries)} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
