using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.Tabs.EventsTab;

[GenerateTypedNameReferences]
public sealed partial class EventsTab : Control
{
    private enum EventSortMode
    {
        Name,
        State,
        Availability,
        Duration,
        Weight,
        MinimumPlayers,
        EarliestStart,
        Cooldown
    }

    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IClientConsoleHost _console = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly Color _altColor = Color.FromHex("#292B38");
    private readonly Color _defaultColor = Color.FromHex("#2F2F3B");
    private readonly AdminSystem _adminSystem;
    private const float AutoRefreshInterval = 1f;
    private float _refreshAccumulator;
    private bool _sortAscending = false;
    private bool _hasScheduler;
    private EventSortMode _sortMode = EventSortMode.Weight;

    public EventsTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _adminSystem = _entityManager.System<AdminSystem>();
        _adminSystem.StationEventsChanged += OnStationEventsChanged;

        SearchList.SearchBar = SearchLineEdit;
        SearchList.GenerateItem += GenerateItem;
        SearchList.DataFilterCondition += DataFilterCondition;

        AvailableOnlyButton.OnPressed += _ => Repopulate(_adminSystem.StationEventsSnapshot);
        RefreshButton.OnPressed += _ => RefreshSnapshot();
        SortOptionButton.OnItemSelected += OnSortItemSelected;
        SortDirectionButton.OnPressed += _ =>
        {
            _sortAscending = !_sortAscending;
            UpdateSortDirectionText();
            Repopulate(_adminSystem.StationEventsSnapshot);
        };

        PopulateSortOptions();
        UpdateSortDirectionText();

        if (_adminSystem.StationEventsSnapshot != null)
            Repopulate(_adminSystem.StationEventsSnapshot);
        else
            RefreshSnapshot();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _adminSystem.StationEventsChanged -= OnStationEventsChanged;
    }

    private void OnStationEventsChanged(StationEventsChangedEvent snapshot)
    {
        Repopulate(snapshot);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _refreshAccumulator += args.DeltaSeconds;
        if (_refreshAccumulator < AutoRefreshInterval)
            return;

        RefreshSnapshot();
    }

    private void Repopulate(StationEventsChangedEvent? snapshot)
    {
        if (snapshot == null)
        {
            SummaryLabel.Text = Loc.GetString("administration-ui-events-tab-loading");
            SearchList.PopulateList(new List<ListData>());
            return;
        }

        _hasScheduler = snapshot.HasScheduler;
        PopulateQueue(snapshot);
        PopulateActiveEvents(snapshot);

        var activeCount = snapshot.ActiveEvents.Count;
        var pendingCount = snapshot.Events.Sum(ev => ev.PendingCount);
        SummaryLabel.Text = Loc.GetString(
            "administration-ui-events-tab-summary",
            ("count", snapshot.Events.Count),
            ("active", activeCount),
            ("pending", pendingCount),
            ("players", snapshot.PlayerCount),
            ("minutes", snapshot.RoundDurationMinutes),
            ("enabled", snapshot.HasScheduler && snapshot.EventsEnabled
                ? Loc.GetString("administration-ui-events-tab-enabled")
                : Loc.GetString("administration-ui-events-tab-disabled")));

        var orderedEvents = SortEvents(snapshot.Events);

        var rows = orderedEvents
            .Where(ev => !AvailableOnlyButton.Pressed || ev.Available)
            .Select((ev, index) => new StationEventListData(
                ev,
                index % 2 == 0 ? _altColor : _defaultColor,
                BuildFilterString(ev)))
            .ToList<ListData>();

        SearchList.PopulateList(rows);
    }

    private void PopulateQueue(StationEventsChangedEvent snapshot)
    {
        QueueList.RemoveAllChildren();

        if (!snapshot.HasScheduler)
        {
            QueueStatusLabel.Text = Loc.GetString("administration-ui-events-tab-queue-no-scheduler");
            return;
        }

        QueueStatusLabel.Text = snapshot.Queue.Count == 0
            ? Loc.GetString("administration-ui-events-tab-queue-empty")
            : Loc.GetString("administration-ui-events-tab-queue-count", ("count", snapshot.Queue.Count));

        foreach (var queued in snapshot.Queue)
        {
            var panel = CreatePanel(queued.Automatic ? Color.FromHex("#24384A") : Color.FromHex("#3D3523"));
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                Margin = new Thickness(7)
            };
            var details = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            details.AddChild(new Label
            {
                Text = Loc.GetString(
                    queued.Automatic
                        ? "administration-ui-events-tab-queue-automatic"
                        : "administration-ui-events-tab-queue-manual",
                    ("event", HumanizeId(queued.EventId)),
                    ("id", queued.EventId))
            });
            details.AddChild(new Label
            {
                Text = Loc.GetString("administration-ui-events-tab-queue-starts-in",
                    ("time", FormatSeconds(queued.TriggerInSeconds))),
                ModulateSelfOverride = Color.LightSteelBlue
            });
            details.AddChild(new ProgressBar
            {
                HorizontalExpand = true,
                MaxValue = Math.Max(queued.TotalDelaySeconds, 1f),
                Value = Math.Clamp(queued.TriggerInSeconds, 0f, Math.Max(queued.TotalDelaySeconds, 1f))
            });

            row.AddChild(details);
            AddQueueButton(row, "-5m", queued.Id, StationEventQueueCommand.Adjust, -300f);
            AddQueueButton(row, "-1m", queued.Id, StationEventQueueCommand.Adjust, -60f);
            AddQueueButton(row, "+1m", queued.Id, StationEventQueueCommand.Adjust, 60f);
            AddQueueButton(row, "+5m", queued.Id, StationEventQueueCommand.Adjust, 300f);
            AddQueueButton(row,
                Loc.GetString("administration-ui-events-tab-queue-now"),
                queued.Id,
                StationEventQueueCommand.RunNow);
            AddQueueButton(row,
                Loc.GetString("administration-ui-events-tab-queue-cancel"),
                queued.Id,
                StationEventQueueCommand.Remove);

            panel.AddChild(row);
            QueueList.AddChild(panel);
        }
    }

    private void PopulateActiveEvents(StationEventsChangedEvent snapshot)
    {
        ActiveList.RemoveAllChildren();
        ActiveStatusLabel.Text = snapshot.ActiveEvents.Count == 0
            ? Loc.GetString("administration-ui-events-tab-active-empty")
            : Loc.GetString("administration-ui-events-tab-active-count", ("count", snapshot.ActiveEvents.Count));

        foreach (var active in snapshot.ActiveEvents)
        {
            var panel = CreatePanel(Color.FromHex("#47292B"));
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(7)
            };
            var details = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            details.AddChild(new Label
            {
                Text = $"{HumanizeId(active.EventId)} ({active.EventId})"
            });

            if (HasValue(active.RemainingSeconds) && HasValue(active.DurationSeconds))
            {
                details.AddChild(new Label
                {
                    Text = Loc.GetString("administration-ui-events-tab-active-remaining",
                        ("remaining", FormatSeconds(active.RemainingSeconds)),
                        ("duration", FormatSeconds(active.DurationSeconds))),
                    ModulateSelfOverride = Color.LightSalmon
                });
                details.AddChild(new ProgressBar
                {
                    HorizontalExpand = true,
                    MaxValue = Math.Max(active.DurationSeconds, 1f),
                    Value = Math.Clamp(active.RemainingSeconds, 0f, Math.Max(active.DurationSeconds, 1f))
                });
            }
            else
            {
                details.AddChild(new Label
                {
                    Text = Loc.GetString("administration-ui-events-tab-active-open",
                        ("elapsed", FormatSeconds(active.ElapsedSeconds))),
                    ModulateSelfOverride = Color.LightSalmon
                });
            }

            var endButton = new Button
            {
                Text = Loc.GetString("administration-ui-events-tab-active-end"),
                Disabled = !_admin.CanCommand("endgamerule")
            };
            endButton.OnPressed += _ =>
            {
                _adminSystem.SendStationEventCommand(
                    StationEventQueueCommand.EndActive,
                    activeEvent: active.Entity);
                RefreshSnapshot();
            };

            row.AddChild(details);
            row.AddChild(endButton);
            panel.AddChild(row);
            ActiveList.AddChild(panel);
        }
    }

    private void AddQueueButton(
        BoxContainer row,
        string text,
        int queueId,
        StationEventQueueCommand command,
        float seconds = -1f)
    {
        var button = new Button
        {
            Text = text,
            Disabled = !_admin.CanCommand("addgamerule")
        };
        button.OnPressed += _ =>
        {
            _adminSystem.SendStationEventCommand(command, queueId: queueId, seconds: seconds);
            RefreshSnapshot();
        };
        row.AddChild(button);
    }

    private static PanelContainer CreatePanel(Color color)
    {
        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = color },
            HorizontalExpand = true
        };
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not StationEventListData row)
            return;

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = row.BackgroundColor },
            HorizontalExpand = true
        };

        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            Margin = new Thickness(8)
        };

        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = 1
        };

        textColumn.AddChild(new Label
        {
            Text = $"{HumanizeId(row.Info.Id)} ({row.Info.Id})",
            FontColorOverride = Color.White
        });

        textColumn.AddChild(new Label
        {
            Text = BuildRuntimeText(row.Info),
            ModulateSelfOverride = Color.LightSteelBlue
        });

        textColumn.AddChild(new Label
        {
            Text = BuildSchedulingText(row.Info),
            ModulateSelfOverride = Color.LightGray
        });

        var runButton = new Button
        {
            Text = Loc.GetString("administration-ui-events-tab-force"),
            Disabled = !_admin.CanCommand("addgamerule")
        };
        runButton.OnPressed += _ => _console.ExecuteCommand($"addgamerule {row.Info.Id}");
        if (runButton.Disabled)
            runButton.ToolTip = Loc.GetString("administration-ui-events-tab-force-disabled");

        var delayInput = new LineEdit
        {
            Text = "5",
            PlaceHolder = Loc.GetString("administration-ui-events-tab-schedule-minutes-placeholder"),
            MinWidth = 48
        };
        var scheduleButton = new Button
        {
            Text = Loc.GetString("administration-ui-events-tab-schedule"),
            Disabled = !_admin.CanCommand("addgamerule") || !_hasScheduler
        };
        scheduleButton.OnPressed += _ =>
        {
            if (!float.TryParse(delayInput.Text, out var minutes))
                return;

            minutes = Math.Clamp(minutes, 0f, 24f * 60f);
            _adminSystem.SendStationEventCommand(
                StationEventQueueCommand.Schedule,
                eventId: row.Info.Id,
                seconds: minutes * 60f);
            RefreshSnapshot();
        };
        if (!_hasScheduler)
            scheduleButton.ToolTip = Loc.GetString("administration-ui-events-tab-schedule-no-scheduler");

        root.AddChild(textColumn);
        root.AddChild(delayInput);
        root.AddChild(scheduleButton);
        root.AddChild(runButton);
        panel.AddChild(root);

        button.AddChild(panel);
        button.StyleClasses.Clear();
        button.ToolTip = row.Info.Id;
    }

    private void PopulateSortOptions()
    {
        SortOptionButton.Clear();
        AddSortOption(EventSortMode.Weight, "administration-ui-events-tab-sort-weight");
        AddSortOption(EventSortMode.State, "administration-ui-events-tab-sort-state");
        AddSortOption(EventSortMode.Duration, "administration-ui-events-tab-sort-duration");
        AddSortOption(EventSortMode.MinimumPlayers, "administration-ui-events-tab-sort-min-players");
        AddSortOption(EventSortMode.EarliestStart, "administration-ui-events-tab-sort-start");
        AddSortOption(EventSortMode.Cooldown, "administration-ui-events-tab-sort-cooldown");
        AddSortOption(EventSortMode.Availability, "administration-ui-events-tab-sort-availability");
        AddSortOption(EventSortMode.Name, "administration-ui-events-tab-sort-name");
        SortOptionButton.SelectId((int) _sortMode);
    }

    private void AddSortOption(EventSortMode mode, string locId)
    {
        SortOptionButton.AddItem(Loc.GetString(locId), (int) mode);
    }

    private void OnSortItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SortOptionButton.SelectId(args.Id);
        _sortMode = (EventSortMode) args.Id;
        Repopulate(_adminSystem.StationEventsSnapshot);
    }

    private void UpdateSortDirectionText()
    {
        SortDirectionButton.Text = Loc.GetString(_sortAscending
            ? "administration-ui-events-tab-sort-ascending"
            : "administration-ui-events-tab-sort-descending");
    }

    private List<StationEventData> SortEvents(List<StationEventData> events)
    {
        IOrderedEnumerable<StationEventData> ordered = _sortMode switch
        {
            EventSortMode.Name => Order(events, ev => HumanizeId(ev.Id).ToLowerInvariant()),
            EventSortMode.State => Order(events, GetStateSortScore),
            EventSortMode.Availability => Order(events, ev => ev.Available ? 1 : 0),
            EventSortMode.Duration => Order(events, GetDurationSortSeconds),
            EventSortMode.MinimumPlayers => Order(events, ev => ev.MinimumPlayers),
            EventSortMode.EarliestStart => Order(events, ev => ev.EarliestStartMinutes),
            EventSortMode.Cooldown => Order(events, ev => ev.ReoccurrenceDelayMinutes),
            _ => Order(events, ev => ev.Weight)
        };

        return ordered
            .ThenBy(ev => HumanizeId(ev.Id).ToLowerInvariant())
            .ToList();
    }

    private IOrderedEnumerable<StationEventData> Order<TKey>(
        IEnumerable<StationEventData> events,
        Func<StationEventData, TKey> selector)
        where TKey : IComparable<TKey>
    {
        return _sortAscending
            ? events.OrderBy(selector)
            : events.OrderByDescending(selector);
    }

    private bool DataFilterCondition(string filter, ListData listData)
    {
        if (listData is not StationEventListData row)
            return false;

        if (AvailableOnlyButton.Pressed && !row.Info.Available)
            return false;

        if (string.IsNullOrWhiteSpace(filter))
            return true;

        return row.FilteringString.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void RefreshSnapshot()
    {
        _refreshAccumulator = 0f;
        _adminSystem.RequestStationEvents();
    }

    private static string BuildFilterString(StationEventData ev)
    {
        return string.Join(" ", new[]
        {
            ev.Id,
            HumanizeId(ev.Id),
            ev.MinimumPlayers.ToString(),
            ev.EarliestStartMinutes.ToString(),
            ev.ReoccurrenceDelayMinutes.ToString(),
            ev.Weight.ToString(),
            ev.ActiveCount.ToString(),
            ev.PendingCount.ToString(),
            FormatSecondsForFilter(ev.DurationSeconds),
            FormatSecondsForFilter(ev.MaxDurationSeconds),
            FormatSecondsForFilter(ev.MinRemainingSeconds),
            FormatSecondsForFilter(ev.MaxRemainingSeconds),
            ev.Available ? "available activo" : "unavailable inactivo"
        });
    }

    private static string BuildSchedulingText(StationEventData info)
    {
        var meta = new StringBuilder();
        meta.Append(info.Available
            ? Loc.GetString("administration-ui-events-tab-status-available")
            : Loc.GetString("administration-ui-events-tab-status-unavailable"));
        meta.Append(" | ");
        meta.Append(Loc.GetString(
            "administration-ui-events-tab-meta",
            ("players", info.MinimumPlayers),
            ("start", info.EarliestStartMinutes),
            ("cooldown", info.ReoccurrenceDelayMinutes),
            ("weight", info.Weight)));
        return meta.ToString();
    }

    private static string BuildRuntimeText(StationEventData info)
    {
        var parts = new List<string>();

        if (info.ActiveCount > 0)
            parts.Add(Loc.GetString("administration-ui-events-tab-runtime-active", ("count", info.ActiveCount)));
        else if (info.PendingCount > 0)
            parts.Add(Loc.GetString("administration-ui-events-tab-runtime-pending", ("count", info.PendingCount)));
        else
            parts.Add(Loc.GetString("administration-ui-events-tab-runtime-idle"));

        if (info.ActiveCount > 0 && HasValue(info.MinRemainingSeconds))
        {
            parts.Add(info.ActiveCount > 1 && HasValue(info.MaxRemainingSeconds) &&
                      Math.Abs(info.MaxRemainingSeconds - info.MinRemainingSeconds) > 0.5f
                ? Loc.GetString("administration-ui-events-tab-runtime-remaining-range",
                    ("min", FormatSeconds(info.MinRemainingSeconds)),
                    ("max", FormatSeconds(info.MaxRemainingSeconds)))
                : Loc.GetString("administration-ui-events-tab-runtime-remaining",
                    ("time", FormatSeconds(info.MaxRemainingSeconds))));
        }

        if (info.PendingCount > 0 && HasValue(info.NextStartSeconds))
        {
            parts.Add(Loc.GetString("administration-ui-events-tab-runtime-next-start",
                ("time", FormatSeconds(info.NextStartSeconds))));
        }

        parts.Add(Loc.GetString("administration-ui-events-tab-runtime-duration",
            ("duration", BuildDurationValue(info))));

        return string.Join(" | ", parts);
    }

    private static string BuildDurationValue(StationEventData info)
    {
        if (!HasValue(info.DurationSeconds))
            return Loc.GetString("administration-ui-events-tab-duration-open");

        if (HasValue(info.MaxDurationSeconds) && Math.Abs(info.MaxDurationSeconds - info.DurationSeconds) > 0.5f)
        {
            return Loc.GetString("administration-ui-events-tab-duration-range",
                ("min", FormatSeconds(info.DurationSeconds)),
                ("max", FormatSeconds(info.MaxDurationSeconds)));
        }

        return FormatSeconds(info.MaxDurationSeconds);
    }

    private static int GetStateSortScore(StationEventData ev)
    {
        if (ev.ActiveCount > 0)
            return 3;
        if (ev.PendingCount > 0)
            return 2;
        return ev.Available ? 1 : 0;
    }

    private static float GetDurationSortSeconds(StationEventData ev)
    {
        if (HasValue(ev.MaxDurationSeconds))
            return ev.MaxDurationSeconds;
        if (HasValue(ev.DurationSeconds))
            return ev.DurationSeconds;
        return -1f;
    }

    private static bool HasValue(float seconds)
    {
        return seconds >= 0f;
    }

    private static string FormatSeconds(float seconds)
    {
        var clamped = Math.Max((int) Math.Ceiling(seconds), 0);
        var span = TimeSpan.FromSeconds(clamped);

        if (span.TotalHours >= 1)
            return $"{(int) span.TotalHours}:{span.Minutes:D2}:{span.Seconds:D2}";

        return $"{(int) span.TotalMinutes}:{span.Seconds:D2}";
    }

    private static string FormatSecondsForFilter(float seconds)
    {
        return HasValue(seconds) ? seconds.ToString("F0") : string.Empty;
    }

    private static string HumanizeId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return id;

        var builder = new StringBuilder(id.Length + 8);
        for (var i = 0; i < id.Length; i++)
        {
            var current = id[i];
            if (i > 0 && char.IsUpper(current) && !char.IsUpper(id[i - 1]))
                builder.Append(' ');

            builder.Append(current == '_' ? ' ' : current);
        }

        return builder.ToString().Trim();
    }
}

public sealed record StationEventListData(StationEventData Info, Color BackgroundColor, string FilteringString) : ListData;
