#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack # Wizard backpack?
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltWizard #Starlight
    belt: ClothingBeltWand
    pocket1: WizardTeleportScroll
    pocket2: WizardsGrimoire

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet

- type: chameleonOutfit
  id: WizardChameleonOutfit
  name: roles-antag-wizard-name
  startingGear: WizardBlueGear
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLGBTPin
    gloves: ClothingHandsGlovesColorBlack

# Archmage outfit startingGear definitions. Is it worth having separate red/blue gear for archmages? New file as well?

- type: startingGear
  id: ArchmageGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltWizard
    belt: ClothingBeltWand
    pocket1: WizardTeleportScroll
    pocket2: ArchmageGrimoire
    neck: ClothingNeckScarfWizardRed # Should be overridden based on faction

- type: startingGear
  id: ArchmageGearRed
  parent: ArchmageGear
  equipment:
    neck: ClothingNeckScarfWizardRed

- type: startingGear
  id: ArchmageGearBlue
  parent: ArchmageGear
  equipment:
    neck: ClothingNeckScarfWizardBlue

- type: startingGear
  id: ApprenticeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorLightBlue
    head: ClothingHeadHatWizard # Use existing wizard hat
    back: ClothingBackpack
    outerClothing: ClothingOuterWizard # Use existing wizard robe
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltWizard
    belt: ClothingBeltWand # Use existing wand belt
    pocket1: WizardTeleportScroll
    neck: ClothingNeckScarfWizardRed # Will be overridden based on faction
