using System.Numerics;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Starlight.Achievement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Achievement;

[GenerateTypedNameReferences]
public sealed partial class AchievementWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystems = default!;

    public AchievementWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(IPrototypeManager protoManager, IClientAchievementManager achievements)
    {
        AchievementList.RemoveAllChildren();
        var spriteSystem = _entitySystems.GetEntitySystem<SpriteSystem>();
        var visibleAchievements = protoManager.EnumeratePrototypes<AchievementPrototype>()
            .Where(proto => !proto.Hidden || achievements.IsUnlocked(proto.ID))
            .ToList();

        for (var i = 0; i < visibleAchievements.Count; i++)
        {
            var proto = visibleAchievements[i];
            var unlocked = achievements.IsUnlocked(proto.ID);

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };

            if (proto.Icon != null)
            {
                var texture = spriteSystem.Frame0(proto.Icon);
                var iconRect = new TextureRect
                {
                    Texture = texture,
                    MinSize = new Vector2(64, 64),
                    MaxSize = new Vector2(64, 64),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    Modulate = unlocked ? Color.White : Color.LightGray
                };
                row.AddChild(iconRect);
            }
            // else
            // {
            //     var statusLabel = new Label
            //     {
            //         Text = unlocked ? "V" : "X",
            //         MinWidth = 32,
            //     };
            //     row.AddChild(statusLabel);
            // }

            var infoBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            var nameLabel = new Label
            {
                Text = Loc.GetString(proto.Name),
                FontColorOverride = unlocked ? Color.FromHex("#55FF55") : Color.FromHex("#AAAAAA"),
            };
            infoBox.AddChild(nameLabel);

            var descLabel = new RichTextLabel();
            descLabel.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString(proto.Description)));
            infoBox.AddChild(descLabel);

            if (proto.ShowProgress && proto.Requirements.Count > 0 && !unlocked)
            {
                foreach (var req in proto.Requirements)
                {
                    var current = achievements.GetProgress(req.ProgressType);
                    var progressLabel = new Label
                    {
                        Text = $"  {current:F0} / {req.RequiredProgress:F0}",
                        FontColorOverride = Color.FromHex("#888888"),
                    };
                    infoBox.AddChild(progressLabel);
                }
            }

            row.AddChild(infoBox);
            AchievementList.AddChild(row);

            if (i < visibleAchievements.Count - 1)
                AchievementList.AddChild(new HSeparator());
        }
    }
}
