using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.CartridgeLoader.Cartridges;

namespace Content.Client.CartridgeLoader.Cartridges;

/// <summary>
///     Starlight - Tidr: read-only job details shown to crew who don't own the task
///     (Tiders and bystanders), instead of the editable form only the poster should see.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoTaskDetailsPopup : DefaultWindow
{
    public NanoTaskDetailsPopup()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void SetTask(NanoTaskItem task)
    {
        DescriptionLabel.Text = task.Description;
        RequesterLabel.Text = task.TaskIsFor;
        LocationLabel.Text = string.IsNullOrWhiteSpace(task.Location)
            ? Loc.GetString("tidr-details-none")
            : task.Location;
        RewardLabel.Text = Loc.GetString("tidr-details-reward-value", ("amount", task.Reward));
        StatusLabel.Text = string.IsNullOrEmpty(task.AcceptedBy)
            ? Loc.GetString("tidr-details-unclaimed")
            : Loc.GetString("tidr-taken-by", ("name", task.AcceptedBy));
    }
}
