using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared.CartridgeLoader.Cartridges;

namespace Content.Client.CartridgeLoader.Cartridges;

/// <summary>
///     Popup displayed to create or edit a Tidr task
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoTaskItemPopup : DefaultWindow
{
    private readonly ButtonGroup _priorityGroup = new();
    private int? _editingTaskId = null;
    private NanoTaskItem? _editingItem = null; // Starlight - Tidr: preserve server-controlled fields on edit

    public Action<int, NanoTaskItem>? TaskSaved;
    public Action<int>? TaskDeleted;
    public Action<NanoTaskItem>? TaskCreated;
    public Action<NanoTaskItem>? TaskPrinted;

    private NanoTaskItem MakeItem()
    {
        return new(
            description: DescriptionInput.Text,
            // Starlight - Tidr: name is stamped server-side from the poster's ID on create; preserved on edit
            taskIsFor: _editingItem?.TaskIsFor ?? "",
            isTaskDone: _editingItem?.IsTaskDone ?? false,
            priority: _priorityGroup.Pressed switch {
                var item when item == LowButton => NanoTaskPriority.Low,
                var item when item == MediumButton => NanoTaskPriority.Medium,
                var item when item == HighButton => NanoTaskPriority.High,
                _ => NanoTaskPriority.Medium,
            },
            location: LocationInput.Text,
            // Starlight - Tidr: reward is escrowed at post time and immutable after; on edit the
            // server keeps its own value regardless, this just keeps the client honest
            reward: _editingItem is not null
                ? _editingItem.Reward
                : (int.TryParse(RewardInput.Text, out var r) && r > 0 ? r : 0),
            acceptedBy: _editingItem?.AcceptedBy
        );
    }

    public NanoTaskItemPopup()
    {
        RobustXamlLoader.Load(this);

        LowButton.Group = _priorityGroup;
        MediumButton.Group = _priorityGroup;
        HighButton.Group = _priorityGroup;

        CancelButton.OnPressed += _ => Close();
        DeleteButton.OnPressed += _ =>
        {
            if (_editingTaskId is int id)
            {
                TaskDeleted?.Invoke(id);
            }
        };
        PrintButton.OnPressed += _ =>
        {
            TaskPrinted?.Invoke(MakeItem());
        };
        SaveButton.OnPressed += _ =>
        {
            if (_editingTaskId is int id)
            {
                TaskSaved?.Invoke(id, MakeItem());
            }
            else
            {
                TaskCreated?.Invoke(MakeItem());
            }
        };

        DescriptionInput.OnTextChanged += args =>
        {
            if (args.Text.Length > NanoTaskItem.MaximumStringLength)
                DescriptionInput.Text = args.Text[..NanoTaskItem.MaximumStringLength];
        };
        LocationInput.OnTextChanged += args =>
        {
            if (args.Text.Length > NanoTaskItem.MaximumStringLength)
                LocationInput.Text = args.Text[..NanoTaskItem.MaximumStringLength];
        };
        RewardInput.OnTextChanged += args =>
        {
            // Starlight - Tidr: digits only
            var filtered = new string(args.Text.Where(char.IsDigit).ToArray());
            if (filtered != args.Text)
                RewardInput.Text = filtered;
        };
    }

    public void SetEditingTaskId(int? id)
    {
        _editingTaskId = id;
        DeleteButton.Visible = id is not null;
    }

    public void ResetInputs(NanoTaskItem? item)
    {
        _editingItem = item; // Starlight - Tidr
        if (item is NanoTaskItem task)
        {
            var button = task.Priority switch
            {
                NanoTaskPriority.High => HighButton,
                NanoTaskPriority.Medium => MediumButton,
                NanoTaskPriority.Low => LowButton,
                _ => throw new ArgumentException("Invalid priority"),
            };
            button.Pressed = true;
            DescriptionInput.Text = task.Description;
            LocationInput.Text = task.Location;
            RewardInput.Text = task.Reward > 0 ? task.Reward.ToString() : "";
            RewardInput.Editable = false; // Starlight - Tidr: escrow is locked once posted
        }
        else
        {
            MediumButton.Pressed = true;
            DescriptionInput.Text = "";
            LocationInput.Text = "";
            RewardInput.Text = "";
            RewardInput.Editable = true;
        }
    }
}
