using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Shared.CartridgeLoader.Cartridges;

namespace Content.Client.CartridgeLoader.Cartridges;

/// <summary>
///     Represents a single control for a single Tidr task
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoTaskItemControl : Control
{
    public Action<int>? OnMainPressed;
    public Action<int>? OnDonePressed;
    public Action<int>? OnAcceptPressed; // Starlight - Tidr

    public NanoTaskItemControl(NanoTaskViewerEntry entry) // Starlight - Tidr: entry carries viewer flags
    {
        RobustXamlLoader.Load(this);

        var data = entry.Task.Data;
        var id = entry.Task.Id;

        TaskLabel.Text = data.Description;
        TaskLabel.FontColorOverride = Color.White;

        // Starlight - Tidr: requester name (auto-stamped) + location + reward + who took it
        var accepted = !string.IsNullOrEmpty(data.AcceptedBy);
        var sub = data.TaskIsFor;
        if (!string.IsNullOrWhiteSpace(data.Location))
            sub += $" - {data.Location}";
        if (data.Reward > 0)
            sub += $"  ({data.Reward} cr)";
        if (accepted)
            sub += $"  •  {Loc.GetString("tidr-taken-by", ("name", data.AcceptedBy!))}";
        TaskForLabel.Text = sub;

        MainButton.OnPressed += _ => OnMainPressed?.Invoke(id);
        DoneButton.OnPressed += _ => OnDonePressed?.Invoke(id);
        AcceptButton.OnPressed += _ => OnAcceptPressed?.Invoke(id);

        if (data.IsTaskDone)
        {
            // Starlight - Tidr: completed rows are receipts. Open still works (details for
            // crew, delete access for the owner); accept/complete are gone.
            AcceptButton.Visible = false;
            DoneButton.Visible = false;
            TaskLabel.FontColorOverride = Color.Gray;
            return;
        }

        // Starlight - Tidr: Accept / Unaccept / Release / locked Taken
        if (!accepted)
        {
            AcceptButton.Text = Loc.GetString("tidr-accept");
            AcceptButton.Disabled = false;
            AcceptButton.ToolTip = null;
        }
        else if (entry.ViewerIsAccepter)
        {
            AcceptButton.Text = Loc.GetString("tidr-unaccept");
            AcceptButton.Disabled = false;
            AcceptButton.ToolTip = Loc.GetString("tidr-unaccept-hint");
        }
        else if (entry.ViewerIsOwner)
        {
            AcceptButton.Text = Loc.GetString("tidr-taken");
            AcceptButton.Disabled = false;
            AcceptButton.ToolTip = Loc.GetString("tidr-release-hint", ("name", data.AcceptedBy!));
        }
        else
        {
            AcceptButton.Text = Loc.GetString("tidr-taken");
            AcceptButton.Disabled = true;
            AcceptButton.ToolTip = Loc.GetString("tidr-taken-by", ("name", data.AcceptedBy!));
        }

        // Starlight - Tidr: Complete is the requester's button; money moves when they press it
        DoneButton.Text = Loc.GetString("tidr-complete");
        DoneButton.Visible = entry.ViewerIsOwner;
        DoneButton.ToolTip = data.Reward > 0 ? Loc.GetString("tidr-complete-hint", ("amount", data.Reward)) : null;
    }
}
