using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Shared.CartridgeLoader.Cartridges;

namespace Content.Client.CartridgeLoader.Cartridges;

/// <summary>
///     Represents a single control for a single NanoTask item
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoTaskItemControl : Control
{
    public Action<int>? OnMainPressed;
    public Action<int>? OnDonePressed;

    public NanoTaskItemControl(NanoTaskItemAndId item)
    {
        RobustXamlLoader.Load(this);

        TaskLabel.Text = item.Data.Description;
        TaskLabel.FontColorOverride = Color.White;

        // Starlight - Tidr: requester name (auto-stamped) + location + reward
        var sub = item.Data.TaskIsFor;
        if (!string.IsNullOrWhiteSpace(item.Data.Location))
            sub += $" - {item.Data.Location}";
        if (item.Data.Reward > 0)
            sub += $"  ({item.Data.Reward} cr)";
        TaskForLabel.Text = sub;

        MainButton.OnPressed += _ => OnMainPressed?.Invoke(item.Id);
        DoneButton.OnPressed += _ => OnDonePressed?.Invoke(item.Id);

        MainButton.Disabled = item.Data.IsTaskDone;
        // Starlight - Tidr: "Complete" / "Undo" wording
        DoneButton.Text = item.Data.IsTaskDone ? Loc.GetString("tidr-revert") : Loc.GetString("tidr-complete");
    }
}
