using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.UniversalSpawner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._Starlight.UniversalSpawner;

[GenerateTypedNameReferences]
public sealed partial class UniversalSpawnerWindow : FancyWindow
{
    private IPrototypeManager _prototypeManager = default!;

    public event Action<List<SpawnEntry>>? OnEntriesChanged;
    public event Action<int, float, bool, float, int, int, int, SpawnerTriggerType, float, string?, float>? OnSettingsChanged;
    public event Action? OnTriggerSpawn;
    public event Action? OnReset;

    private List<SpawnEntry> _currentEntries = new();
    private List<string> _availableHolidays = new();
    private readonly List<string> _availableGameRules = new();
    private readonly Dictionary<int, FloatSpinBox> _weightBoxes = new();
    private readonly Dictionary<int, SpinBox> _quantityBoxes = new();
    private readonly Dictionary<int, CheckBox> _allowMultipleBoxes = new();
    private readonly Dictionary<int, FloatSpinBox> _offsetBoxes = new();
    private readonly Dictionary<int, RichTextLabel> _validationLabels = new();
    private SpawnerTriggerType _selectedTriggerType = SpawnerTriggerType.None;
    private int _selectedGameRuleIndex = -1;

    public UniversalSpawnerWindow()
    {
        RobustXamlLoader.Load(this);

        // Button events
        AddEntryButton.OnPressed += _ => AddNewEntry();
        ApplyButton.OnPressed += _ => ApplyChanges();
        TriggerButton.OnPressed += _ => OnTriggerSpawn?.Invoke();
        ResetButton.OnPressed += _ => OnReset?.Invoke();

        // Batch operation buttons
        ClearAllButton.OnPressed += _ => ClearAllEntries();
        EnableAllButton.OnPressed += _ => SetAllEntriesEnabled(true);
        DisableAllButton.OnPressed += _ => SetAllEntriesEnabled(false);

        // Settings change events
        MinSpawnsBox.ValueChanged += _ => OnSettingsModified();
        MaxSpawnsBox.ValueChanged += _ => OnSettingsModified();
        MinRollsBox.ValueChanged += _ => OnSettingsModified();
        MaxRollsBox.ValueChanged += _ => OnSettingsModified();
        DeleteCheckBox.OnToggled += _ => OnSettingsModified();
        
        // Populate trigger type dropdown
        TriggerTypeDropdown.Clear();
        TriggerTypeDropdown.AddItem(Loc.GetString("universal-spawner-trigger-none"), (int)SpawnerTriggerType.None);
        TriggerTypeDropdown.AddItem(Loc.GetString("universal-spawner-trigger-mapinit"), (int)SpawnerTriggerType.MapInit);
        TriggerTypeDropdown.AddItem(Loc.GetString("universal-spawner-trigger-time"), (int)SpawnerTriggerType.TimeIntoRound);
        TriggerTypeDropdown.AddItem(Loc.GetString("universal-spawner-trigger-gamerule"), (int)SpawnerTriggerType.Gamerule);
        TriggerTypeDropdown.AddItem(Loc.GetString("universal-spawner-trigger-proximity"), (int)SpawnerTriggerType.Proximity);
        TriggerTypeDropdown.OnItemSelected += OnTriggerTypeChanged;
    }

    public void Initialize(IPrototypeManager prototypeManager) =>
        _prototypeManager = prototypeManager;

    public void UpdateState(UniversalSpawnerBoundUserInterfaceState state)
    {
        _currentEntries = new List<SpawnEntry>(state.Entries);
        _availableHolidays = state.AvailableHolidays;
        _availableGameRules.Clear();
        _availableGameRules.AddRange(state.AvailableGameRules);

        // Update settings
        MinSpawnsBox.Value = state.MinSpawns;
        MaxSpawnsBox.Value = state.MaxSpawns;
        MinRollsBox.Value = state.MinRolls;
        MaxRollsBox.Value = state.MaxRolls;
        OffsetBox.Value = state.Offset;
        SpawnChanceBox.Value = state.SpawnChance;
        DeleteCheckBox.Pressed = state.DeleteAfterSpawn;
        
        // Set trigger type and update tracked value
        _selectedTriggerType = state.TriggerType;
        if (TriggerTypeDropdown.ItemCount > 0)
        {
            TriggerTypeDropdown.SelectId((int)state.TriggerType);
            var idx = TriggerTypeDropdown.GetIdx((int)state.TriggerType);
            if (idx >= 0)
                TriggerTypeDropdown.Select(idx);
        }
        TriggerTimeBox.Value = state.TriggerTimeSeconds;
        TriggerProximityBox.Value = state.ProximityRange;
        
        // Populate gamerule dropdown
        TriggerGameRuleDropdown.Clear();
        TriggerGameRuleDropdown.OnItemSelected += args => _selectedGameRuleIndex = args.Id;
        foreach (var gamerule in _availableGameRules)
        {
            TriggerGameRuleDropdown.AddItem(gamerule);
        }
        
        // Select current gamerule if set
        if (!string.IsNullOrEmpty(state.TriggerGameRule))
        {
            var index = _availableGameRules.IndexOf(state.TriggerGameRule);
            if (index >= 0)
            {
                _selectedGameRuleIndex = index;
                TriggerGameRuleDropdown.SelectId(index);
            }
        }
        
        UpdateTriggerVisibility();

        // Update status
        StatusLabel.Text = state.HasSpawned ? 
            Loc.GetString("universal-spawner-status-spawned") : 
            Loc.GetString("universal-spawner-status-ready");

        RebuildEntriesUI();
        UpdateEntryCount();
    }

    private void OnTriggerTypeChanged(OptionButton.ItemSelectedEventArgs args)
    {
        _selectedTriggerType = (SpawnerTriggerType)args.Id;
        UpdateTriggerVisibility();
        OnSettingsModified();
    }

    private void UpdateTriggerVisibility()
    {
        TriggerTimeRow.Visible = (_selectedTriggerType == SpawnerTriggerType.TimeIntoRound);
        TriggerGameRuleRow.Visible = (_selectedTriggerType == SpawnerTriggerType.Gamerule);
        TriggerProximityRow.Visible = (_selectedTriggerType == SpawnerTriggerType.Proximity);
    }

    private void OnSettingsModified()
    {
    }

    private void ApplyChanges()
    {
        var triggerType = _selectedTriggerType;
        var triggerTimeSeconds = (float)TriggerTimeBox.Value;
        var proximityRange = (float)TriggerProximityBox.Value;
        string? triggerGameRule = null;
        
        if (triggerType == SpawnerTriggerType.Gamerule && _selectedGameRuleIndex >= 0 && _selectedGameRuleIndex < _availableGameRules.Count)
            triggerGameRule = _availableGameRules[_selectedGameRuleIndex];
        OnSettingsChanged?.Invoke(
            (int)MaxSpawnsBox.Value,
            (float)OffsetBox.Value,
            DeleteCheckBox.Pressed,
            (float)SpawnChanceBox.Value,
            (int)MinSpawnsBox.Value,
            (int)MinRollsBox.Value,
            (int)MaxRollsBox.Value,
            triggerType,
            triggerTimeSeconds,
            triggerGameRule,
            proximityRange
        );

        // Send entries update
        OnEntriesChanged?.Invoke(new List<SpawnEntry>(_currentEntries));
        var enabledCount = _currentEntries.Count(e => e.Enabled);
        if (enabledCount == 0)
        {
            ValidationLabel.Text = Loc.GetString("universal-spawner-validation-warn");
        }
        else
        {
            ValidationLabel.Text = $"✓ Saved: {enabledCount} rolls enabled";
        }
    }

    private void AddNewEntry()
    {
        var newEntry = new SpawnEntry
        {
            PrototypeId = "",
            Weight = 1.0f,
            Quantity = 1,
            AllowMultiple = false,
            Holiday = null,
            Enabled = true
        };

        _currentEntries.Add(newEntry);
        _weightBoxes.Clear();
        _quantityBoxes.Clear();
        _allowMultipleBoxes.Clear();
        _offsetBoxes.Clear();
        _validationLabels.Clear();
        RebuildEntriesUI();
        UpdateEntryCount();
    }

    private void RebuildEntriesUI()
    {
        EntriesContainer.RemoveAllChildren();
        _weightBoxes.Clear();
        _quantityBoxes.Clear();
        _allowMultipleBoxes.Clear();
        _offsetBoxes.Clear();
        _validationLabels.Clear();

        for (var i = 0; i < _currentEntries.Count; i++)
        {
            AddEntryControl(_currentEntries[i], i);
        }

        UpdateEntryCount();
    }

    private void AddEntryControl(SpawnEntry entry, int index)
    {
        var container = new PanelContainer
        {
            StyleClasses = { "AngleRect" },
            Margin = new Thickness(0, 0, 0, 5)
        };

        var innerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8)
        };

        // Header row with enable checkbox and delete button
        var headerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 5)
        };

        var enabledCheck = new CheckBox
        {
            Pressed = entry.Enabled
        };
        enabledCheck.OnToggled += args => entry.Enabled = args.Pressed;

        var entryLabel = new Label
        {
            Text = Loc.GetString("universal-spawner-entry-label", ("index", index + 1)),
            HorizontalExpand = true,
            VAlign = Label.VAlignMode.Center
        };

        var duplicateButton = new Button
        {
            Text = Loc.GetString("universal-spawner-duplicate-entry-button"),
            MinWidth = 90,
            Margin = new Thickness(0, 0, 5, 0)
        };
        duplicateButton.OnPressed += _ =>
        {
            var copy = new SpawnEntry
            {
                PrototypeId = entry.PrototypeId,
                Weight = entry.Weight,
                Quantity = entry.Quantity,
                AllowMultiple = entry.AllowMultiple,
                Holiday = entry.Holiday,
                Enabled = entry.Enabled
            };
            _currentEntries.Insert(index + 1, copy);
            RebuildEntriesUI();
        };

        var deleteButton = new Button
        {
            Text = Loc.GetString("universal-spawner-delete-entry-button"),
            MinWidth = 80,
            StyleClasses = { "ButtonColorRed" }
        };
        deleteButton.OnPressed += _ =>
        {
            _currentEntries.RemoveAt(index);
            RebuildEntriesUI();
        };

        headerRow.AddChild(enabledCheck);
        headerRow.AddChild(entryLabel);
        headerRow.AddChild(duplicateButton);
        headerRow.AddChild(deleteButton);

        var grid = new GridContainer
        {
            Columns = 2
        };

        // Prototype ID
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-prototype-label"),
            VAlign = Label.VAlignMode.Top,
            MinWidth = 120
        });

        var protoBox = new LineEdit
        {
            Text = entry.PrototypeId,
            HorizontalExpand = true,
            PlaceHolder = Loc.GetString("universal-spawner-prototype-placeholder")
        };
        
        var protoContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };
        protoContainer.AddChild(protoBox);
        
        var validationLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 0)
        };
        protoContainer.AddChild(validationLabel);
        _validationLabels[index] = validationLabel;
        
        protoBox.OnTextChanged += args =>
        {
            entry.PrototypeId = args.Text;
            UpdatePrototypeValidation(index, args.Text);
        };
        UpdatePrototypeValidation(index, entry.PrototypeId);
        grid.AddChild(protoContainer);
        // Weight
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-weight-label"),
            VAlign = Label.VAlignMode.Center
        });

        var weightBox = new FloatSpinBox
        {
            Value = entry.Weight,
            MinWidth = 150,
            HorizontalExpand = false
        };
        weightBox.OnValueChanged += _ => entry.Weight = (float)weightBox.Value;
        _weightBoxes[index] = weightBox;
        
        var weightContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        weightContainer.AddChild(weightBox);
        weightContainer.AddChild(new Control { HorizontalExpand = true });
        grid.AddChild(weightContainer);

        // Quantity
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-quantity-label"),
            VAlign = Label.VAlignMode.Center,
            ToolTip = Loc.GetString("universal-spawner-quantity-tooltip")
        });

        var quantityBox = new SpinBox
        {
            Value = entry.Quantity,
            MinWidth = 150,
            HorizontalExpand = false
        };
        quantityBox.ValueChanged += _ => entry.Quantity = (int)quantityBox.Value;
        _quantityBoxes[index] = quantityBox;
        
        var quantityContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        quantityContainer.AddChild(quantityBox);
        quantityContainer.AddChild(new Control { HorizontalExpand = true });
        grid.AddChild(quantityContainer);

        // Allow Multiple
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-allow-multiple-label"),
            VAlign = Label.VAlignMode.Center,
            ToolTip = Loc.GetString("universal-spawner-allow-multiple-tooltip")
        });

        var allowMultipleBox = new CheckBox
        {
            Pressed = entry.AllowMultiple
        };
        allowMultipleBox.OnToggled += args => entry.AllowMultiple = args.Pressed;
        _allowMultipleBoxes[index] = allowMultipleBox;
        
        var allowMultipleContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        allowMultipleContainer.AddChild(allowMultipleBox);
        allowMultipleContainer.AddChild(new Control { HorizontalExpand = true });
        grid.AddChild(allowMultipleContainer);

        // Entry Offset
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-entry-offset-label"),
            VAlign = Label.VAlignMode.Center,
            ToolTip = Loc.GetString("universal-spawner-entry-offset-tooltip")
        });

        var offsetBox = new FloatSpinBox
        {
            Value = entry.Offset,
            MinWidth = 150,
            HorizontalExpand = false
        };
        offsetBox.OnValueChanged += _ => entry.Offset = (float)offsetBox.Value;
        _offsetBoxes[index] = offsetBox;
        
        var offsetContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        offsetContainer.AddChild(offsetBox);
        offsetContainer.AddChild(new Control { HorizontalExpand = true });
        grid.AddChild(offsetContainer);

        // Holiday
        grid.AddChild(new Label
        {
            Text = Loc.GetString("universal-spawner-holiday-label"),
            VAlign = Label.VAlignMode.Center
        });

        var holidayButton = new OptionButton
        {
            MinWidth = 200,
            HorizontalExpand = false
        };
        // holiday options
        holidayButton.AddItem(Loc.GetString("universal-spawner-no-holiday"), 0);
        holidayButton.AddItem(Loc.GetString("universal-spawner-any-holiday"), 1);
        var holidayOffset = 2;
        for (var i = 0; i < _availableHolidays.Count; i++)
        {
            var holiday = _availableHolidays[i];
            if (string.IsNullOrEmpty(holiday))
                continue;
            holidayButton.AddItem(holiday, i + holidayOffset);
        }

        if (string.IsNullOrEmpty(entry.Holiday))
        {
            holidayButton.SelectId(0); // No Holiday
            holidayButton.Select(0);
        }
        else if (entry.Holiday == "*")
        {
            holidayButton.SelectId(1); // Any Holiday
            holidayButton.Select(1);
        }
        else
        {
            var idx = _availableHolidays.IndexOf(entry.Holiday);
            if (idx >= 0)
            {
                holidayButton.SelectId(idx + holidayOffset);
                var displayIdx = holidayButton.GetIdx(idx + holidayOffset);
                if (displayIdx >= 0)
                    holidayButton.Select(displayIdx);
            }
        }

        holidayButton.OnItemSelected += args =>
        {
            if (args.Id == 0)
                entry.Holiday = null;
            else if (args.Id == 1)
                entry.Holiday = "*";
            else
            {
                var holidayIndex = args.Id - holidayOffset;
                if (holidayIndex < _availableHolidays.Count)
                    entry.Holiday = _availableHolidays[holidayIndex];
            }
        };

        var holidayContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        holidayContainer.AddChild(holidayButton);
        holidayContainer.AddChild(new Control { HorizontalExpand = true });
        grid.AddChild(holidayContainer);

        innerBox.AddChild(headerRow);
        innerBox.AddChild(grid);
        container.AddChild(innerBox);
        EntriesContainer.AddChild(container);
    }

    private void UpdatePrototypeValidation(int index, string prototypeId)
    {
        if (!_validationLabels.TryGetValue(index, out var label))
            return;

        if (string.IsNullOrWhiteSpace(prototypeId))
        {
            label.SetMessage(new FormattedMessage());
            return;
        }

        // Split by comma to support multiple entities per entry
        var prototypeIds = prototypeId.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        
        var message = new FormattedMessage();
        for (var i = 0; i < prototypeIds.Length; i++)
        {
            var id = prototypeIds[i];
            var isValid = _prototypeManager.HasIndex<EntityPrototype>(id);
            
            if (i > 0)
                message.AddText(", ");
                
            message.PushColor(isValid ? Color.LightGreen : Color.LightCoral);
            message.AddText(id);
            message.Pop();
        }
        
        label.SetMessage(message);
    }

    private void UpdateEntryCount()
    {
        EntryCountLabel.Text = _currentEntries.Count.ToString();
        var enabled = _currentEntries.Where(e => e.Enabled).Count();
        ValidationLabel.Text = enabled > 0 
            ? Loc.GetString("universal-spawner-validation-ok", ("count", enabled))
            : Loc.GetString("universal-spawner-validation-warn");
    }

    private void ClearAllEntries()
    {
        _currentEntries.Clear();
        _weightBoxes.Clear();
        RebuildEntriesUI();
    }

    private void SetAllEntriesEnabled(bool enabled)
    {
        foreach (var entry in _currentEntries)
        {
            entry.Enabled = enabled;
        }
        RebuildEntriesUI();
    }
}
