
- type: entity
  name: handheld station radio box
  parent: BoxCardboard
  id: BoxRadioHandheldStation
  description: A box full of handheld station radios. Handed out at the radio host's discretion.
  components:
    - type: EntityTableContainerFill
      containers:
        storagebase:
          id: RadioHandheldStation
          amount: 9
    - type: Sprite
      layers:
        - state: box
        - state: vials