using Content.Client.Message;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationDisplay : Control
{
    private Color BenefitColor = Color.FromHex("#3d000a");
    private Color BenefitUnavailableColor = Color.FromHex("#2a0c11");

    private Color DisadvantageColor = Color.FromHex("#032b01");
    private Color DisadvantageUnavailableColor = Color.FromHex("#010f00");

    public DevilDamnationDisplay((DamnationPrototype, int) damnationMeta)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var damnation = damnationMeta.Item1;
        var uses = damnationMeta.Item2;

        var damnationTitle = Loc.GetString("devil-damnations-ui-damnation-name", ("name", damnation.Name));
        var damnationCost = Loc.GetString("devil-damnations-ui-cost", ("cost", damnation.Cost), ("uses", uses), ("maxuses", damnation.MaxUses == -1 ? "infinite" : damnation.MaxUses));
        var damnationDescription = damnation.Description;
        var damnationBackgroundColor = (damnation.MaxUses > uses || damnation.MaxUses == -1) ?
            ((damnation.Cost >= 0) ? DisadvantageColor : BenefitColor) :
            ((damnation.Cost >= 0) ? DisadvantageUnavailableColor : BenefitUnavailableColor);

        DamnationTitle.Title = damnationTitle;
        DamnationCost.SetMarkup(damnationCost);
        DamnationDescription.SetMarkup(damnationDescription);
        DamnationPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = damnationBackgroundColor };
    }
}
