using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationsMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public DevilDamnationsMenu(EntityUid devil)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!_entityManager.TryGetComponent<DevilComponent>(devil, out var devilComponent)) return;

        foreach (var damnation in devilComponent.AvailableDamnations)
        {
            var element = new DevilDamnationDisplay(damnation);
            DamnationsDisplayContainer.AddChild(element);
        }
    }
}