using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationsMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public DevilDamnationsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(DevilDamnationsBuiState state)
    {
        DamnationsDisplayContainer.Children.Clear();
        foreach (var damnation in state.Damnations)
        {
            var element = new DevilDamnationDisplay(damnation);
            DamnationsDisplayContainer.AddChild(element);
        }
    }
}