using Content.Client.Message;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationDisplay : Control
{
    private Color BenefitColor = Color.FromHex("#3d000a");
    private Color DisadvantageColour = Color.FromHex("#032b01");

    public DevilDamnationDisplay(DamnationPrototype damnation)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var damnationTitle = Loc.GetString("devil-damnations-ui-damnation-name", ("name", damnation.Name));
        var damnationCost = Loc.GetString("devil-damnations-ui-cost", ("cost", damnation.Cost));
        var damnationDescription = damnation.Description;
        var damnationBackgroundColor = damnation.Cost >= 0 ? DisadvantageColour : BenefitColor;

        DamnationTitle.Title = damnationTitle;
        DamnationCost.SetMarkup(damnationCost);
        DamnationDescription.SetMarkup(damnationDescription);
        DamnationPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = damnationBackgroundColor };
    }
}
