using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationsMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    public DevilDamnationsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(DevilDamnationsBuiState state)
    {
        // first clear out old
        DamnationsInfoBox.Orphan();
        DamnationCategories.DisposeAllChildren();
        DamnationCategories.AddChild(DamnationsInfoBox);
        DamnationCategories.SetTabTitle(0, Loc.GetString("devil-damnations-info-title"));

        // now get all prototypes, and sort them into categories
        Dictionary<string, List<(DamnationPrototype, int)>> allDamnations = new();
        foreach (var damnationMeta in state.Damnations)
        {
            if (_prototypeManager.TryIndex(damnationMeta.Item1, out var damnation))
            {
                allDamnations.GetOrNew(damnation.Category).Add((damnation, damnationMeta.Item2));
            }
        }

        int tabIndex = 1;
        // all collated, so we can send them off to individual ui instances
        foreach (var category in allDamnations.Keys)
        {
            var categoryTitle = Loc.GetString("devil-damnations-category-" + category + "-title");

            var element = new DevilDamnationsCategory(categoryTitle, allDamnations[category]);
            DamnationCategories.AddChild(element);

            DamnationCategories.SetTabTitle(tabIndex, categoryTitle);
            tabIndex++;
        }

        DamnedCrewList.DisposeAllChildren();
        foreach (var (netuid, name) in state.DamnedEntities)
        {
            _entityManager.TryGetEntity(netuid, out var uid);
            if (uid is not EntityUid) continue;
            var view = new DevilDamnedCrewView(((EntityUid)uid, name));
            DamnedCrewList.AddChild(view);
        }
    }
}
