using Content.Client.Message;
using Content.Shared._Starlight.Devil;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Devil.Ui;

[GenerateTypedNameReferences]
public sealed partial class DevilDamnationsCategory : Control
{
    public DevilDamnationsCategory(string categoryTitle, List<(DamnationPrototype, int)> damnations)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        damnations.Sort((x, y) => x.Item1.Cost.CompareTo(y.Item1.Cost));

        CategoryTitle.SetMarkup(categoryTitle);

        foreach (var damnation in damnations)
        {
            var element = new DevilDamnationDisplay(damnation);
            DamnationsDisplayContainer.AddChild(element);
        }
    }
}
