using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.UserInterface;

/// <summary>
/// A <see cref="DefaultWindow"/> with a pop out button in its header. Pressing it moves the window's
/// contents into a real desktop window so it can be dragged to another monitor. The controls are
/// moved over, not rebuilt, so nothing loses its state.
/// </summary>
[GenerateTypedNameReferences]
[Virtual]
public partial class PopOutWindow : DefaultWindow, IPopOutWindow
{
    /// <summary>
    /// The content that moves out into the desktop window. Subclasses point this at their root container.
    /// </summary>
    protected virtual Control Control { get; } = default!;

    /// <summary>Fires when the window is closed for good (in-game or as a desktop window).</summary>
    public event Action? OnFinalClose;

    /// <summary>Fires right after the contents move into the desktop window.</summary>
    public event Action? OnPopout;

    private OSWindow? _popOutWindow;

    public PopOutWindow()
    {
        RobustXamlLoader.Load(this);
        OnClose += FinalClose;
        AddButton();
    }

    private void AddButton()
    {
        var button = new TextureButton
        {
            StyleClasses = { PopOutExtensions.PopOutButtonStyleClass },
            VerticalAlignment = VAlignment.Center,
            ToolTip = "Pop Out",
            Margin = new Thickness(0, 0, 6, 0)
        };
        if (!WindowHeader.Children.OfType<BoxContainer>().TryFirstOrDefault(out var header))
            return;

        header.AddChild(button);
        button.SetPositionInParent(header.ChildCount - 2);
        button.OnPressed += _ =>
        {
            // We're about to close the in-game window on purpose, so don't treat that as closing for good.
            OnClose -= FinalClose;

            Control.Orphan();
            Close();

            _popOutWindow = PopOutHelper.Show(Title ?? string.Empty, Size, Control, () => OnFinalClose?.Invoke());

            OnPopout?.Invoke();
        };
    }

    private void FinalClose() => OnFinalClose?.Invoke();

    public void DisposePopOut() => _popOutWindow?.Close();
}
