- type: quickPhrase
  id: BaseCentralcommandPhrase
  group: CentralCommand
  styleClass: CentralCommandButton
  abstract: true

- type: quickPhrase
  id: BaseNanotrasenPhrase
  group: Nanotrasen
  styleClass: NanotrasenButton
  abstract: true
