using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class MasterDispenserLinkWindow : FancyWindow
{
    public event Action<NetEntity>? OnChemMasterSelected;

    public MasterDispenserLinkWindow()
    {
        RobustXamlLoader.Load(this);

        ChemMasterList.OnItemSelected += args =>
        {
            var item = ChemMasterList[args.ItemIndex];
            if (item.Metadata is NetEntity netEnt)
                OnChemMasterSelected?.Invoke(netEnt);
        };
    }

    public void UpdateList(List<(NetEntity Entity, string Text, string Beacon)> chemMasters)
    {
        ChemMasterList.Clear();
        foreach (var (entity, text, _) in chemMasters)
        {
            ChemMasterList.Add(new ItemList.Item(ChemMasterList)
            {
                Text = text,
                Metadata = entity
            });
        }
    }
}
