using System.Linq;
using Content.Shared._Sol.Medical.Allergy;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sol.Medical.Allergy.UI;

/// <summary>
/// Lobby character-editor tab for selecting mechanical allergies and intensity.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AllergyEditorGui : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<List<CharacterAllergyPreference>>? OnAllergiesChanged;

    private readonly Dictionary<ProtoId<AllergyPrototype>, AllergyEntry> _entries = new();
    private readonly Dictionary<ProtoId<AllergyPrototype>, CharacterAllergyPreference> _selected = new();
    private readonly HashSet<ProtoId<AllergyPrototype>> _innate = new();
    private string _search = string.Empty;
    private bool _suppressEvents;

    public AllergyEditorGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += args =>
        {
            _search = args.Text.Trim();
            ApplySearchFilter();
        };

        PopulateEntries();
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        _suppressEvents = true;
        _selected.Clear();
        _innate.Clear();

        var species = profile?.Species;
        if (species != null)
        {
            foreach (var proto in _prototypes.EnumeratePrototypes<AllergyPrototype>())
            {
                if (proto.InnateSpecies.Any(s => s.Id == species))
                    _innate.Add(proto.ID);
            }
        }

        if (profile != null)
        {
            foreach (var entry in profile.SolAllergies)
            {
                if (!_prototypes.HasIndex(entry.AllergyId) || _innate.Contains(entry.AllergyId))
                    continue;
                _selected[entry.AllergyId] = new CharacterAllergyPreference(entry);
            }
        }

        foreach (var (id, control) in _entries)
        {
            if (_innate.Contains(id))
                control.SetState(true, _prototypes.Index(id).DefaultSeverity, locked: true);
            else if (_selected.TryGetValue(id, out var selected))
                control.SetState(true, selected.Severity);
            else
                control.SetState(false, _prototypes.Index(id).DefaultSeverity);
        }

        ApplySearchFilter();
        _suppressEvents = false;
    }

    private void PopulateEntries()
    {
        EntriesContainer.RemoveAllChildren();
        _entries.Clear();

        foreach (var allergy in _prototypes.EnumeratePrototypes<AllergyPrototype>()
                     .OrderBy(a => Loc.GetString(a.Name)))
        {
            var entry = new AllergyEntry(allergy);
            entry.OnChanged += OnEntryChanged;
            _entries[allergy.ID] = entry;
            EntriesContainer.AddChild(entry);
        }
    }

    private void OnEntryChanged(ProtoId<AllergyPrototype> allergyId, bool selected, AllergySeverity severity)
    {
        if (_suppressEvents)
            return;

        if (selected)
            _selected[allergyId] = new CharacterAllergyPreference(allergyId, severity);
        else
            _selected.Remove(allergyId);

        OnAllergiesChanged?.Invoke(_selected.Values
            .OrderBy(a => a.AllergyId.Id)
            .Select(a => new CharacterAllergyPreference(a))
            .ToList());
    }

    private void ApplySearchFilter()
    {
        foreach (var (id, control) in _entries)
        {
            if (string.IsNullOrWhiteSpace(_search))
            {
                control.Visible = true;
                continue;
            }

            var proto = _prototypes.Index(id);
            var name = Loc.GetString(proto.Name);
            var desc = Loc.GetString(proto.Description);
            control.Visible =
                name.Contains(_search, StringComparison.OrdinalIgnoreCase) ||
                desc.Contains(_search, StringComparison.OrdinalIgnoreCase) ||
                proto.ID.Contains(_search, StringComparison.OrdinalIgnoreCase);
        }
    }
}
