using Content.Client.Materials;
using Content.Client.Stylesheets;
using Content.Shared.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Cargo.MaterialDispenser;

/// <summary>
/// This widget is one row in the material storage buffer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DispenserMaterialDisplay : PanelContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly MaterialStorageSystem _materialStorage;

    public event Action<string, int>? OnAmountButton;

    private int _volume;
    public readonly string Material;

    public DispenserMaterialDisplay(string material, int volume)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        var spriteSys = _entityManager.System<SpriteSystem>();
        Icon.Texture = spriteSys.Frame0(_prototypeManager.Index<MaterialPrototype>(material).Icon);

        Material = material;
        UpdateVolume(volume);
    }

    public void UpdateVolume(int volume)
    {
        if (_volume == volume)
            return;

        _volume = volume;
        var matProto = _prototypeManager.Index<MaterialPrototype>(Material);

        var sheetVolume = _materialStorage.GetSheetVolume(matProto);
        var sheets = (float) volume / sheetVolume;
        var maxEjectableSheets = (int) MathF.Floor(sheets);

        var unit = Loc.GetString(matProto.Unit);
        var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
        var name = Loc.GetString(matProto.Name);
        var mat = Loc.GetString("lathe-menu-material-display", ("material", name), ("amount", amountText));
        ProductName.Text = mat;

        PopulateButtons(maxEjectableSheets);
    }

    public void PopulateButtons(int maxEjectableSheets)
    {
        Content.Children.Clear();
        int[] sheetsToEjectArray = { 1, 5, 10, 30, 90 };

        for (var i = 0; i < sheetsToEjectArray.Length; i++)
        {
            var sheetsToEject = sheetsToEjectArray[i];

            var styleClass = StyleClass.ButtonOpenBoth;
            if (i == 0)
                styleClass = StyleClass.ButtonOpenRight;
            else if (i == sheetsToEjectArray.Length - 1)
                styleClass = StyleClass.ButtonOpenLeft;

            var button = new Button
            {
                Name = $"{sheetsToEject}",
                Access = AccessLevel.Public,
                Text = $"{sheetsToEject}",
                MinWidth = 45,
                StyleClasses = { styleClass }
            };

            button.OnPressed += _ =>
            {
                OnAmountButton?.Invoke(Material, sheetsToEject);
            };

            button.Disabled = maxEjectableSheets < sheetsToEject;

            if (_prototypeManager.TryIndex<MaterialPrototype>(Material, out var proto))
            {
                button.ToolTip = Loc.GetString("lathe-menu-tooltip-display", ("amount", sheetsToEject), ("material", Loc.GetString(proto.Name)));
            }

            Content.AddChild(button);
        }
    }
}
