using System.Linq;
using Content.Client.Cargo.Systems;
using Content.Client.Materials;
using Content.Client.Materials.UI;
using Content.Client.Station;
using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Cargo.MaterialDispenser;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Materials;
using Content.Shared.Station;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Cargo.MaterialDispenser;

[GenerateTypedNameReferences]
public sealed partial class MaterialDispenserWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly CargoSystem _cargoSystem;
    private readonly SharedStationSystem _stationSystem;
    private readonly SharedMaterialStorageSystem _materialStorageSystem;

    private EntityUid _owner;
    private readonly Dictionary<int, string> _departmentOptions = new();

    public event Action<string>? OnDepartmentSelected;
    public event Action<string, int,bool>? OnAmountButton;

    public MaterialDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _cargoSystem = _entityManager.System<CargoSystem>();
        _stationSystem = _entityManager.System<SharedStationSystem>();
        _materialStorageSystem = _entityManager.System<SharedMaterialStorageSystem>();

        DepartmentSelector.OnItemSelected += args =>
        {
            OnDepartmentSelected?.Invoke(_departmentOptions[args.Id]);
            args.Button.Select(args.Id);
        };
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        PopulateDepartmentSelector();
    }

    public void UpdateState(MaterialDispenserBoundUserInterfaceState castState)
    {
        if (castState.Mode == MaterialDispenserMode.Eject)
        {
            StorageTransferButton.Pressed = false;
            StorageEjectButton.Pressed = true;
        }
        else if (castState.Mode == MaterialDispenserMode.Transfer)
        {
            StorageTransferButton.Pressed = true;
            StorageEjectButton.Pressed = false;
        }

        SetSelectDepartment(castState.CargoAccount);
        OutputCrateInfo.RemoveAllChildren();
        if (castState.Buffer.Count == 0)
        {
            OutputCrateInfo.AddChild(new Label { Name = "NoMatsInCrate", Text = Loc.GetString("Crate is currently empty") });
        }
        else
        {
            foreach (var item in castState.Buffer)
            {
                var control = new DispenserMaterialDisplay(item.Key, item.Value);
                control.OnAmountButton += (s, i) => OnAmountButton?.Invoke(s, i, false);
                OutputCrateInfo.AddChild(control);
            }
        }

        NoMatsInCrate.Visible = OutputCrateInfo.ChildCount == 0;
        PopulateBuffer();

    }

    private void SetSelectDepartment(string cargoAccount)
    {
        var id = _departmentOptions.FirstOrDefault(x => x.Value == cargoAccount);
        DepartmentSelector.Select(id.Key);
    }

    private void PopulateDepartmentSelector()
    {
        var stationEntity = _stationSystem.GetOwningStation(_owner);
        if (stationEntity == null) return;
        var accounts = _cargoSystem.GetAccounts((Entity<StationBankAccountComponent?>)stationEntity);
        var i = 0;
        foreach (var account in accounts)
        {
            DepartmentSelector.AddItem(account.Key.Id, i);
            _departmentOptions[i] = account.Key.Id;
            i++;
        }
    }

    private void PopulateBuffer()
    {
        BufferInfo.RemoveAllChildren();

        var mats = _materialStorageSystem.GetStoredMaterials(_owner);
        foreach (var item in mats)
        {
            var control = new DispenserMaterialDisplay(item.Key, item.Value);
            control.OnAmountButton += (s, i) => OnAmountButton?.Invoke(s, i, true);
            BufferInfo.AddChild(control);
        }
        NoMats.Visible = BufferInfo.ChildCount == 0;
    }
}
