using Content.Client.Message;
using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Systems.Admin;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IConfigurationManager _configurationManager = default!;
        [Dependency] private IClientAdminManager _adminManager = default!;

        private string _serverName = string.Empty;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            AdminButton.OnPressed += _ => UserInterfaceManager.GetUIController<AdminUIController>().Toggle();
            _adminManager.AdminStatusUpdated += UpdateAdminButton;
            UpdateAdminButton();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            //Starlight start
            _serverName = _configurationManager.GetCVar(StarlightCCVars.ServerName);
            _configurationManager.OnValueChanged(StarlightCCVars.ServerName, OnServerNameChanged, true);

            ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", _serverName));
            //Starlight end
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void OnServerNameChanged(string serverName)
        {
            ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", serverName));
            _serverName = serverName;
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        private void UpdateAdminButton()
        {
            AdminButton.Visible = _adminManager.CanAdminMenu();
        }

        protected override void Dispose(bool disposing)
        {
            _adminManager.AdminStatusUpdated -= UpdateAdminButton;
            base.Dispose(disposing);
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
