- type: rank
  id: CargoSpecialist
  name: job-name-cargospecialist
  requirement: CargoPrestigeReq
  priority: High

- type: rank
  id: MailSpecialist
  name: job-name-mailspecialist
  requirement: CargoPrestigeReq
  priority: High

- type: rank
  id: ModelSalvager
  name: job-name-modelsalvager
  requirement: CargoPrestigeReq
  priority: High

- type: rank
  id: ModelSalvageLead
  name: job-name-modelsalvagelead
  requirement: CargoPrestigeReq
  priority: High

- type: rank
  id: QuartermasterGeneral
  name: job-name-quartermastergeneral
  requirement: CargoPrestigeReq
  priority: High
