- type: rank
  id: MasterJanitor
  name: job-name-masterjanitor
  requirement: ServicePrestigeReq
  priority: High

- type: rank
  id: MasterBartender
  name: job-name-masterbartender
  requirement: ServicePrestigeReq
  priority: High

- type: rank
  id: MessOfficer
  name: job-name-messofficer
  requirement: ServicePrestigeReq
  priority: High

- type: rank
  id: MasterBotanist
  name: job-name-masterbotanist
  requirement: ServicePrestigeReq
  priority: High

- type: rank
  id: ChiefSteward
  name: job-name-chiefsteward
  requirement: ServicePrestigeReq
  priority: High
