- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 18000 # 5 hours
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    HeadOfSecurity:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hours
    - !type:OverallPlaytimeRequirement
      time: 18000 # 5 hours
    ChiefEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10800 # 3 hours
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10800 # 3 hours
    ChiefMedicalOfficer:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10800 # 3 hours
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 18000 # 5 hours
    - !type:OverallPlaytimeRequirement
      time: 25200 # 7 hours
    Quartermaster:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hours
    SalvageSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 0
    CargoTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0 

    Bartender:
    - !type:OverallPlaytimeRequirement
      time: 0     
    Botanist:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Chaplain:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Chef:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Clown:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Janitor:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Lawyer:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Librarian:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Musician:
    - !type:OverallPlaytimeRequirement
      time: 0    
    ServiceWorker:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Visitor:
    - !type:OverallPlaytimeRequirement
      time: 0    

    AtmosphericTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0    
    StationEngineer:
    - !type:OverallPlaytimeRequirement
      time: 0    

    Chemist:
    - !type:OverallPlaytimeRequirement
      time: 0    
    MedicalDoctor:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Paramedic:
    - !type:OverallPlaytimeRequirement
      time: 0  

    Borg:
    - !type:OverallPlaytimeRequirement
      time: 0    
    Scientist:
    - !type:OverallPlaytimeRequirement
      time: 0   

    Detective:
    - !type:OverallPlaytimeRequirement
      time: 3600    
    SecurityOfficer:
    - !type:OverallPlaytimeRequirement
      time: 3600    
    Warden:
    - !type:OverallPlaytimeRequirement
      time: 3600