using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class OptionsSightPreview : Control
{
    private readonly SightRender _render;

    public OptionsSightPreview()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        MinSize = new Vector2(64, 64);

        _render = new SightRender();
        SightPanel.Children.Add(_render);
    }

    public void UpdateTexture(Texture sight, float scale, float offset, Color main, Color second) 
        => _render.UpdateTexture(sight, scale, offset, main, second);

    public void SetBrackets(Texture? left = null, Texture? right = null, Texture? down = null, Texture? up = null) 
        => _render.SetBrackets(left, right, down, up);

    protected override Vector2 MeasureOverride(Vector2 availableSize) 
        => new Vector2(140, 140);
}

public sealed class SightRender : Control
{
    private Texture? _center;
    private Texture? _bracket1;
    private Texture? _bracket2;
    private Texture? _bracket3;
    private Texture? _bracket4;

    private float _scale = 1f;
    private float _offset = 0f;

    private Color _main = Color.White;
    private Color _second = Color.Black;
    public void UpdateTexture(Texture sight, float scale, float offset, Color main, Color second)
    {
        _center = sight;
        _scale = scale;
        _offset = offset;
        _main = main;
        _second = second;
        UpdateDraw();
    }

    public void SetBrackets(Texture? left = null, Texture? right = null, Texture? down = null, Texture? up = null)
    {
        _bracket1 = left;
        _bracket2 = right;
        _bracket3 = down;
        _bracket4 = up;
        UpdateDraw();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_center == null)
            return;

        var centerPos = Size / 2f;

        DrawPart(handle, _center, centerPos, _scale, _main, _second);

        if (_bracket1 == null || _bracket2 == null)
            return;

        var bracketSize1 = _bracket1.Size * _scale;
        var bracketSize2 = _bracket2.Size * _scale;

        var leftPos = centerPos + new Vector2(-_offset - bracketSize1.X * 0.5f, 0f);
        var rightPos = centerPos + new Vector2(_offset + bracketSize2.X * 0.5f, 0f);

        DrawPart(handle, _bracket1, leftPos, _scale, _main, _second);
        DrawPart(handle, _bracket2, rightPos, _scale, _main, _second);

        if (_bracket3 != null)
        {
            var downPos = centerPos + new Vector2(0f, _offset + bracketSize1.Y * 0.5f);
            DrawPart(handle, _bracket3, downPos, _scale, _main, _second);
        }

        if (_bracket4 != null)
        {
            var upPos = centerPos + new Vector2(0f, -_offset - bracketSize2.Y * 0.5f);
            DrawPart(handle, _bracket4, upPos, _scale, _main, _second);
        }
    }

    private static void DrawPart(DrawingHandleScreen screen, Texture texture, Vector2 pos, float scale, Color main, Color stroke)
    {
        var size = texture.Size * scale;

        screen.DrawTextureRect(texture,
            UIBox2.FromDimensions(pos - size * 0.5f, size), stroke);

        screen.DrawTextureRect(texture,
            UIBox2.FromDimensions(pos - size * 0.5f - new Vector2(3f, 3f),
            size + new Vector2(7f, 7f)), main);
    }
}