using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.UI.Setup;

[GenerateTypedNameReferences]
public sealed partial class SetupMenu : DefaultWindow
{
    public Action<string>? OnNameConfirm;

    public SetupMenu()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);

        NameConfirm.OnPressed += _ => OnNameConfirm?.Invoke(DeviceName.Text);
    }

    public void HideNameSetter() => NamingSection.Visible = false;

    public void UpdateState(string name, bool disableNaming)
    {
        DeviceName.Text = name;
        DeviceName.Editable = !disableNaming;
        NameConfirm.Disabled = disableNaming;
    }
}

