using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Samurai;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Samurai.Eui;

[GenerateTypedNameReferences]
public sealed partial class SamuraiCodeUi : FancyWindow
{
    public event Action? OnSave;

    private List<SamuraiCode> _codes = [];

    public SamuraiCodeUi()
    {
        RobustXamlLoader.Load(this);
        NewCodeButton.OnPressed += _ => AddNewCode();
        SaveButton.OnPressed += _ => OnSave?.Invoke();
    }

    private void AddNewCode()
        => CodeContainer.AddChild(new CodeContainer());

    public List<SamuraiCode> GetCodes()
    {
        var newCodes = new List<SamuraiCode>();

        foreach (var control in CodeContainer.Children)
        {
            if (control is not CodeContainer codeControl)
                continue;

            var title = codeControl.CodeTitle;
            if (string.IsNullOrWhiteSpace(title))
                continue;

            var codeText = codeControl.CodeText;
            if (string.IsNullOrWhiteSpace(codeText))
                continue;

            var code = new SamuraiCode()
            {
                CodeName = title,
                CodeDesc = codeText,
            };

            newCodes.Add(code);
        }

        return newCodes;
    }

    private void MoveUp(int index)
    {
        if (index <= 0)
            return;

        (_codes[index], _codes[index - 1]) = (_codes[index - 1], _codes[index]);
        SetCodes(_codes);
    }

    private void MoveDown(int index)
    {
        if (index >= _codes.Count - 1)
            return;

        (_codes[index], _codes[index + 1]) = (_codes[index + 1], _codes[index]);
        SetCodes(_codes);
    }

    private void Delete(int index)
    {
        _codes.RemoveAt(index);

        SetCodes(_codes);
    }

    public void SetCodes(List<SamuraiCode> codes)
    {
        _codes = codes;
        CodeContainer.RemoveAllChildren();
        for (var i = 0; i < codes.Count; i++)
        {
            var index = i; // Copy for the closures
            var codeControl = new CodeContainer(codes[i]);
            codeControl.OnMoveUp += () => MoveUp(index);
            codeControl.OnMoveDown += () => MoveDown(index);
            codeControl.OnDelete += () => Delete(index);
            CodeContainer.AddChild(codeControl);
        }
    }
}
