using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._TP.Kitchen;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Guidebook.Controls;

/// <summary>
/// Control for embedding a deep fryer recipe into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideDeepFryerEmbed : PanelContainer, IDocumentTag, ISearchableControl, IPrototypeRepresentationControl
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill = default!;

    public IPrototype? RepresentedPrototype { get; private set; }

    public GuideDeepFryerEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;

        _sawmill = _logManager.GetSawmill("guidebook.deepfryer");
    }

    public GuideDeepFryerEmbed(string recipe) : this()
        => GenerateControl(_prototype.Index<DeepFryingRecipePrototype>(recipe));

    public GuideDeepFryerEmbed(DeepFryingRecipePrototype recipe) : this()
        => GenerateControl(recipe);

    public bool CheckMatchesSearch(string query)
        => this.ChildrenContainText(query);

    public void SetHiddenState(bool state, string query)
        => Visible = CheckMatchesSearch(query) ? state : !state;

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("Recipe embed tag is missing recipe prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<DeepFryingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified recipe prototype \"{id}\" is not a valid recipe prototype");
            return false;
        }

        GenerateControl(recipe);

        control = this;
        return true;
    }

    private void GenerateHeader(DeepFryingRecipePrototype recipe)
    {
        var entity = _prototype.Index<EntityPrototype>(recipe.Result);

        RepresentedPrototype = entity;

        IconContainer.AddChild(new GuideEntityEmbed(recipe.Result, false, false));
        ResultName.SetMarkup(entity.Name);
        ResultDescription.SetMarkup(entity.Description);
    }

    private void GenerateSolidIngredients(DeepFryingRecipePrototype recipe)
    {
        var product = recipe.Ingredient;
        var ingredient = _prototype.Index<EntityPrototype>(product);

        IngredientsGrid.AddChild(new GuideEntityEmbed(product, false, false));

        // solid name

        var solidNameMsg = new FormattedMessage();
        solidNameMsg.AddMarkupOrThrow(Loc.GetString("guidebook-microwave-solid-name-display", ("ingredient", ingredient.Name)));
        solidNameMsg.Pop();

        var solidNameLabel = new GuidebookRichPrototypeLink();
        solidNameLabel.SetMessage(solidNameMsg);
        solidNameLabel.LinkedPrototype = ingredient;

        IngredientsGrid.AddChild(solidNameLabel);
    }

    private void GenerateIngredients(DeepFryingRecipePrototype recipe)
        => GenerateSolidIngredients(recipe);

    private void GenerateCookTime(DeepFryingRecipePrototype recipe)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-microwave-cook-time", ("time", recipe.CookTime)));
        msg.Pop();

        CookTimeLabel.SetMessage(msg);
    }

    private void GenerateDeviceType(DeepFryingRecipePrototype _)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-microwave-device-type", ("type", "Deep Fryer")));
        msg.Pop();

        DeviceTypeLabel.SetMessage(msg);
    }

    private void GenerateControl(DeepFryingRecipePrototype recipe)
    {
        GenerateHeader(recipe);
        GenerateIngredients(recipe);
        GenerateCookTime(recipe);
        GenerateDeviceType(recipe);
    }
}
