using Content.Server.Anomaly;
using Content.Server.Anomaly.Components;
using Content.Server.Chat.Systems;
using Content.Server.Explosion.EntitySystems;
using Content.Server.Power.EntitySystems;
using Content.Server.Radio.EntitySystems;
using Content.Server.Station.Systems;
using Content.Shared.Anomaly.Components;
using Content.Shared.Radio;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Server.ArcanusFlux;

/// <summary>
/// Tracks station-wide Arcanus Flux — Nullscar pollution caused by anomaly presence.
/// Flux is generated by ALL anomalies on the station grid, no vessel link required.
/// Scaling is non-linear: each additional anomaly compounds flux gain, not just adds to it.
///
/// Thresholds:
///   250  — First science radio warning.
///   500  — CC announcement about Nullscar disturbance; Extreme Anomaly events begin spawning.
///   700  — Generator overload: any powered anomaly generator will explode after sustained exposure.
///  1000  — Maximum (hard cap).
///
/// Extreme Anomalies are overclocked anomalies that generate extra flux per second and
/// snowball the Nullscar level further.
/// </summary>
public sealed class ArcanusFluxSystem : EntitySystem
{
    [Dependency] private readonly ChatSystem _chat = default!;
    [Dependency] private readonly ExplosionSystem _explosion = default!;
    [Dependency] private readonly RadioSystem _radio = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly StationSystem _station = default!;
    [Dependency] private readonly AnomalySystem _anomaly = default!;

    // ── Constants ─────────────────────────────────────────────────────────────

    /// <summary>Maximum possible flux level.</summary>
    public const float MaxFlux = 1000f;

    /// <summary>First science radio warning threshold.</summary>
    public const float WarnThreshold = 250f;

    /// <summary>CC announcement + extreme anomaly spawning begins.</summary>
    public const float CriticalThreshold = 500f;

    /// <summary>Flux level at which the generator overload timer starts ticking.</summary>
    public const float OverloadThreshold = 700f;

    /// <summary>How long (seconds) flux must stay at or above <see cref="OverloadThreshold"/> before generators explode.</summary>
    public const float OverloadDuration = 60f; // 1 minute

    /// <summary>
    /// Base Arcanus Flux coefficient per second. Scaling is non-linear:
    ///   gain = BaseFlux × anomalyCount^1.4
    /// Calibrated for ~90-minute rounds:
    ///   1 anomaly  → ~155 AF/round  (safe all round)
    ///   2 anomalies → ~410 AF/round  (250 warning at ~55 min)
    ///   3 anomalies → ~722 AF/round  (250 at ~31 min, 500 at ~62 min)
    ///   4 anomalies → ~1082 AF/round (250 at ~21 min, 500 at ~41 min)
    /// </summary>
    public const float BaseFluxPerAnomalyPerSecond = 0.0287f;

    /// <summary>
    /// Extra flux per Extreme anomaly per second (added on top of the scaled base rate).
    /// ~10 min from 500→700 with 2 extremes + 3 normal anomalies.
    /// </summary>
    public const float ExtraFluxPerExtremeAnomalyPerSecond = 0.5f;

    /// <summary>
    /// Probability per second (when flux ≥ <see cref="CriticalThreshold"/>) that an existing normal
    /// anomaly becomes Extreme.
    /// </summary>
    public const float ExtremeConversionChancePerSecond = 0.005f;

    private static readonly ProtoId<RadioChannelPrototype> ScienceChannel = "Science";

    // ── State ─────────────────────────────────────────────────────────────────

    private float _flux = 0f;

    // Threshold crossed flags — reset when flux drops back below each threshold
    private bool _sentWarnAlert = false;
    private bool _sentCriticalAlert = false;

    // Generator overload state
    private float _overloadAccumulated = 0f; // seconds spent above OverloadThreshold
    private bool _overloadWarned = false;

    private float _tickAccumulated = 0f;

    /// <summary>Current Arcanus Flux level, clamped to [0, <see cref="MaxFlux"/>].</summary>
    public float Flux => _flux;

    // ── Update ────────────────────────────────────────────────────────────────

    public override void Update(float frameTime)
    {
        base.Update(frameTime);

        _tickAccumulated += frameTime;
        if (_tickAccumulated < 1f)
            return;

        var dt = _tickAccumulated;
        _tickAccumulated = 0f;

        // 1. Count ALL anomalies that exist anywhere (global — no vessel link needed).
        //    Extreme anomalies are also counted in the base total, plus they add bonus flux.
        var anomalyCount = 0;
        var extremeCount = 0;
        var anomalyQuery = EntityQueryEnumerator<AnomalyComponent>();
        while (anomalyQuery.MoveNext(out _, out _))
            anomalyCount++;

        var extremeQuery = EntityQueryEnumerator<ExtremeAnomalyComponent>();
        while (extremeQuery.MoveNext(out _, out _))
            extremeCount++;

        // 2. Non-linear scaling: each additional anomaly compounds the Nullscar growth.
        //    Formula: base × count^1.4  (2 anomalies = 2.64×, 4 = 6.96× a single anomaly)
        var scaledBase = anomalyCount > 0
            ? BaseFluxPerAnomalyPerSecond * MathF.Pow(anomalyCount, 1.4f)
            : 0f;
        var fluxGain = scaledBase * dt;
        fluxGain += extremeCount * ExtraFluxPerExtremeAnomalyPerSecond * dt;

        if (fluxGain > 0f)
            AddFlux(fluxGain);

        // 3. Try to convert a normal anomaly into an Extreme when flux is critical
        if (_flux >= CriticalThreshold)
            TrySpawnExtremeAnomaly(dt);

        // 4. Track generator overload
        UpdateGeneratorOverload(dt);
    }

    // ── Flux management ───────────────────────────────────────────────────────

    /// <summary>
    /// Add flux (negative to reduce). Fires threshold events as appropriate.
    /// </summary>
    public void AddFlux(float amount)
    {
        var old = _flux;
        _flux = Math.Clamp(_flux + amount, 0f, MaxFlux);

        // ── 250 warning ──────────────────────────────────────────
        if (!_sentWarnAlert && _flux >= WarnThreshold)
        {
            _sentWarnAlert = true;
            SendScienceAlert(Loc.GetString("arcanus-flux-alert-warn", ("flux", (int)_flux)));
        }
        if (_sentWarnAlert && _flux < WarnThreshold)
            _sentWarnAlert = false;

        // ── 500 critical ─────────────────────────────────────────
        if (!_sentCriticalAlert && _flux >= CriticalThreshold)
        {
            _sentCriticalAlert = true;
            SendScienceAlert(Loc.GetString("arcanus-flux-alert-critical", ("flux", (int)_flux)));
            SendNullscarAnnouncement();
        }
        if (_sentCriticalAlert && _flux < CriticalThreshold)
            _sentCriticalAlert = false;
    }

    /// <summary>Remove flux. Equivalent to <c>AddFlux(-amount)</c>.</summary>
    public void RemoveFlux(float amount) => AddFlux(-amount);

    // ── Generator overload ────────────────────────────────────────────────────

    private void UpdateGeneratorOverload(float dt)
    {
        if (_flux >= OverloadThreshold)
        {
            _overloadAccumulated += dt;

            // Warn at half overload time
            if (!_overloadWarned && _overloadAccumulated >= OverloadDuration * 0.5f)
            {
                _overloadWarned = true;
                SendScienceAlert(Loc.GetString("arcanus-flux-generator-overload-warning"));
            }

            // Explode at full overload time
            if (_overloadAccumulated >= OverloadDuration)
            {
                _overloadAccumulated = 0f;
                _overloadWarned = false;
                ExplodeGenerators();
            }
        }
        else
        {
            // Bleed accumulated overload back out when below threshold
            _overloadAccumulated = Math.Max(0f, _overloadAccumulated - dt * 2f);
            if (_overloadAccumulated == 0f)
                _overloadWarned = false;
        }
    }

    private void ExplodeGenerators()
    {
        var genQuery = EntityQueryEnumerator<AnomalyGeneratorComponent>();
        while (genQuery.MoveNext(out var uid, out _))
        {
            if (!this.IsPowered(uid, EntityManager))
                continue;

            // 1.5× the experimental vessel explosion (totalIntensity 500 → 750)
            _explosion.QueueExplosion(uid, "Default", totalIntensity: 750f, slope: 7.5f, maxTileIntensity: 50f);

            // Destroying the generator also dumps some flux back (the noosphere destabilises)
            AddFlux(50f);
        }

        SendScienceAlert(Loc.GetString("arcanus-flux-generator-exploded"));
        _chat.DispatchGlobalAnnouncement(
            Loc.GetString("arcanus-flux-nullscar-overload"),
            sender: Loc.GetString("arcanus-flux-cc-sender"),
            playSound: true,
            colorOverride: Color.DarkRed
        );
    }

    // ── Extreme anomaly spawning ──────────────────────────────────────────────

    private void TrySpawnExtremeAnomaly(float dt)
    {
        // Probability scales with how far above 500 we are
        var excessFraction = Math.Clamp((_flux - CriticalThreshold) / (MaxFlux - CriticalThreshold), 0f, 1f);
        var chance = ExtremeConversionChancePerSecond * (1f + excessFraction * 4f) * dt;

        if (!_random.Prob(chance))
            return;

        // Find any existing anomaly — use its grid as the spawn location
        EntityUid? grid = null;
        var anomalyQuery = EntityQueryEnumerator<AnomalyComponent>();
        if (anomalyQuery.MoveNext(out var existingUid, out _))
        {
            grid = Transform(existingUid).GridUid;
        }

        // Fall back to finding the station grid via any generator
        if (grid == null)
        {
            var genQuery = EntityQueryEnumerator<AnomalyGeneratorComponent>();
            if (genQuery.MoveNext(out var genUid, out _))
            {
                var xform = Transform(genUid);
                if (_station.GetStationInMap(xform.MapID) is { } station)
                    grid = _station.GetLargestGrid(station);
                else
                    grid = xform.GridUid;
            }
        }

        if (grid == null)
            return;

        // Spawn on a random tile of that grid using the returning overload
        var spawned = _anomaly.SpawnOnRandomGridLocationReturning(grid.Value, "RandomAnomalySpawner");
        if (spawned == null)
            return;

        // Mark as extreme and apply violent stats via AnomalySystem (which has write access)
        EnsureComp<ExtremeAnomalyComponent>(spawned.Value);
        _anomaly.ApplyExtremeAnomalyStats(spawned.Value);

        // Each extreme anomaly also immediately dumps extra flux into the Nullscar
        AddFlux(30f);

        SendScienceAlert(Loc.GetString("arcanus-flux-extreme-anomaly-spawned"));
    }

    // ── Announcements ─────────────────────────────────────────────────────────

    private void SendScienceAlert(string message)
    {
        var genQuery = EntityQueryEnumerator<AnomalyGeneratorComponent>();
        if (!genQuery.MoveNext(out var genUid, out _))
            return;

        _radio.SendRadioMessage(genUid, message, ScienceChannel, genUid);
    }

    private void SendNullscarAnnouncement()
    {
        _chat.DispatchGlobalAnnouncement(
            Loc.GetString("arcanus-flux-nullscar-announcement"),
            sender: Loc.GetString("arcanus-flux-cc-sender"),
            playSound: true,
            colorOverride: Color.MediumPurple
        );
    }
}
