using Content.Client.Message;
using Content.Shared._Starlight.Scent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Starlight.Scent;

[GenerateTypedNameReferences]
public sealed partial class ScentSniffMenu : DefaultWindow
{
    // Wired up by ScentSniffBoundUserInterface to send the message and close the window.
    public event Action<string>? OnTrackPressed;

    public ScentSniffMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<ScentTraceEntry> entries)
    {
        Rows.RemoveAllChildren();

        if (entries.Count == 0)
        {
            Rows.AddChild(new Label { Text = Loc.GetString("scent-sniff-window-empty") });
            return;
        }

        // Freshest first. Most likely to be the one someone actually wants to follow. Enum
        // values are already declared in freshest-to-stalest order.
        entries.Sort((a, b) => a.Freshness.CompareTo(b.Freshness));

        foreach (var entry in entries)
        {
            var color = GetFreshnessColor(entry.Freshness);

            var content = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            var idLabel = new RichTextLabel();
            var displayId = entry.ScentId.Length >= 8 ? entry.ScentId[..8] : entry.ScentId;
            idLabel.SetMarkup(Loc.GetString("scent-sniff-window-entry-id", ("id", displayId), ("color", color)));
            content.AddChild(idLabel);

            var detailLabel = new RichTextLabel();
            detailLabel.SetMarkup(Loc.GetString("scent-sniff-window-entry-detail",
                ("species", entry.Species), ("freshness", GetFreshnessLabel(entry.Freshness)), ("color", color)));
            content.AddChild(detailLabel);

            var row = new ContainerButton
            {
                ToolTip = Loc.GetString("scent-sniff-window-track-tooltip"),
                HorizontalExpand = true,
            };
            row.AddStyleClass(ContainerButton.StyleClassButton);
            row.AddChild(content);

            var scentId = entry.ScentId;
            row.OnPressed += _ => OnTrackPressed?.Invoke(scentId);

            Rows.AddChild(row);
        }
    }

    private static string GetFreshnessLabel(ScentFreshness freshness) => Loc.GetString(freshness switch
    {
        ScentFreshness.VeryFresh => "scent-freshness-very-fresh",
        ScentFreshness.Fresh => "scent-freshness-fresh",
        ScentFreshness.SomewhatFresh => "scent-freshness-somewhat-fresh",
        _ => "scent-freshness-not-very-fresh",
    });

    private static Color GetFreshnessColor(ScentFreshness freshness) => freshness switch
    {
        ScentFreshness.VeryFresh => Color.LightGreen,
        ScentFreshness.Fresh => Color.Green,
        ScentFreshness.SomewhatFresh => Color.Yellow,
        _ => Color.Red,
    };
}
