- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistolSP

- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult
