using Content.Client.Message;
using Content.Shared._Starlight.Samurai;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Samurai;

[GenerateTypedNameReferences]
public sealed partial class CodeDisplay : Control
{
    private static string GetSharedString()
        => $"[italic][font size=10][color=gray]{Loc.GetString("codes-ui-shared-code")}[/color][/font][/italic]";

    public CodeDisplay(SamuraiCode code, bool shared)
    {
        RobustXamlLoader.Load(this);

        var name = code.GetLocName();
        if (shared)
            CodeNameLabel.SetMarkup($"{name} {GetSharedString()}");
        else
            CodeNameLabel.SetMarkup(name);
        CodeDescLabel.SetMarkup(code.GetLocDesc());
    }
}
