using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Samurai;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Samurai;

[GenerateTypedNameReferences]
public sealed partial class SamuraiCodesMenu : FancyWindow
{
    public SamuraiCodesMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(SamuraiCodesComponent comp, SamuraiCodesBuiState state)
    {
        CodeDisplayContainer.Children.Clear();

        foreach (var code in state.SharedCodes)
            CodeDisplayContainer.AddChild(new CodeDisplay(code, true));

        foreach (var code in comp.Codes)
            CodeDisplayContainer.AddChild(new CodeDisplay(code, false));
    }
}
