- type: entity
  id: CrateServiceHydraRefill
  parent: CratePlastic
  name: hydra refill crate
  description: Contains two refills for the Hydra cleanade launcher.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: MagazineGrenadeCleanade
        amount: 2

- type: entity
  id: CrateServiceIceCreamMakerStarter
  parent: CrateFreezer
  name: ice cream maker starter crate
  description: Contains a flatpack of an ice cream maker, a jug of ice cream, cream, cocoa powder, berries, pistachios, and glasses.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: JugIceCream
          amount: 1
        - id: DrinkCreamCarton
          amount: 1
        - id: JugCocoaPowder
          amount: 1
        - id: FoodSnackPistachios
          amount: 5
        - id: FoodBerries
          amount: 9
        - id: IceCreamMakerFlatpack
          amount: 1
        - id: DrinkGlass
          amount: 5
