- type: cargoProduct
  id: SecurityReflectiveArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/armor_reflec.rsi
    state: icon
  product: CrateSecurityReflectiveArmor
  cost: 6000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecuritySandbags
  icon:
    sprite: _Starlight/Objects/Materials/sandbag.rsi
    state: sandbag_3
  product: CrateSecuritySandbags
  cost: 1000
  category: cargoproduct-category-name-security
  group: market
