# Sol mapping server — use with: config.presets=_Sol/sol,_Sol/solMapping
[server]
rules_file = "SolRuleset"

[nulllink.id]
server = "mapping"

[nulllink.roles_req]
admin_builder = "SolMapping"
title_builder = "Sol"
